In [1]:
import pandas as pd
import os

rainfall_path = r"D:\document\Brahmaputra-FloodCast\data\raw\assam_rainfall_2021_2025.csv"

print("File exists:", os.path.exists(rainfall_path))

rainfall = pd.read_csv(rainfall_path)

print("\nRAINFALL DATA LOADED")
print("=" * 60)
print("Shape:", rainfall.shape)

print("\nColumns:")
print(rainfall.columns.tolist())

print("\nFirst 5 rows:")
display(rainfall.head())

File exists: True

RAINFALL DATA LOADED
============================================================
Shape: (74560, 20)

Columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)']

First 5 rows:

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,River,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
0,1,Anipur WR Dept Quarter_1,Assam,18,Assam,293,KARIMGANJ,-,-,-,-,-,-,-,-,-,24.54791,92.432997,17-07-2022 16:00,2.0
1,2,Anipur WR Dept Quarter_1,Assam,18,Assam,293,KARIMGANJ,-,-,-,-,-,-,-,-,-,24.54791,92.432997,20-07-2022 02:00,1.0
2,3,Anipur WR Dept Quarter_1,Assam,18,Assam,293,KARIMGANJ,-,-,-,-,-,-,-,-,-,24.54791,92.432997,20-07-2022 12:00,1.0
3,4,Anipur WR Dept Quarter_1,Assam,18,Assam,293,KARIMGANJ,-,-,-,-,-,-,-,-,-,24.54791,92.432997,20-07-2022 13:00,1.0
4,5,Anipur WR Dept Quarter_1,Assam,18,Assam,293,KARIMGANJ,-,-,-,-,-,-,-,-,-,24.54791,92.432997,21-07-2022 23:00,1.0

In [2]:
# Find all rainfall stations available in DARRANG district

darrang_rainfall = rainfall[
    rainfall["District"].astype(str).str.strip().str.upper() == "DARRANG"
].copy()

print("DARRANG RAINFALL DATA")
print("=" * 60)

print("Rows:", len(darrang_rainfall))

print("\nStations available in DARRANG:")
print(
    darrang_rainfall["Station"]
    .dropna()
    .unique()
)

print("\nNumber of unique stations:")
print(darrang_rainfall["Station"].nunique())

DARRANG RAINFALL DATA
============================================================
Rows: 2721

Stations available in DARRANG:
<StringArray>
['NH15 Crossing Barnadi', 'NH15 Crossing Fakirpara Tangni']
Length: 2, dtype: str

Number of unique stations:
2

In [3]:
# Filter rainfall data for the same station as our water-level station

fakipara_rainfall = rainfall[
    rainfall["Station"].astype(str).str.strip() ==
    "NH15 Crossing Fakirpara Tangni"
].copy()

print("FAKIRPARA TANGNI RAINFALL CHECK")
print("=" * 60)

print("Rows:", len(fakipara_rainfall))

print("\nStation:")
print(fakipara_rainfall["Station"].unique())

print("\nDistrict:")
print(fakipara_rainfall["District"].unique())

print("\nCoordinates:")
print(
    fakipara_rainfall[
        ["Latitude", "Longitude"]
    ].drop_duplicates()
)

print("\nDate range:")
print("Start:", fakipara_rainfall["Data Acquisition Time"].min())
print("End:  ", fakipara_rainfall["Data Acquisition Time"].max())

print("\nRainfall statistics:")
print(
    fakipara_rainfall[
        "Telemetry Hourly Rainfall (mm)"
    ].describe()
)

print("\nMissing values:")
print(fakipara_rainfall.isna().sum())

FAKIRPARA TANGNI RAINFALL CHECK
============================================================
Rows: 1614

Station:
<StringArray>
['NH15 Crossing Fakirpara Tangni']
Length: 1, dtype: str

District:
<StringArray>
['DARRANG']
Length: 1, dtype: str

Coordinates:
        Latitude  Longitude
42215  26.508333  92.116389

Date range:
Start: 01-04-2022 01:00
End:   31-07-2024 19:00

Rainfall statistics:
count    1614.000000
mean       41.049628
std        34.994101
min         0.500000
25%         1.000000
50%        61.200000
75%        66.800000
max       381.000000
Name: Telemetry Hourly Rainfall (mm), dtype: float64

Missing values:
SlNo                              0
Station                           0
Agency                            0
State LGD Code                    0
State                             0
District LGD Code                 0
District                          0
Tehsil                            0
Block                             0
Village                           0
River                             0
Basin                             0
Tributary                         0
Subtributary                      0
SubSubtributary                   0
Local River                       0
Latitude                          0
Longitude                         0
Data Acquisition Time             0
Telemetry Hourly Rainfall (mm)    0
dtype: int64

In [4]:
# Convert rainfall timestamp to datetime

fakipara_rainfall["Data Acquisition Time"] = pd.to_datetime(
    fakipara_rainfall["Data Acquisition Time"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

print("RAINFALL TIMESTAMP CHECK")
print("=" * 60)

print("Data type:")
print(fakipara_rainfall["Data Acquisition Time"].dtype)

print("\nMissing timestamps after conversion:")
print(fakipara_rainfall["Data Acquisition Time"].isna().sum())

print("\nFirst 5 timestamps:")
print(fakipara_rainfall["Data Acquisition Time"].head())

print("\nLast 5 timestamps:")
print(fakipara_rainfall["Data Acquisition Time"].tail())

RAINFALL TIMESTAMP CHECK
============================================================
Data type:
datetime64[us]

Missing timestamps after conversion:
0

First 5 timestamps:
42215   2022-03-24 14:00:00
42216   2022-03-24 14:00:00
42217   2022-03-25 04:00:00
42218   2022-03-25 04:00:00
42219   2022-03-25 06:00:00
Name: Data Acquisition Time, dtype: datetime64[us]

Last 5 timestamps:
43824   2025-04-16 14:00:00
43825   2025-04-16 15:00:00
43826   2025-04-16 15:30:00
43827   2025-04-16 16:00:00
43828   2025-04-23 13:00:00
Name: Data Acquisition Time, dtype: datetime64[us]

In [5]:

print("ACTUAL RAINFALL COVERAGE CHECK")
print("=" * 60)

print("Start:", fakipara_rainfall["Data Acquisition Time"].min())
print("End:  ", fakipara_rainfall["Data Acquisition Time"].max())

print("\nRows:", len(fakipara_rainfall))

print("\nDuplicate timestamps:")
print(
    fakipara_rainfall["Data Acquisition Time"].duplicated().sum()
)

print("\nRainfall value summary:")
print(
    fakipara_rainfall[
        "Telemetry Hourly Rainfall (mm)"
    ].describe()
)

ACTUAL RAINFALL COVERAGE CHECK
============================================================
Start: 2022-03-24 14:00:00
End:   2025-04-23 13:00:00

Rows: 1614

Duplicate timestamps:
153

Rainfall value summary:
count    1614.000000
mean       41.049628
std        34.994101
min         0.500000
25%         1.000000
50%        61.200000
75%        66.800000
max       381.000000
Name: Telemetry Hourly Rainfall (mm), dtype: float64

In [6]:
# Check duplicate rainfall timestamps

duplicate_rainfall = fakipara_rainfall[
    fakipara_rainfall["Data Acquisition Time"].duplicated(
        keep=False
    )
].sort_values("Data Acquisition Time")

print("DUPLICATE RAINFALL TIMESTAMPS")
print("=" * 60)

print("Duplicate rows:", len(duplicate_rainfall))
print(
    "Duplicate timestamps:",
    duplicate_rainfall["Data Acquisition Time"].nunique()
)

print("\nFirst duplicate groups:")
display(
    duplicate_rainfall[
        [
            "Station",
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ].head(20)
)

DUPLICATE RAINFALL TIMESTAMPS
============================================================
Duplicate rows: 306
Duplicate timestamps: 153

First duplicate groups:

,Station,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
42215,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,14.0
42216,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,7.0
42217,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,1.0
42218,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,0.5
42220,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,22.0
42221,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,11.0
42222,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,7.0
42223,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,3.5
42225,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,2.0
42224,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,4.0
42226,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,1.0
42227,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,0.5
42228,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,1.0
42229,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,0.5
42230,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,1.0
42231,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,0.5
42232,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,1.0
42233,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,0.5
42235,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,4.5
42234,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,9.0

In [7]:
# Check how many rainfall observations occur per timestamp

timestamp_counts = (
    fakipara_rainfall
    .groupby("Data Acquisition Time")
    .size()
)

print("OBSERVATIONS PER TIMESTAMP")
print("=" * 60)

print("1 observation:", (timestamp_counts == 1).sum())
print("2 observations:", (timestamp_counts == 2).sum())
print("3+ observations:", (timestamp_counts >= 3).sum())

print("\nMaximum observations for one timestamp:")
print(timestamp_counts.max())

print("\nFrequency distribution:")
print(timestamp_counts.value_counts().sort_index())

OBSERVATIONS PER TIMESTAMP
============================================================
1 observation: 1308
2 observations: 153
3+ observations: 0

Maximum observations for one timestamp:
2

Frequency distribution:
1    1308
2     153
Name: count, dtype: int64

In [8]:
# Check the time difference between the two observations
# for duplicate timestamps

duplicate_pairs = (
    fakipara_rainfall[
        fakipara_rainfall["Data Acquisition Time"].duplicated(
            keep=False
        )
    ]
    .sort_values("Data Acquisition Time")
)

print("DUPLICATE PAIR TIME PATTERN")
print("=" * 60)

# Show selected columns
display(
    duplicate_pairs[
        [
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ].head(30)
)

print("\nUnique rainfall values in duplicate pairs:")
print(
    duplicate_pairs
    .groupby("Data Acquisition Time")[
        "Telemetry Hourly Rainfall (mm)"
    ]
    .agg(["min", "max", "mean"])
    .head(20)
)

DUPLICATE PAIR TIME PATTERN
============================================================

      Data Acquisition Time  Telemetry Hourly Rainfall (mm)
42215   2022-03-24 14:00:00                            14.0
42216   2022-03-24 14:00:00                             7.0
42217   2022-03-25 04:00:00                             1.0
42218   2022-03-25 04:00:00                             0.5
42220   2022-03-25 07:00:00                            22.0
42221   2022-03-25 07:00:00                            11.0
42222   2022-03-25 08:00:00                             7.0
42223   2022-03-25 08:00:00                             3.5
42225   2022-03-25 22:00:00                             2.0
42224   2022-03-25 22:00:00                             4.0
42226   2022-03-25 23:00:00                             1.0
42227   2022-03-25 23:00:00                             0.5
42228   2022-03-26 10:00:00                             1.0
42229   2022-03-26 10:00:00                             0.5
42230   2022-03-26 13:00:00                             1.0
42231   2022-03-26 13:00:00                             0.5
42232   2022-03-26 16:00:00                             1.0
42233   2022-03-26 16:00:00                             0.5
42235   2022-03-26 17:00:00                             4.5
42234   2022-03-26 17:00:00                             9.0
42237   2022-03-27 03:00:00                             1.0
42238   2022-03-27 03:00:00                             0.5
42239   2022-03-27 10:00:00                             1.0
42240   2022-03-27 10:00:00                             0.5
42242   2022-03-28 11:00:00                             1.0
42243   2022-03-28 11:00:00                             0.5
42247   2022-03-31 01:00:00                             1.0
42246   2022-03-31 01:00:00                             0.5
42249   2022-04-01 01:00:00                             0.5
42248   2022-04-01 01:00:00                             1.0

Unique rainfall values in duplicate pairs:
                        min   max   mean
Data Acquisition Time
2022-03-24 14:00:00     7.0  14.0  10.50
2022-03-25 04:00:00     0.5   1.0   0.75
2022-03-25 07:00:00    11.0  22.0  16.50
2022-03-25 08:00:00     3.5   7.0   5.25
2022-03-25 22:00:00     2.0   4.0   3.00
2022-03-25 23:00:00     0.5   1.0   0.75
2022-03-26 10:00:00     0.5   1.0   0.75
2022-03-26 13:00:00     0.5   1.0   0.75
2022-03-26 16:00:00     0.5   1.0   0.75
2022-03-26 17:00:00     4.5   9.0   6.75
2022-03-27 03:00:00     0.5   1.0   0.75
2022-03-27 10:00:00     0.5   1.0   0.75
2022-03-28 11:00:00     0.5   1.0   0.75
2022-03-31 01:00:00     0.5   1.0   0.75
2022-04-01 01:00:00     0.5   1.0   0.75
2022-04-02 04:00:00     0.5   1.0   0.75
2022-04-04 02:00:00     0.5   1.0   0.75
2022-04-04 10:00:00     0.5   1.0   0.75
2022-04-05 06:00:00     0.5   1.0   0.75
2022-04-05 13:00:00     0.5   1.0   0.75

In [9]:
# Check whether duplicate rainfall values follow a consistent ratio

duplicate_groups = (
    duplicate_rainfall
    .groupby("Data Acquisition Time")[
        "Telemetry Hourly Rainfall (mm)"
    ]
    .agg(["min", "max"])
)

duplicate_groups["ratio_max_min"] = (
    duplicate_groups["max"] / duplicate_groups["min"]
)

print("DUPLICATE VALUE RATIO CHECK")
print("=" * 60)

print(
    duplicate_groups["ratio_max_min"]
    .value_counts()
    .head(10)
)

print("\nRatio statistics:")
print(
    duplicate_groups["ratio_max_min"].describe()
)

print("\nExamples where ratio is close to 2:")
display(
    duplicate_groups[
        (duplicate_groups["ratio_max_min"] >= 1.99) &
        (duplicate_groups["ratio_max_min"] <= 2.01)
    ].head(20)
)

DUPLICATE VALUE RATIO CHECK
============================================================
ratio_max_min
2.0    146
1.0      7
Name: count, dtype: int64

Ratio statistics:
count    153.000000
mean       1.954248
std        0.209632
min        1.000000
25%        2.000000
50%        2.000000
75%        2.000000
max        2.000000
Name: ratio_max_min, dtype: float64

Examples where ratio is close to 2:

                        min   max  ratio_max_min
Data Acquisition Time
2022-03-24 14:00:00     7.0  14.0            2.0
2022-03-25 04:00:00     0.5   1.0            2.0
2022-03-25 07:00:00    11.0  22.0            2.0
2022-03-25 08:00:00     3.5   7.0            2.0
2022-03-25 22:00:00     2.0   4.0            2.0
2022-03-25 23:00:00     0.5   1.0            2.0
2022-03-26 10:00:00     0.5   1.0            2.0
2022-03-26 13:00:00     0.5   1.0            2.0
2022-03-26 16:00:00     0.5   1.0            2.0
2022-03-26 17:00:00     4.5   9.0            2.0
2022-03-27 03:00:00     0.5   1.0            2.0
2022-03-27 10:00:00     0.5   1.0            2.0
2022-03-28 11:00:00     0.5   1.0            2.0
2022-03-31 01:00:00     0.5   1.0            2.0
2022-04-01 01:00:00     0.5   1.0            2.0
2022-04-02 04:00:00     0.5   1.0            2.0
2022-04-04 02:00:00     0.5   1.0            2.0
2022-04-04 10:00:00     0.5   1.0            2.0
2022-04-05 06:00:00     0.5   1.0            2.0
2022-04-05 13:00:00     0.5   1.0            2.0

In [10]:
# Inspect metadata of duplicate rainfall records

duplicate_metadata = duplicate_rainfall[
    [
        "Station",
        "Agency",
        "State",
        "District",
        "Latitude",
        "Longitude",
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].copy()

print("DUPLICATE RECORD METADATA CHECK")
print("=" * 60)

display(duplicate_metadata.head(30))

DUPLICATE RECORD METADATA CHECK
============================================================

,Station,Agency,State,District,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
42215,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-24 14:00:00,14.0
42216,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-24 14:00:00,7.0
42217,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 04:00:00,1.0
42218,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 04:00:00,0.5
42220,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 07:00:00,22.0
42221,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 07:00:00,11.0
42222,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 08:00:00,7.0
42223,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 08:00:00,3.5
42225,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 22:00:00,2.0
42224,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 22:00:00,4.0
42226,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 23:00:00,1.0
42227,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 23:00:00,0.5
42228,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 10:00:00,1.0
42229,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 10:00:00,0.5
42230,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 13:00:00,1.0
42231,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 13:00:00,0.5
42232,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 16:00:00,1.0
42233,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 16:00:00,0.5
42235,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 17:00:00,4.5
42234,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 17:00:00,9.0
42237,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 03:00:00,1.0
42238,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 03:00:00,0.5
42239,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 10:00:00,1.0
42240,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 10:00:00,0.5
42242,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-28 11:00:00,1.0
42243,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-28 11:00:00,0.5
42247,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-31 01:00:00,1.0
42246,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-31 01:00:00,0.5
42249,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-01 01:00:00,0.5
42248,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-01 01:00:00,1.0

In [11]:
# Create a working copy of Fakirpara Tangni rainfall data

rainfall_2021_2025 = fakipara_rainfall.copy()

# Sort by timestamp
rainfall_2021_2025 = rainfall_2021_2025.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

print("RAINFALL WORKING DATASET")
print("=" * 60)

print("Rows:", len(rainfall_2021_2025))
print("Columns:", len(rainfall_2021_2025.columns))

print("\nDate range:")
print("Start:", rainfall_2021_2025["Data Acquisition Time"].min())
print("End:  ", rainfall_2021_2025["Data Acquisition Time"].max())

print("\nDuplicate timestamps:")
print(
    rainfall_2021_2025["Data Acquisition Time"].duplicated().sum()
)

print("\nMissing values:")
print(rainfall_2021_2025[
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].isna().sum())

RAINFALL WORKING DATASET
============================================================
Rows: 1614
Columns: 20

Date range:
Start: 2022-03-24 14:00:00
End:   2025-04-23 13:00:00

Duplicate timestamps:
153

Missing values:
Data Acquisition Time             0
Telemetry Hourly Rainfall (mm)    0
dtype: int64

In [12]:
import os

rainfall_2026_path = r"D:\document\Brahmaputra-FloodCast\data\raw\assam_rainfall_2026_2030.csv"

print("File exists:", os.path.exists(rainfall_2026_path))

File exists: False

In [13]:
import os

raw_path = r"D:\document\Brahmaputra-FloodCast\data\raw"

print("RAW FOLDER EXISTS:", os.path.exists(raw_path))

print("\nFiles in raw folder:")
print(os.listdir(raw_path))

RAW FOLDER EXISTS: True

Files in raw folder:
['assam_rainfall_2021_2025.csv', 'assam_water_level_2021_2025.csv', 'darrang_api1_raw.csv', 'darrang_api2_raw.csv']

In [14]:
import pandas as pd
import os

rainfall_2026_path = r"D:\document\Brahmaputra-FloodCast\data\raw\assam_rainfall_2026_2030.csv"

print("File exists:", os.path.exists(rainfall_2026_path))

rainfall_2026 = pd.read_csv(rainfall_2026_path)

print("\n2026–2030 RAINFALL DATA LOADED")
print("=" * 60)

print("Shape:", rainfall_2026.shape)

print("\nColumns:")
print(rainfall_2026.columns.tolist())

print("\nFirst 5 rows:")
display(rainfall_2026.head())

File exists: True

2026–2030 RAINFALL DATA LOADED
============================================================
Shape: (1336, 20)

Columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)']

First 5 rows:

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,River,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
0,1,AT Road Crossing Jorhat towni,Assam,18,Assam,290,JORHAT,-,-,-,-,-,-,-,-,-,26.76311,94.22003,11-05-2026 03:00,0.5
1,2,AT Road Crossing Jorhat towni,Assam,18,Assam,290,JORHAT,-,-,-,-,-,-,-,-,-,26.76311,94.22003,15-05-2026 17:00,0.5
2,3,AT Road Crossing Jorhat towni,Assam,18,Assam,290,JORHAT,-,-,-,-,-,-,-,-,-,26.76311,94.22003,17-05-2026 03:00,0.5
3,4,AT Road Crossing Jorhat towni,Assam,18,Assam,290,JORHAT,-,-,-,-,-,-,-,-,-,26.76311,94.22003,17-05-2026 04:00,0.5
4,5,AT Road Crossing Jorhat towni,Assam,18,Assam,290,JORHAT,-,-,-,-,-,-,-,-,-,26.76311,94.22003,17-05-2026 05:00,0.5

In [15]:
# Find rainfall stations available in DARRANG for the 2026–2030 dataset

darrang_rainfall_2026 = rainfall_2026[
    rainfall_2026["District"].astype(str).str.strip().str.upper() == "DARRANG"
].copy()

print("DARRANG 2026 RAINFALL DATA")
print("=" * 60)

print("Rows:", len(darrang_rainfall_2026))

print("\nStations available in DARRANG:")
print(darrang_rainfall_2026["Station"].dropna().unique())

print("\nNumber of unique stations:")
print(darrang_rainfall_2026["Station"].nunique())

DARRANG 2026 RAINFALL DATA
============================================================
Rows: 7

Stations available in DARRANG:
<StringArray>
['NH15 Crossing Fakirpara Tangni']
Length: 1, dtype: str

Number of unique stations:
1

In [16]:
# Filter the 2026 rainfall data for our target station

fakipara_rainfall_2026 = rainfall_2026[
    rainfall_2026["Station"].astype(str).str.strip() ==
    "NH15 Crossing Fakirpara Tangni"
].copy()

print("FAKIRPARA TANGNI 2026 RAINFALL CHECK")
print("=" * 60)

print("Rows:", len(fakipara_rainfall_2026))

print("\nStation:")
print(fakipara_rainfall_2026["Station"].unique())

print("\nDistrict:")
print(fakipara_rainfall_2026["District"].unique())

print("\nCoordinates:")
print(
    fakipara_rainfall_2026[
        ["Latitude", "Longitude"]
    ].drop_duplicates()
)

print("\nRaw timestamps:")
print(
    fakipara_rainfall_2026[
        "Data Acquisition Time"
    ].tolist()
)

print("\nRainfall values:")
print(
    fakipara_rainfall_2026[
        "Telemetry Hourly Rainfall (mm)"
    ].tolist()
)

print("\nMissing values:")
print(
    fakipara_rainfall_2026[
        [
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ].isna().sum()
)

FAKIRPARA TANGNI 2026 RAINFALL CHECK
============================================================
Rows: 7

Station:
<StringArray>
['NH15 Crossing Fakirpara Tangni']
Length: 1, dtype: str

District:
<StringArray>
['DARRANG']
Length: 1, dtype: str

Coordinates:
      Latitude  Longitude
878  26.508333  92.116389

Raw timestamps:
['22-05-2026 07:00', '23-05-2026 06:00', '23-05-2026 13:00', '23-05-2026 23:00', '24-05-2026 11:00', '25-05-2026 06:00', '27-05-2026 06:00']

Rainfall values:
[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

Missing values:
Data Acquisition Time             0
Telemetry Hourly Rainfall (mm)    0
dtype: int64

In [17]:
# Convert 2026 rainfall timestamps to datetime

fakipara_rainfall_2026["Data Acquisition Time"] = pd.to_datetime(
    fakipara_rainfall_2026["Data Acquisition Time"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

print("2026 RAINFALL TIMESTAMP CHECK")
print("=" * 60)

print("Data type:")
print(fakipara_rainfall_2026["Data Acquisition Time"].dtype)

print("\nMissing timestamps after conversion:")
print(
    fakipara_rainfall_2026["Data Acquisition Time"].isna().sum()
)

print("\nTimestamps:")
print(
    fakipara_rainfall_2026[
        "Data Acquisition Time"
    ].tolist()
)

print("\nDuplicate timestamps:")
print(
    fakipara_rainfall_2026[
        "Data Acquisition Time"
    ].duplicated().sum()
)

2026 RAINFALL TIMESTAMP CHECK
============================================================
Data type:
datetime64[us]

Missing timestamps after conversion:
0

Timestamps:
[Timestamp('2026-05-22 07:00:00'), Timestamp('2026-05-23 06:00:00'), Timestamp('2026-05-23 13:00:00'), Timestamp('2026-05-23 23:00:00'), Timestamp('2026-05-24 11:00:00'), Timestamp('2026-05-25 06:00:00'), Timestamp('2026-05-27 06:00:00')]

Duplicate timestamps:
0

In [18]:
# Check actual 2026 rainfall coverage

print("2026 RAINFALL COVERAGE CHECK")
print("=" * 60)

print("Start:")
print(fakipara_rainfall_2026["Data Acquisition Time"].min())

print("\nEnd:")
print(fakipara_rainfall_2026["Data Acquisition Time"].max())

print("\nTotal rows:")
print(len(fakipara_rainfall_2026))

print("\nDuplicate timestamps:")
print(
    fakipara_rainfall_2026[
        "Data Acquisition Time"
    ].duplicated().sum()
)

print("\nRainfall statistics:")
print(
    fakipara_rainfall_2026[
        "Telemetry Hourly Rainfall (mm)"
    ].describe()
)

print("\nTime gaps:")
sorted_2026 = fakipara_rainfall_2026.sort_values(
    "Data Acquisition Time"
).copy()

gaps_2026 = (
    sorted_2026["Data Acquisition Time"]
    .diff()
    .dropna()
)

print(gaps_2026)

2026 RAINFALL COVERAGE CHECK
============================================================
Start:
2026-05-22 07:00:00

End:
2026-05-27 06:00:00

Total rows:
7

Duplicate timestamps:
0

Rainfall statistics:
count    7.000000e+00
mean     2.000000e-01
std      2.997945e-17
min      2.000000e-01
25%      2.000000e-01
50%      2.000000e-01
75%      2.000000e-01
max      2.000000e-01
Name: Telemetry Hourly Rainfall (mm), dtype: float64

Time gaps:
879   0 days 23:00:00
880   0 days 07:00:00
881   0 days 10:00:00
882   0 days 12:00:00
883   0 days 19:00:00
884   2 days 00:00:00
Name: Data Acquisition Time, dtype: timedelta64[us]

In [19]:
# Check timestamp overlap between 2021–2025 and 2026 rainfall

rainfall_old_times = set(
    rainfall_2021_2025["Data Acquisition Time"]
)

rainfall_2026_times = set(
    fakipara_rainfall_2026["Data Acquisition Time"]
)

overlap_times = rainfall_old_times.intersection(
    rainfall_2026_times
)

print("RAINFALL DATASET OVERLAP CHECK")
print("=" * 60)

print("2021–2025 unique timestamps:",
      len(rainfall_old_times))

print("2026 unique timestamps:",
      len(rainfall_2026_times))

print("Overlapping timestamps:",
      len(overlap_times))

if len(overlap_times) > 0:
    print("\nOverlapping timestamps:")
    for timestamp in sorted(overlap_times):
        print(timestamp)
else:
    print("\nNo overlapping timestamps found.")

RAINFALL DATASET OVERLAP CHECK
============================================================
2021–2025 unique timestamps: 1461
2026 unique timestamps: 7
Overlapping timestamps: 0

No overlapping timestamps found.

In [20]:
# Final diagnostic of duplicate rainfall pairs

duplicate_groups = (
    rainfall_2021_2025[
        rainfall_2021_2025["Data Acquisition Time"].duplicated(
            keep=False
        )
    ]
    .groupby("Data Acquisition Time")[
        "Telemetry Hourly Rainfall (mm)"
    ]
    .agg(["min", "max", "count"])
)

duplicate_groups["ratio_max_min"] = (
    duplicate_groups["max"] /
    duplicate_groups["min"]
)

print("FINAL DUPLICATE RAINFALL DIAGNOSTIC")
print("=" * 60)

print("Duplicate timestamps:", len(duplicate_groups))

print("\nObservation count:")
print(duplicate_groups["count"].value_counts())

print("\nRatio distribution:")
print(duplicate_groups["ratio_max_min"].value_counts())

print("\nExact 2× pairs:")
print(
    (duplicate_groups["ratio_max_min"] == 2).sum()
)

print("\nExact equal pairs:")
print(
    (duplicate_groups["ratio_max_min"] == 1).sum()
)

print("\nOther ratios:")
print(
    (
        ~duplicate_groups["ratio_max_min"].isin([1, 2])
    ).sum()
)

FINAL DUPLICATE RAINFALL DIAGNOSTIC
============================================================
Duplicate timestamps: 153

Observation count:
count
2    153
Name: count, dtype: int64

Ratio distribution:
ratio_max_min
2.0    146
1.0      7
Name: count, dtype: int64

Exact 2× pairs:
146

Exact equal pairs:
7

Other ratios:
0

In [21]:
# Create a separate audit dataset for duplicate rainfall timestamps

duplicate_rainfall_audit = rainfall_2021_2025[
    rainfall_2021_2025["Data Acquisition Time"].duplicated(
        keep=False
    )
].copy()

duplicate_rainfall_audit = duplicate_rainfall_audit.sort_values(
    "Data Acquisition Time"
)

print("DUPLICATE RAINFALL AUDIT DATASET")
print("=" * 60)

print("Rows:", len(duplicate_rainfall_audit))

print("Unique duplicate timestamps:",
      duplicate_rainfall_audit["Data Acquisition Time"].nunique())

print("\nFirst 20 duplicate records:")
display(
    duplicate_rainfall_audit[
        [
            "Station",
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ].head(20)
)

DUPLICATE RAINFALL AUDIT DATASET
============================================================
Rows: 306
Unique duplicate timestamps: 153

First 20 duplicate records:

,Station,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
0,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,14.0
1,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,7.0
2,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,1.0
3,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,0.5
5,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,22.0
6,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,11.0
7,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,7.0
8,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,3.5
10,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,2.0
9,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,4.0
11,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,0.5
12,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,1.0
13,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,1.0
14,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,0.5
15,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,1.0
16,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,0.5
17,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,1.0
18,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,0.5
20,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,4.5
19,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,9.0

In [22]:
# Check when the duplicate rainfall pattern occurs

duplicate_pattern_check = duplicate_rainfall_audit.copy()

duplicate_pattern_check["Year"] = (
    duplicate_pattern_check["Data Acquisition Time"].dt.year
)

duplicate_pattern_check["Month"] = (
    duplicate_pattern_check["Data Acquisition Time"].dt.to_period("M")
)

print("DUPLICATE RAINFALL TIME DISTRIBUTION")
print("=" * 60)

print("\nDuplicates by year:")
print(
    duplicate_pattern_check["Year"]
    .value_counts()
    .sort_index()
)

print("\nDuplicates by month:")
print(
    duplicate_pattern_check["Month"]
    .value_counts()
    .sort_index()
)

print("\nFirst duplicate timestamp:")
print(
    duplicate_pattern_check["Data Acquisition Time"].min()
)

print("\nLast duplicate timestamp:")
print(
    duplicate_pattern_check["Data Acquisition Time"].max()
)

DUPLICATE RAINFALL TIME DISTRIBUTION
============================================================

Duplicates by year:
Year
2022     84
2023    188
2024     34
Name: count, dtype: int64

Duplicates by month:
Month
2022-03    28
2022-04    22
2022-09    12
2022-10    18
2022-12     4
2023-01     2
2023-03    64
2023-04    76
2023-05    24
2023-06    14
2023-10     4
2023-12     4
2024-02    10
2024-03     4
2024-05     2
2024-06    18
Freq: M, Name: count, dtype: int64

First duplicate timestamp:
2022-03-24 14:00:00

Last duplicate timestamp:
2024-06-08 01:00:00

In [23]:
# Compare duplicate rainfall values with nearby observations

rainfall_sorted = rainfall_2021_2025.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

duplicate_times = (
    duplicate_rainfall_audit[
        "Data Acquisition Time"
    ]
    .drop_duplicates()
    .sort_values()
)

print("DUPLICATE RAINFALL + SURROUNDING VALUES")
print("=" * 60)

for timestamp in duplicate_times.head(10):

    nearby = rainfall_sorted[
        (rainfall_sorted["Data Acquisition Time"] >= timestamp - pd.Timedelta(hours=2)) &
        (rainfall_sorted["Data Acquisition Time"] <= timestamp + pd.Timedelta(hours=2))
    ][
        [
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ]

    print("\nDuplicate timestamp:", timestamp)
    display(nearby)

DUPLICATE RAINFALL + SURROUNDING VALUES
============================================================

Duplicate timestamp: 2022-03-24 14:00:00

  Data Acquisition Time  Telemetry Hourly Rainfall (mm)
0   2022-03-24 14:00:00                            14.0
1   2022-03-24 14:00:00                             7.0

Duplicate timestamp: 2022-03-25 04:00:00

  Data Acquisition Time  Telemetry Hourly Rainfall (mm)
2   2022-03-25 04:00:00                             1.0
3   2022-03-25 04:00:00                             0.5
4   2022-03-25 06:00:00                             3.0

Duplicate timestamp: 2022-03-25 07:00:00

  Data Acquisition Time  Telemetry Hourly Rainfall (mm)
4   2022-03-25 06:00:00                             3.0
5   2022-03-25 07:00:00                            22.0
6   2022-03-25 07:00:00                            11.0
7   2022-03-25 08:00:00                             7.0
8   2022-03-25 08:00:00                             3.5

Duplicate timestamp: 2022-03-25 08:00:00

  Data Acquisition Time  Telemetry Hourly Rainfall (mm)
4   2022-03-25 06:00:00                             3.0
5   2022-03-25 07:00:00                            22.0
6   2022-03-25 07:00:00                            11.0
7   2022-03-25 08:00:00                             7.0
8   2022-03-25 08:00:00                             3.5

Duplicate timestamp: 2022-03-25 22:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
9    2022-03-25 22:00:00                             4.0
10   2022-03-25 22:00:00                             2.0
11   2022-03-25 23:00:00                             1.0
12   2022-03-25 23:00:00                             0.5

Duplicate timestamp: 2022-03-25 23:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
9    2022-03-25 22:00:00                             4.0
10   2022-03-25 22:00:00                             2.0
11   2022-03-25 23:00:00                             1.0
12   2022-03-25 23:00:00                             0.5

Duplicate timestamp: 2022-03-26 10:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
13   2022-03-26 10:00:00                             1.0
14   2022-03-26 10:00:00                             0.5

Duplicate timestamp: 2022-03-26 13:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
15   2022-03-26 13:00:00                             1.0
16   2022-03-26 13:00:00                             0.5

Duplicate timestamp: 2022-03-26 16:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
17   2022-03-26 16:00:00                             1.0
18   2022-03-26 16:00:00                             0.5
19   2022-03-26 17:00:00                             9.0
20   2022-03-26 17:00:00                             4.5

Duplicate timestamp: 2022-03-26 17:00:00

   Data Acquisition Time  Telemetry Hourly Rainfall (mm)
17   2022-03-26 16:00:00                             1.0
18   2022-03-26 16:00:00                             0.5
19   2022-03-26 17:00:00                             9.0
20   2022-03-26 17:00:00                             4.5

In [24]:
# Check rainfall value patterns in duplicate pairs

pair_check = (
    duplicate_rainfall_audit
    .groupby("Data Acquisition Time")[
        "Telemetry Hourly Rainfall (mm)"
    ]
    .agg(["min", "max"])
    .copy()
)

pair_check["difference"] = (
    pair_check["max"] - pair_check["min"]
)

pair_check["ratio"] = (
    pair_check["max"] / pair_check["min"]
)

print("DUPLICATE RAINFALL VALUE PATTERN")
print("=" * 60)

print("\nMinimum duplicate value:")
print(pair_check["min"].min())

print("\nMaximum duplicate value:")
print(pair_check["max"].max())

print("\nUnique smaller values:")
print(
    sorted(pair_check["min"].unique())[:50]
)

print("\nUnique larger values:")
print(
    sorted(pair_check["max"].unique())[:50]
)

print("\nMost common differences:")
print(
    pair_check["difference"].value_counts().head(20)
)

DUPLICATE RAINFALL VALUE PATTERN
============================================================

Minimum duplicate value:
0.5

Maximum duplicate value:
70.0

Unique smaller values:
[np.float64(0.5), np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(3.5), np.float64(4.5), np.float64(6.5), np.float64(7.0), np.float64(11.0), np.float64(15.0), np.float64(70.0)]

Unique larger values:
[np.float64(0.5), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(9.0), np.float64(13.0), np.float64(14.0), np.float64(22.0), np.float64(30.0), np.float64(70.0)]

Most common differences:
difference
0.5     111
1.0      17
0.0       7
1.5       4
2.0       3
11.0      2
3.5       2
3.0       2
7.0       1
4.5       1
15.0      1
2.5       1
6.5       1
Name: count, dtype: int64

In [25]:
# COMPLETE DUPLICATE PAIR AUDIT

duplicate_pairs = (
    duplicate_rainfall_audit
    .groupby("Data Acquisition Time")[
        "Telemetry Hourly Rainfall (mm)"
    ]
    .agg(["min", "max", "count"])
    .reset_index()
)

duplicate_pairs["difference"] = (
    duplicate_pairs["max"] - duplicate_pairs["min"]
)

duplicate_pairs["ratio"] = (
    duplicate_pairs["max"] /
    duplicate_pairs["min"]
)

print("COMPLETE DUPLICATE PAIR AUDIT")
print("=" * 60)

print("Total duplicate timestamps:", len(duplicate_pairs))

display(
    duplicate_pairs.sort_values(
        "Data Acquisition Time"
    ).reset_index(drop=True)
)

COMPLETE DUPLICATE PAIR AUDIT
============================================================
Total duplicate timestamps: 153

    Data Acquisition Time   min   max  count  difference  ratio
0     2022-03-24 14:00:00   7.0  14.0      2         7.0    2.0
1     2022-03-25 04:00:00   0.5   1.0      2         0.5    2.0
2     2022-03-25 07:00:00  11.0  22.0      2        11.0    2.0
3     2022-03-25 08:00:00   3.5   7.0      2         3.5    2.0
4     2022-03-25 22:00:00   2.0   4.0      2         2.0    2.0
..                    ...   ...   ...    ...         ...    ...
148   2024-06-07 04:00:00   0.5   0.5      2         0.0    1.0
149   2024-06-07 14:00:00   0.5   0.5      2         0.0    1.0
150   2024-06-07 20:00:00   0.5   0.5      2         0.0    1.0
151   2024-06-07 23:00:00   0.5   0.5      2         0.0    1.0
152   2024-06-08 01:00:00   1.0   1.0      2         0.0    1.0

[153 rows x 6 columns]

In [26]:
# STEP 25: DUPLICATE METADATA COMPARISON

duplicate_metadata = duplicate_rainfall_audit[
    duplicate_rainfall_audit["Data Acquisition Time"].isin(
        duplicate_pairs["Data Acquisition Time"]
    )
].copy()

metadata_cols = [
    "Station",
    "Agency",
    "State",
    "District",
    "Latitude",
    "Longitude",
    "Data Acquisition Time",
    "Telemetry Hourly Rainfall (mm)"
]

print("DUPLICATE METADATA COMPARISON")
print("=" * 60)

display(
    duplicate_metadata[metadata_cols]
    .sort_values("Data Acquisition Time")
    .head(50)
)

DUPLICATE METADATA COMPARISON
============================================================

,Station,Agency,State,District,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
0,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-24 14:00:00,14.0
1,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-24 14:00:00,7.0
2,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 04:00:00,1.0
3,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 04:00:00,0.5
5,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 07:00:00,22.0
6,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 07:00:00,11.0
7,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 08:00:00,7.0
8,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 08:00:00,3.5
9,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 22:00:00,4.0
10,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 22:00:00,2.0
11,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 23:00:00,0.5
12,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-25 23:00:00,1.0
13,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 10:00:00,1.0
14,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 10:00:00,0.5
15,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 13:00:00,1.0
16,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 13:00:00,0.5
17,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 16:00:00,1.0
18,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 16:00:00,0.5
19,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 17:00:00,9.0
20,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-26 17:00:00,4.5
22,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 03:00:00,0.5
23,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 03:00:00,1.0
24,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 10:00:00,0.5
25,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-27 10:00:00,1.0
27,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-28 11:00:00,1.0
28,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-28 11:00:00,0.5
31,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-31 01:00:00,0.5
32,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-03-31 01:00:00,1.0
33,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-01 01:00:00,1.0
34,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-01 01:00:00,0.5
35,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-02 04:00:00,1.0
36,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-02 04:00:00,0.5
38,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-04 02:00:00,1.0
39,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-04 02:00:00,0.5
40,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-04 10:00:00,1.0
41,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-04 10:00:00,0.5
43,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-05 06:00:00,1.0
44,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-05 06:00:00,0.5
45,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-05 13:00:00,1.0
46,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-05 13:00:00,0.5
47,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 02:00:00,1.0
48,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 02:00:00,0.5
49,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 09:00:00,0.5
50,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 09:00:00,1.0
51,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 20:00:00,1.0
52,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-06 20:00:00,0.5
53,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-07 08:00:00,0.5
54,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-07 08:00:00,1.0
55,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-07 14:00:00,0.5
56,NH15 Crossing Fakirpara Tangni,Assam,Assam,DARRANG,26.508333,92.116389,2022-04-07 14:00:00,1.0

In [6]:
import pandas as pd
import os

raw_path = os.path.join(os.getcwd(), "data", "raw")

rainfall_2021_2025 = pd.read_csv(
    os.path.join(raw_path, "assam_rainfall_2021_2025.csv")
)

rainfall_2026_2030 = pd.read_csv(
    os.path.join(raw_path, "assam_rainfall_2026_2030.csv")
)

print("RAINFALL FILE INSPECTION")
print("=" * 70)

print("\n2021-2025 FILE")
print("Shape:", rainfall_2021_2025.shape)
print("Columns:")
print(rainfall_2021_2025.columns.tolist())

print("\n2026-2030 FILE")
print("Shape:", rainfall_2026_2030.shape)
print("Columns:")
print(rainfall_2026_2030.columns.tolist())

RAINFALL FILE INSPECTION
======================================================================

2021-2025 FILE
Shape: (74560, 20)
Columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)']

2026-2030 FILE
Shape: (1336, 20)
Columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)']

In [7]:
# STEP 26B: RECONSTRUCT RAINFALL DATASET

import pandas as pd
import os

raw_path = os.path.join(os.getcwd(), "data", "raw")

# Load both rainfall files
rainfall_2021_2025 = pd.read_csv(
    os.path.join(raw_path, "assam_rainfall_2021_2025.csv")
)

rainfall_2026_2030 = pd.read_csv(
    os.path.join(raw_path, "assam_rainfall_2026_2030.csv")
)

# Combine both files
rainfall_all = pd.concat(
    [rainfall_2021_2025, rainfall_2026_2030],
    ignore_index=True
)

# Convert timestamp
rainfall_all["Data Acquisition Time"] = pd.to_datetime(
    rainfall_all["Data Acquisition Time"],
    errors="coerce"
)

print("RAINFALL DATASET RECONSTRUCTED")
print("=" * 70)

print("Total rows:", len(rainfall_all))
print("Total columns:", rainfall_all.shape[1])

print(
    "Date range:",
    rainfall_all["Data Acquisition Time"].min(),
    "to",
    rainfall_all["Data Acquisition Time"].max()
)

print(
    "Missing timestamps:",
    rainfall_all["Data Acquisition Time"].isna().sum()
)

RAINFALL DATASET RECONSTRUCTED
======================================================================
Total rows: 75896
Total columns: 20
Date range: 2021-06-25 14:15:00 to 2026-06-03 23:00:00
Missing timestamps: 0

C:\Users\singh\AppData\Local\Temp\ipykernel_10824\1318884925.py:24: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  rainfall_all["Data Acquisition Time"] = pd.to_datetime(

In [8]:
# STEP 26C: VERIFY DATE PARSING

print("DATE PARSING VERIFICATION")
print("=" * 70)

print("\nFirst 20 timestamps:")
display(
    rainfall_all[["Data Acquisition Time"]]
    .head(20)
)

print("\nLast 20 timestamps:")
display(
    rainfall_all[["Data Acquisition Time"]]
    .tail(20)
)

print("\nData type:")
print(rainfall_all["Data Acquisition Time"].dtype)

print("\nInvalid / missing timestamps:")
print(rainfall_all["Data Acquisition Time"].isna().sum())

DATE PARSING VERIFICATION
======================================================================

First 20 timestamps:

   Data Acquisition Time
0    2022-07-17 16:00:00
1    2022-07-20 02:00:00
2    2022-07-20 12:00:00
3    2022-07-20 13:00:00
4    2022-07-21 23:00:00
5    2022-07-22 05:00:00
6    2022-07-23 17:00:00
7    2022-07-23 18:00:00
8    2022-07-24 08:00:00
9    2022-07-24 13:00:00
10   2022-07-24 16:00:00
11   2022-07-25 12:00:00
12   2022-07-25 13:00:00
13   2022-07-25 14:00:00
14   2022-07-25 15:00:00
15   2022-07-25 20:00:00
16   2022-07-26 05:00:00
17   2022-07-26 06:00:00
18   2022-07-26 15:00:00
19   2022-07-28 16:00:00

Last 20 timestamps:

      Data Acquisition Time
75876   2026-05-23 06:00:00
75877   2026-05-23 08:00:00
75878   2026-05-23 09:00:00
75879   2026-05-23 10:00:00
75880   2026-05-23 11:00:00
75881   2026-05-30 18:00:00
75882   2026-05-31 17:00:00
75883   2026-06-02 02:00:00
75884   2026-06-02 03:00:00
75885   2026-06-02 04:00:00
75886   2026-06-02 05:00:00
75887   2026-06-02 06:00:00
75888   2026-06-02 07:00:00
75889   2026-06-02 08:00:00
75890   2026-06-02 09:00:00
75891   2026-06-02 10:00:00
75892   2026-06-02 11:00:00
75893   2026-06-02 17:00:00
75894   2026-06-03 02:00:00
75895   2026-06-03 18:00:00

Data type:
datetime64[us]

Invalid / missing timestamps:
0

In [9]:
# STEP 26D: FILTER TARGET RAINFALL STATION

target_station = "NH15 Crossing Fakirpara Tangni"

rainfall_fakirpara = rainfall_all[
    rainfall_all["Station"] == target_station
].copy()

print("TARGET RAINFALL DATASET")
print("=" * 70)

print("Station:", target_station)
print("Rows:", len(rainfall_fakirpara))
print("Columns:", rainfall_fakirpara.shape[1])

print(
    "Date range:",
    rainfall_fakirpara["Data Acquisition Time"].min(),
    "to",
    rainfall_fakirpara["Data Acquisition Time"].max()
)

print(
    "Missing timestamps:",
    rainfall_fakirpara["Data Acquisition Time"].isna().sum()
)

print(
    "Duplicate timestamps:",
    rainfall_fakirpara["Data Acquisition Time"].duplicated().sum()
)

TARGET RAINFALL DATASET
======================================================================
Station: NH15 Crossing Fakirpara Tangni
Rows: 1621
Columns: 20
Date range: 2022-03-24 14:00:00 to 2026-05-27 06:00:00
Missing timestamps: 0
Duplicate timestamps: 153

In [10]:
# STEP 26E: RECONSTRUCT DUPLICATE RAINFALL PAIRS

rainfall_col = "Telemetry Hourly Rainfall (mm)"
time_col = "Data Acquisition Time"

duplicate_times = (
    rainfall_fakirpara[
        rainfall_fakirpara[time_col].duplicated(keep=False)
    ][time_col]
    .drop_duplicates()
    .sort_values()
)

duplicate_rainfall_audit = (
    rainfall_fakirpara[
        rainfall_fakirpara[time_col].isin(duplicate_times)
    ][
        [
            time_col,
            rainfall_col
        ]
    ]
    .sort_values(time_col)
    .copy()
)

print("DUPLICATE RAINFALL AUDIT")
print("=" * 70)

print("Duplicate timestamps:", duplicate_times.nunique())
print("Duplicate rows:", len(duplicate_rainfall_audit))

display(
    duplicate_rainfall_audit.head(30)
)

DUPLICATE RAINFALL AUDIT
======================================================================
Duplicate timestamps: 153
Duplicate rows: 306

      Data Acquisition Time  Telemetry Hourly Rainfall (mm)
42215   2022-03-24 14:00:00                            14.0
42216   2022-03-24 14:00:00                             7.0
42217   2022-03-25 04:00:00                             1.0
42218   2022-03-25 04:00:00                             0.5
42220   2022-03-25 07:00:00                            22.0
42221   2022-03-25 07:00:00                            11.0
42222   2022-03-25 08:00:00                             7.0
42223   2022-03-25 08:00:00                             3.5
42225   2022-03-25 22:00:00                             2.0
42224   2022-03-25 22:00:00                             4.0
42226   2022-03-25 23:00:00                             1.0
42227   2022-03-25 23:00:00                             0.5
42228   2022-03-26 10:00:00                             1.0
42229   2022-03-26 10:00:00                             0.5
42230   2022-03-26 13:00:00                             1.0
42231   2022-03-26 13:00:00                             0.5
42232   2022-03-26 16:00:00                             1.0
42233   2022-03-26 16:00:00                             0.5
42235   2022-03-26 17:00:00                             4.5
42234   2022-03-26 17:00:00                             9.0
42237   2022-03-27 03:00:00                             1.0
42238   2022-03-27 03:00:00                             0.5
42239   2022-03-27 10:00:00                             1.0
42240   2022-03-27 10:00:00                             0.5
42242   2022-03-28 11:00:00                             1.0
42243   2022-03-28 11:00:00                             0.5
42247   2022-03-31 01:00:00                             1.0
42246   2022-03-31 01:00:00                             0.5
42249   2022-04-01 01:00:00                             0.5
42248   2022-04-01 01:00:00                             1.0

In [11]:
# STEP 26F: COMPLETE DUPLICATE PAIR VERIFICATION

pair_check = (
    duplicate_rainfall_audit
    .groupby(time_col)[rainfall_col]
    .agg(["min", "max", "count"])
    .reset_index()
)

pair_check["difference"] = (
    pair_check["max"] - pair_check["min"]
)

pair_check["ratio"] = (
    pair_check["max"] / pair_check["min"]
)

print("DUPLICATE PAIR VERIFICATION")
print("=" * 70)

print("Total duplicate timestamps:", len(pair_check))
print("Pairs with exactly 2 records:",
      (pair_check["count"] == 2).sum())

print(
    "Exact duplicate-value pairs:",
    (pair_check["difference"] == 0).sum()
)

print(
    "Pairs with ratio exactly 2:",
    (pair_check["ratio"] == 2).sum()
)

print(
    "Pairs with ratio NOT equal to 2:",
    (pair_check["ratio"] != 2).sum()
)

print("\nNon-2× pairs:")
display(
    pair_check[
        pair_check["ratio"] != 2
    ]
)

DUPLICATE PAIR VERIFICATION
======================================================================
Total duplicate timestamps: 153
Pairs with exactly 2 records: 153
Exact duplicate-value pairs: 7
Pairs with ratio exactly 2: 146
Pairs with ratio NOT equal to 2: 7

Non-2× pairs:

    Data Acquisition Time   min   max  count  difference  ratio
146   2024-06-01 16:00:00  70.0  70.0      2         0.0    1.0
147   2024-06-06 10:00:00   0.5   0.5      2         0.0    1.0
148   2024-06-07 04:00:00   0.5   0.5      2         0.0    1.0
149   2024-06-07 14:00:00   0.5   0.5      2         0.0    1.0
150   2024-06-07 20:00:00   0.5   0.5      2         0.0    1.0
151   2024-06-07 23:00:00   0.5   0.5      2         0.0    1.0
152   2024-06-08 01:00:00   1.0   1.0      2         0.0    1.0

In [12]:
# STEP 26G: RAW RECORD-LEVEL DUPLICATE COMPARISON

raw_duplicate_records = rainfall_2021_2025[
    rainfall_2021_2025["Station"] == "NH15 Crossing Fakirpara Tangni"
].copy()

raw_duplicate_records["Data Acquisition Time"] = pd.to_datetime(
    raw_duplicate_records["Data Acquisition Time"],
    errors="coerce"
)

duplicate_times = (
    raw_duplicate_records[
        raw_duplicate_records["Data Acquisition Time"].duplicated(keep=False)
    ]["Data Acquisition Time"]
    .drop_duplicates()
)

raw_duplicate_records = raw_duplicate_records[
    raw_duplicate_records["Data Acquisition Time"].isin(duplicate_times)
].copy()

print("RAW RECORD-LEVEL DUPLICATE COMPARISON")
print("=" * 70)

display(
    raw_duplicate_records[
        [
            "SlNo",
            "Station",
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ]
    .sort_values(["Data Acquisition Time", "SlNo"])
    .head(50)
)

RAW RECORD-LEVEL DUPLICATE COMPARISON
======================================================================

C:\Users\singh\AppData\Local\Temp\ipykernel_10824\1371290846.py:7: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  raw_duplicate_records["Data Acquisition Time"] = pd.to_datetime(

,SlNo,Station,Data Acquisition Time,Telemetry Hourly Rainfall (mm)
42215,42216,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,14.0
42216,42217,NH15 Crossing Fakirpara Tangni,2022-03-24 14:00:00,7.0
42217,42218,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,1.0
42218,42219,NH15 Crossing Fakirpara Tangni,2022-03-25 04:00:00,0.5
42220,42221,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,22.0
42221,42222,NH15 Crossing Fakirpara Tangni,2022-03-25 07:00:00,11.0
42222,42223,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,7.0
42223,42224,NH15 Crossing Fakirpara Tangni,2022-03-25 08:00:00,3.5
42224,42225,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,4.0
42225,42226,NH15 Crossing Fakirpara Tangni,2022-03-25 22:00:00,2.0
42226,42227,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,1.0
42227,42228,NH15 Crossing Fakirpara Tangni,2022-03-25 23:00:00,0.5
42228,42229,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,1.0
42229,42230,NH15 Crossing Fakirpara Tangni,2022-03-26 10:00:00,0.5
42230,42231,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,1.0
42231,42232,NH15 Crossing Fakirpara Tangni,2022-03-26 13:00:00,0.5
42232,42233,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,1.0
42233,42234,NH15 Crossing Fakirpara Tangni,2022-03-26 16:00:00,0.5
42234,42235,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,9.0
42235,42236,NH15 Crossing Fakirpara Tangni,2022-03-26 17:00:00,4.5
42237,42238,NH15 Crossing Fakirpara Tangni,2022-03-27 03:00:00,1.0
42238,42239,NH15 Crossing Fakirpara Tangni,2022-03-27 03:00:00,0.5
42239,42240,NH15 Crossing Fakirpara Tangni,2022-03-27 10:00:00,1.0
42240,42241,NH15 Crossing Fakirpara Tangni,2022-03-27 10:00:00,0.5
42242,42243,NH15 Crossing Fakirpara Tangni,2022-03-28 11:00:00,1.0
42243,42244,NH15 Crossing Fakirpara Tangni,2022-03-28 11:00:00,0.5
42246,42247,NH15 Crossing Fakirpara Tangni,2022-03-31 01:00:00,0.5
42247,42248,NH15 Crossing Fakirpara Tangni,2022-03-31 01:00:00,1.0
42248,42249,NH15 Crossing Fakirpara Tangni,2022-04-01 01:00:00,1.0
42249,42250,NH15 Crossing Fakirpara Tangni,2022-04-01 01:00:00,0.5
42250,42251,NH15 Crossing Fakirpara Tangni,2022-04-02 04:00:00,1.0
42251,42252,NH15 Crossing Fakirpara Tangni,2022-04-02 04:00:00,0.5
42253,42254,NH15 Crossing Fakirpara Tangni,2022-04-04 02:00:00,1.0
42254,42255,NH15 Crossing Fakirpara Tangni,2022-04-04 02:00:00,0.5
42255,42256,NH15 Crossing Fakirpara Tangni,2022-04-04 10:00:00,1.0
42256,42257,NH15 Crossing Fakirpara Tangni,2022-04-04 10:00:00,0.5
42258,42259,NH15 Crossing Fakirpara Tangni,2022-04-05 06:00:00,1.0
42259,42260,NH15 Crossing Fakirpara Tangni,2022-04-05 06:00:00,0.5
42260,42261,NH15 Crossing Fakirpara Tangni,2022-04-05 13:00:00,1.0
42261,42262,NH15 Crossing Fakirpara Tangni,2022-04-05 13:00:00,0.5
42262,42263,NH15 Crossing Fakirpara Tangni,2022-04-06 02:00:00,1.0
42263,42264,NH15 Crossing Fakirpara Tangni,2022-04-06 02:00:00,0.5
42264,42265,NH15 Crossing Fakirpara Tangni,2022-04-06 09:00:00,1.0
42265,42266,NH15 Crossing Fakirpara Tangni,2022-04-06 09:00:00,0.5
42266,42267,NH15 Crossing Fakirpara Tangni,2022-04-06 20:00:00,1.0
42267,42268,NH15 Crossing Fakirpara Tangni,2022-04-06 20:00:00,0.5
42268,42269,NH15 Crossing Fakirpara Tangni,2022-04-07 08:00:00,0.5
42269,42270,NH15 Crossing Fakirpara Tangni,2022-04-07 08:00:00,1.0
42270,42271,NH15 Crossing Fakirpara Tangni,2022-04-07 14:00:00,0.5
42271,42272,NH15 Crossing Fakirpara Tangni,2022-04-07 14:00:00,1.0

In [13]:
# STEP 26H: COMPLETE ROW COMPARISON
# Check what actually differs between duplicate records

compare_cols = [
    col for col in raw_duplicate_records.columns
    if col not in ["SlNo", rainfall_col]
]

difference_summary = []

for timestamp, group in raw_duplicate_records.groupby(time_col):

    if len(group) == 2:

        row1 = group.iloc[0]
        row2 = group.iloc[1]

        different_cols = []

        for col in compare_cols:
            if row1[col] != row2[col]:
                different_cols.append(col)

        difference_summary.append({
            "Data Acquisition Time": timestamp,
            "Different Columns": different_cols,
            "Number of Differences": len(different_cols)
        })

difference_df = pd.DataFrame(difference_summary)

print("COMPLETE DUPLICATE ROW DIFFERENCE ANALYSIS")
print("=" * 70)

print(
    "Duplicate timestamp pairs:",
    len(difference_df)
)

print(
    "Pairs where metadata is completely identical:",
    (difference_df["Number of Differences"] == 0).sum()
)

print(
    "Pairs having other differences:",
    (difference_df["Number of Differences"] > 0).sum()
)

print("\nDifference summary:")
display(difference_df.head(20))

COMPLETE DUPLICATE ROW DIFFERENCE ANALYSIS
======================================================================
Duplicate timestamp pairs: 153
Pairs where metadata is completely identical: 153
Pairs having other differences: 0

Difference summary:

   Data Acquisition Time Different Columns  Number of Differences
0    2022-03-24 14:00:00                []                      0
1    2022-03-25 04:00:00                []                      0
2    2022-03-25 07:00:00                []                      0
3    2022-03-25 08:00:00                []                      0
4    2022-03-25 22:00:00                []                      0
5    2022-03-25 23:00:00                []                      0
6    2022-03-26 10:00:00                []                      0
7    2022-03-26 13:00:00                []                      0
8    2022-03-26 16:00:00                []                      0
9    2022-03-26 17:00:00                []                      0
10   2022-03-27 03:00:00                []                      0
11   2022-03-27 10:00:00                []                      0
12   2022-03-28 11:00:00                []                      0
13   2022-03-31 01:00:00                []                      0
14   2022-04-01 01:00:00                []                      0
15   2022-04-02 04:00:00                []                      0
16   2022-04-04 02:00:00                []                      0
17   2022-04-04 10:00:00                []                      0
18   2022-04-05 06:00:00                []                      0
19   2022-04-05 13:00:00                []                      0

In [14]:
# STEP 26I: DUPLICATE TEMPORAL PATTERN

duplicate_years = (
    duplicate_times
    .dt.year
    .value_counts()
    .sort_index()
)

duplicate_months = (
    duplicate_times
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

print("DUPLICATE TEMPORAL PATTERN")
print("=" * 70)

print(
    "First duplicate timestamp:",
    duplicate_times.min()
)

print(
    "Last duplicate timestamp:",
    duplicate_times.max()
)

print("\nDuplicates by year:")
print(duplicate_years)

print("\nDuplicates by month:")
print(duplicate_months)

DUPLICATE TEMPORAL PATTERN
======================================================================
First duplicate timestamp: 2022-03-24 14:00:00
Last duplicate timestamp: 2024-06-08 01:00:00

Duplicates by year:
Data Acquisition Time
2022    42
2023    94
2024    17
Name: count, dtype: int64

Duplicates by month:
Data Acquisition Time
2022-03    14
2022-04    11
2022-09     6
2022-10     9
2022-12     2
2023-01     1
2023-03    32
2023-04    38
2023-05    12
2023-06     7
2023-10     2
2023-12     2
2024-02     5
2024-03     2
2024-05     1
2024-06     9
Freq: M, Name: count, dtype: int64

In [15]:
# STEP 26J: INSPECT RECORDS AROUND DUPLICATE BLOCK

target_time = pd.Timestamp("2022-03-24 14:00:00")

station_data = (
    rainfall_2021_2025[
        rainfall_2021_2025["Station"] == "NH15 Crossing Fakirpara Tangni"
    ]
    .copy()
)

station_data["Data Acquisition Time"] = pd.to_datetime(
    station_data["Data Acquisition Time"],
    errors="coerce"
)

# Locate the duplicate timestamp
duplicate_position = station_data.index[
    station_data["Data Acquisition Time"] == target_time
].tolist()

print("TARGET DUPLICATE TIMESTAMP")
print("=" * 70)
print(target_time)

print("\nMatching rows:")
display(
    station_data.loc[
        duplicate_position,
        [
            "SlNo",
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ]
)

# Show surrounding raw records
first_position = duplicate_position[0]

print("\nRows around the duplicate:")
display(
    station_data.loc[
        max(0, first_position - 5):
        first_position + 7,
        [
            "SlNo",
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ]
)

TARGET DUPLICATE TIMESTAMP
======================================================================
2022-03-24 14:00:00

Matching rows:

C:\Users\singh\AppData\Local\Temp\ipykernel_10824\2885389197.py:12: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  station_data["Data Acquisition Time"] = pd.to_datetime(

        SlNo Data Acquisition Time  Telemetry Hourly Rainfall (mm)
42215  42216   2022-03-24 14:00:00                            14.0
42216  42217   2022-03-24 14:00:00                             7.0

Rows around the duplicate:

        SlNo Data Acquisition Time  Telemetry Hourly Rainfall (mm)
42215  42216   2022-03-24 14:00:00                            14.0
42216  42217   2022-03-24 14:00:00                             7.0
42217  42218   2022-03-25 04:00:00                             1.0
42218  42219   2022-03-25 04:00:00                             0.5
42219  42220   2022-03-25 06:00:00                             3.0
42220  42221   2022-03-25 07:00:00                            22.0
42221  42222   2022-03-25 07:00:00                            11.0
42222  42223   2022-03-25 08:00:00                             7.0

In [16]:
# STEP 26K: CHECK CONTIGUOUS SLNO BLOCKS

dup_slno = (
    raw_duplicate_records["SlNo"]
    .sort_values()
    .astype(int)
    .tolist()
)

blocks = []

start = dup_slno[0]
previous = dup_slno[0]

for current in dup_slno[1:]:
    if current != previous + 1:
        blocks.append((start, previous))
        start = current
    previous = current

blocks.append((start, previous))

print("CONTIGUOUS DUPLICATE SLNO BLOCKS")
print("=" * 70)

print("Total duplicate rows:", len(dup_slno))
print("Number of contiguous blocks:", len(blocks))

for i, (start, end) in enumerate(blocks, start=1):
    print(
        f"Block {i}: SlNo {start} → {end} "
        f"({end - start + 1} rows)"
    )

CONTIGUOUS DUPLICATE SLNO BLOCKS
======================================================================
Total duplicate rows: 306
Number of contiguous blocks: 61
Block 1: SlNo 42216 → 42219 (4 rows)
Block 2: SlNo 42221 → 42236 (16 rows)
Block 3: SlNo 42238 → 42241 (4 rows)
Block 4: SlNo 42243 → 42244 (2 rows)
Block 5: SlNo 42247 → 42252 (6 rows)
Block 6: SlNo 42254 → 42257 (4 rows)
Block 7: SlNo 42259 → 42272 (14 rows)
Block 8: SlNo 42407 → 42414 (8 rows)
Block 9: SlNo 42417 → 42418 (2 rows)
Block 10: SlNo 42423 → 42424 (2 rows)
Block 11: SlNo 42427 → 42430 (4 rows)
Block 12: SlNo 42432 → 42435 (4 rows)
Block 13: SlNo 42437 → 42444 (8 rows)
Block 14: SlNo 42447 → 42448 (2 rows)
Block 15: SlNo 42509 → 42514 (6 rows)
Block 16: SlNo 42516 → 42517 (2 rows)
Block 17: SlNo 42519 → 42524 (6 rows)
Block 18: SlNo 42527 → 42530 (4 rows)
Block 19: SlNo 42532 → 42535 (4 rows)
Block 20: SlNo 42537 → 42540 (4 rows)
Block 21: SlNo 42542 → 42543 (2 rows)
Block 22: SlNo 42545 → 42548 (4 rows)
Block 23: SlNo 42557 → 42558 (2 rows)
Block 24: SlNo 42561 → 42562 (2 rows)
Block 25: SlNo 42566 → 42567 (2 rows)
Block 26: SlNo 42570 → 42571 (2 rows)
Block 27: SlNo 42573 → 42576 (4 rows)
Block 28: SlNo 42579 → 42594 (16 rows)
Block 29: SlNo 42596 → 42601 (6 rows)
Block 30: SlNo 42604 → 42619 (16 rows)
Block 31: SlNo 42621 → 42632 (12 rows)
Block 32: SlNo 42634 → 42639 (6 rows)
Block 33: SlNo 42641 → 42648 (8 rows)
Block 34: SlNo 42650 → 42651 (2 rows)
Block 35: SlNo 42657 → 42658 (2 rows)
Block 36: SlNo 42660 → 42663 (4 rows)
Block 37: SlNo 42666 → 42685 (20 rows)
Block 38: SlNo 42687 → 42690 (4 rows)
Block 39: SlNo 42698 → 42701 (4 rows)
Block 40: SlNo 42705 → 42706 (2 rows)
Block 41: SlNo 42709 → 42710 (2 rows)
Block 42: SlNo 42713 → 42714 (2 rows)
Block 43: SlNo 42716 → 42719 (4 rows)
Block 44: SlNo 42722 → 42723 (2 rows)
Block 45: SlNo 42725 → 42726 (2 rows)
Block 46: SlNo 42728 → 42729 (2 rows)
Block 47: SlNo 42732 → 42735 (4 rows)
Block 48: SlNo 42739 → 42742 (4 rows)
Block 49: SlNo 42744 → 42747 (4 rows)
Block 50: SlNo 42754 → 42759 (6 rows)
Block 51: SlNo 42771 → 42772 (2 rows)
Block 52: SlNo 42775 → 42778 (4 rows)
Block 53: SlNo 42798 → 42805 (8 rows)
Block 54: SlNo 42807 → 42808 (2 rows)
Block 55: SlNo 42810 → 42817 (8 rows)
Block 56: SlNo 42821 → 42824 (4 rows)
Block 57: SlNo 42832 → 42833 (2 rows)
Block 58: SlNo 42840 → 42843 (4 rows)
Block 59: SlNo 42846 → 42847 (2 rows)
Block 60: SlNo 42849 → 42858 (10 rows)
Block 61: SlNo 42860 → 42861 (2 rows)

In [17]:
# STEP 26L: CHECK DUPLICATE PAIR ORDER / SLNO PATTERN

pair_order_check = []

for timestamp, group in raw_duplicate_records.groupby(time_col):

    group = group.sort_values("SlNo")

    if len(group) == 2:

        first = group.iloc[0]
        second = group.iloc[1]

        v1 = first[rainfall_col]
        v2 = second[rainfall_col]

        pair_order_check.append({
            "Data Acquisition Time": timestamp,
            "First_SlNo": first["SlNo"],
            "First_Rainfall": v1,
            "Second_SlNo": second["SlNo"],
            "Second_Rainfall": v2,
            "First_to_Second_Ratio": (
                v1 / v2 if v2 != 0 else None
            ),
            "First_Is_Double": (
                v1 == 2 * v2
            ),
            "Second_Is_Double": (
                v2 == 2 * v1
            ),
            "Values_Equal": (
                v1 == v2
            )
        })

pair_order_check = pd.DataFrame(pair_order_check)

print("DUPLICATE PAIR ORDER ANALYSIS")
print("=" * 70)

print(
    "First value is exactly 2× second:",
    pair_order_check["First_Is_Double"].sum()
)

print(
    "Second value is exactly 2× first:",
    pair_order_check["Second_Is_Double"].sum()
)

print(
    "Both values equal:",
    pair_order_check["Values_Equal"].sum()
)

print("\nFirst 30 pairs:")
display(pair_order_check.head(30))

DUPLICATE PAIR ORDER ANALYSIS
======================================================================
First value is exactly 2× second: 110
Second value is exactly 2× first: 36
Both values equal: 7

First 30 pairs:

,Data Acquisition Time,First_SlNo,First_Rainfall,Second_SlNo,Second_Rainfall,First_to_Second_Ratio,First_Is_Double,Second_Is_Double,Values_Equal
0,2022-03-24 14:00:00,42216,14.0,42217,7.0,2.0,True,False,False
1,2022-03-25 04:00:00,42218,1.0,42219,0.5,2.0,True,False,False
2,2022-03-25 07:00:00,42221,22.0,42222,11.0,2.0,True,False,False
3,2022-03-25 08:00:00,42223,7.0,42224,3.5,2.0,True,False,False
4,2022-03-25 22:00:00,42225,4.0,42226,2.0,2.0,True,False,False
5,2022-03-25 23:00:00,42227,1.0,42228,0.5,2.0,True,False,False
6,2022-03-26 10:00:00,42229,1.0,42230,0.5,2.0,True,False,False
7,2022-03-26 13:00:00,42231,1.0,42232,0.5,2.0,True,False,False
8,2022-03-26 16:00:00,42233,1.0,42234,0.5,2.0,True,False,False
9,2022-03-26 17:00:00,42235,9.0,42236,4.5,2.0,True,False,False
10,2022-03-27 03:00:00,42238,1.0,42239,0.5,2.0,True,False,False
11,2022-03-27 10:00:00,42240,1.0,42241,0.5,2.0,True,False,False
12,2022-03-28 11:00:00,42243,1.0,42244,0.5,2.0,True,False,False
13,2022-03-31 01:00:00,42247,0.5,42248,1.0,0.5,False,True,False
14,2022-04-01 01:00:00,42249,1.0,42250,0.5,2.0,True,False,False
15,2022-04-02 04:00:00,42251,1.0,42252,0.5,2.0,True,False,False
16,2022-04-04 02:00:00,42254,1.0,42255,0.5,2.0,True,False,False
17,2022-04-04 10:00:00,42256,1.0,42257,0.5,2.0,True,False,False
18,2022-04-05 06:00:00,42259,1.0,42260,0.5,2.0,True,False,False
19,2022-04-05 13:00:00,42261,1.0,42262,0.5,2.0,True,False,False
20,2022-04-06 02:00:00,42263,1.0,42264,0.5,2.0,True,False,False
21,2022-04-06 09:00:00,42265,1.0,42266,0.5,2.0,True,False,False
22,2022-04-06 20:00:00,42267,1.0,42268,0.5,2.0,True,False,False
23,2022-04-07 08:00:00,42269,0.5,42270,1.0,0.5,False,True,False
24,2022-04-07 14:00:00,42271,0.5,42272,1.0,0.5,False,True,False
25,2022-09-12 09:00:00,42407,2.0,42408,1.0,2.0,True,False,False
26,2022-09-12 10:00:00,42409,1.0,42410,0.5,2.0,True,False,False
27,2022-09-12 11:00:00,42411,1.0,42412,0.5,2.0,True,False,False
28,2022-09-12 12:00:00,42413,1.0,42414,0.5,2.0,True,False,False
29,2022-09-13 06:00:00,42417,1.0,42418,0.5,2.0,True,False,False

In [18]:
# STEP 27: CREATE DUPLICATE RESOLUTION TABLE

duplicate_resolution = (
    rainfall_fakirpara[
        rainfall_fakirpara[time_col].isin(duplicate_times)
    ]
    .groupby(time_col)[rainfall_col]
    .agg(["min", "max", "count"])
    .reset_index()
)

duplicate_resolution["difference"] = (
    duplicate_resolution["max"] -
    duplicate_resolution["min"]
)

duplicate_resolution["ratio"] = (
    duplicate_resolution["max"] /
    duplicate_resolution["min"]
)

duplicate_resolution["resolution_status"] = "UNRESOLVED_DUPLICATE"

# Exact same-value duplicates can be safely represented by one value
duplicate_resolution.loc[
    duplicate_resolution["difference"] == 0,
    "resolution_status"
] = "EXACT_DUPLICATE"

print("STEP 27 — DUPLICATE RESOLUTION TABLE")
print("=" * 70)

print("Total duplicate timestamps:",
      len(duplicate_resolution))

print(
    "Exact duplicates:",
    (duplicate_resolution["resolution_status"] == "EXACT_DUPLICATE").sum()
)

print(
    "Unresolved conflicting duplicates:",
    (duplicate_resolution["resolution_status"] == "UNRESOLVED_DUPLICATE").sum()
)

display(
    duplicate_resolution.head(30)
)

STEP 27 — DUPLICATE RESOLUTION TABLE
======================================================================
Total duplicate timestamps: 153
Exact duplicates: 7
Unresolved conflicting duplicates: 146

,Data Acquisition Time,min,max,count,difference,ratio,resolution_status
0,2022-03-24 14:00:00,7.0,14.0,2,7.0,2.0,UNRESOLVED_DUPLICATE
1,2022-03-25 04:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
2,2022-03-25 07:00:00,11.0,22.0,2,11.0,2.0,UNRESOLVED_DUPLICATE
3,2022-03-25 08:00:00,3.5,7.0,2,3.5,2.0,UNRESOLVED_DUPLICATE
4,2022-03-25 22:00:00,2.0,4.0,2,2.0,2.0,UNRESOLVED_DUPLICATE
5,2022-03-25 23:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
6,2022-03-26 10:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
7,2022-03-26 13:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
8,2022-03-26 16:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
9,2022-03-26 17:00:00,4.5,9.0,2,4.5,2.0,UNRESOLVED_DUPLICATE
10,2022-03-27 03:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
11,2022-03-27 10:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
12,2022-03-28 11:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
13,2022-03-31 01:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
14,2022-04-01 01:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
15,2022-04-02 04:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
16,2022-04-04 02:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
17,2022-04-04 10:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
18,2022-04-05 06:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
19,2022-04-05 13:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
20,2022-04-06 02:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
21,2022-04-06 09:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
22,2022-04-06 20:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
23,2022-04-07 08:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
24,2022-04-07 14:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
25,2022-09-12 09:00:00,1.0,2.0,2,1.0,2.0,UNRESOLVED_DUPLICATE
26,2022-09-12 10:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
27,2022-09-12 11:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
28,2022-09-12 12:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE
29,2022-09-13 06:00:00,0.5,1.0,2,0.5,2.0,UNRESOLVED_DUPLICATE

In [20]:
# STEP 28: CREATE CLEAN RAINFALL WORKING DATASET
import numpy as np
rainfall_clean = rainfall_fakirpara.copy()

# Count observations at each timestamp
timestamp_counts = (
    rainfall_clean[time_col]
    .value_counts()
)

# Identify duplicate timestamps
duplicate_timestamp_set = set(
    timestamp_counts[timestamp_counts > 1].index
)

# Separate unique and duplicate records
unique_rows = rainfall_clean[
    ~rainfall_clean[time_col].isin(duplicate_timestamp_set)
].copy()

duplicate_rows = rainfall_clean[
    rainfall_clean[time_col].isin(duplicate_timestamp_set)
].copy()

# ---------------------------------------------------------
# Exact duplicate timestamps
# ---------------------------------------------------------

exact_duplicate_times = set(
    duplicate_resolution.loc[
        duplicate_resolution["resolution_status"] == "EXACT_DUPLICATE",
        time_col
    ]
)

exact_duplicate_rows = duplicate_rows[
    duplicate_rows[time_col].isin(exact_duplicate_times)
].copy()

# Keep one record for each exact duplicate timestamp
exact_duplicate_clean = (
    exact_duplicate_rows
    .sort_values(time_col)
    .drop_duplicates(
        subset=[time_col],
        keep="first"
    )
    .copy()
)

# ---------------------------------------------------------
# Conflicting duplicate timestamps
# ---------------------------------------------------------

conflicting_times = set(
    duplicate_resolution.loc[
        duplicate_resolution["resolution_status"] == "UNRESOLVED_DUPLICATE",
        time_col
    ]
)

conflicting_rows = duplicate_rows[
    duplicate_rows[time_col].isin(conflicting_times)
].copy()

# Create one representative row per conflicting timestamp
# but mark rainfall as NaN because true value is unknown

conflicting_clean = (
    conflicting_rows
    .sort_values(time_col)
    .drop_duplicates(
        subset=[time_col],
        keep="first"
    )
    .copy()
)

conflicting_clean[rainfall_col] = np.nan

# ---------------------------------------------------------
# Combine
# ---------------------------------------------------------

rainfall_clean = pd.concat(
    [
        unique_rows,
        exact_duplicate_clean,
        conflicting_clean
    ],
    ignore_index=True
)

rainfall_clean = (
    rainfall_clean
    .sort_values(time_col)
    .reset_index(drop=True)
)

print("STEP 28 — CLEAN RAINFALL WORKING DATASET")
print("=" * 70)

print("Original rows:", len(rainfall_fakirpara))
print("Clean rows:", len(rainfall_clean))

print(
    "Duplicate timestamps remaining:",
    rainfall_clean[time_col].duplicated().sum()
)

print(
    "Missing rainfall values:",
    rainfall_clean[rainfall_col].isna().sum()
)

print(
    "Exact duplicates safely retained:",
    len(exact_duplicate_clean)
)

print(
    "Conflicting duplicate timestamps flagged:",
    len(conflicting_clean)
)

STEP 28 — CLEAN RAINFALL WORKING DATASET
======================================================================
Original rows: 1621
Clean rows: 1468
Duplicate timestamps remaining: 0
Missing rainfall values: 146
Exact duplicates safely retained: 7
Conflicting duplicate timestamps flagged: 146

In [21]:
# STEP 29: RAINFALL TIME-GAP AND COVERAGE CHECK

rainfall_clean = rainfall_clean.sort_values(time_col).reset_index(drop=True)

# Time difference between consecutive observations
rainfall_clean["time_gap"] = (
    rainfall_clean[time_col].diff()
)

print("STEP 29 — RAINFALL TIME-GAP ANALYSIS")
print("=" * 70)

print(
    "Date range:",
    rainfall_clean[time_col].min(),
    "to",
    rainfall_clean[time_col].max()
)

print(
    "Total rows:",
    len(rainfall_clean)
)

print(
    "Missing rainfall:",
    rainfall_clean[rainfall_col].isna().sum()
)

print(
    "Unique timestamps:",
    rainfall_clean[time_col].nunique()
)

print("\nMost common time gaps:")

display(
    rainfall_clean["time_gap"]
    .value_counts()
    .head(15)
)

print("\nGaps greater than 1 hour:")

print(
    (rainfall_clean["time_gap"] > pd.Timedelta(hours=1)).sum()
)

print("\nLargest time gap:")

print(
    rainfall_clean["time_gap"].max()
)

STEP 29 — RAINFALL TIME-GAP ANALYSIS
======================================================================
Date range: 2022-03-24 14:00:00 to 2026-05-27 06:00:00
Total rows: 1468
Missing rainfall: 146
Unique timestamps: 1468

Most common time gaps:

time_gap
0 days 01:00:00    1097
0 days 02:00:00     107
0 days 03:00:00      41
0 days 04:00:00      17
0 days 06:00:00      14
0 days 07:00:00      14
0 days 05:00:00      11
0 days 13:00:00       9
0 days 10:00:00       8
0 days 08:00:00       8
0 days 12:00:00       7
0 days 14:00:00       5
0 days 11:00:00       5
0 days 15:00:00       5
0 days 20:00:00       5
Name: count, dtype: int64

Gaps greater than 1 hour:
367

Largest time gap:
393 days 18:00:00

In [22]:
# STEP 30: LOAD FINAL WATER LEVEL DATASET
# AND CHECK COMPATIBILITY WITH RAINFALL

water_level_path = "data/final/darrang_water_level_final.csv"

water_level_final = pd.read_csv(
    water_level_path
)

print("STEP 30 — WATER LEVEL DATASET CHECK")
print("=" * 70)

print("Rows:", len(water_level_final))
print("Columns:", len(water_level_final.columns))

print("\nColumns:")
print(water_level_final.columns.tolist())

print("\nFirst 5 rows:")
display(water_level_final.head())

print("\nLast 5 rows:")
display(water_level_final.tail())

STEP 30 — WATER LEVEL DATASET CHECK
======================================================================
Rows: 11124
Columns: 24

Columns:
['Data Acquisition Time', '_id', 'SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Is_DischargeDataAvailable', 'RL_of_zeroGauge', 'MeanSeaLevel', 'River Water Level Telemetry Hourly (meter)']

First 5 rows:

,Data Acquisition Time,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,...,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,River Water Level Telemetry Hourly (meter)
0,2022-01-01 20:00:00,16499,16499,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,1.275
1,2022-01-03 00:00:00,16534,16534,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.159
2,2022-01-03 01:00:00,16535,16535,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.158
3,2022-01-03 02:00:00,16536,16536,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.160
4,2022-01-03 03:00:00,16537,16537,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.161

Last 5 rows:

,Data Acquisition Time,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,...,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,River Water Level Telemetry Hourly (meter)
11119,2026-12-05 17:00:00,118,118,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,60.894
11120,2026-12-05 18:00:00,119,119,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,60.894
11121,2026-12-05 19:00:00,120,120,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,60.891
11122,2026-12-05 20:00:00,121,121,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,60.891
11123,2026-12-05 22:00:00,122,122,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,60.893

In [23]:
# STEP 31: FINAL WATER LEVEL VALIDATION BEFORE RAINFALL MERGE

water_time_col = "Data Acquisition Time"
water_level_col = "River Water Level Telemetry Hourly (meter)"

# Ensure datetime
water_level_final[water_time_col] = pd.to_datetime(
    water_level_final[water_time_col],
    errors="coerce"
)

print("STEP 31 — WATER LEVEL VALIDATION")
print("=" * 70)

print("Rows:", len(water_level_final))

print(
    "Missing timestamps:",
    water_level_final[water_time_col].isna().sum()
)

print(
    "Duplicate timestamps:",
    water_level_final[water_time_col].duplicated().sum()
)

print(
    "Missing water levels:",
    water_level_final[water_level_col].isna().sum()
)

print(
    "Date range:",
    water_level_final[water_time_col].min(),
    "to",
    water_level_final[water_time_col].max()
)

print(
    "Unique timestamps:",
    water_level_final[water_time_col].nunique()
)

print("\nWater-level statistics:")
display(
    water_level_final[water_level_col].describe()
)

STEP 31 — WATER LEVEL VALIDATION
======================================================================
Rows: 11124
Missing timestamps: 0
Duplicate timestamps: 0
Missing water levels: 45
Date range: 2022-01-01 20:00:00 to 2026-12-05 22:00:00
Unique timestamps: 11124

Water-level statistics:

count    11079.000000
mean        19.076142
std         24.607100
min          0.001000
25%          1.241000
50%          5.763000
75%         32.700000
max        641.231000
Name: River Water Level Telemetry Hourly (meter), dtype: float64

In [24]:
# STEP 32: RAINFALL-WATER LEVEL TIMESTAMP OVERLAP

rain_time_col = "Data Acquisition Time"

# Make sure rainfall timestamp is datetime
rainfall_clean[rain_time_col] = pd.to_datetime(
    rainfall_clean[rain_time_col],
    errors="coerce"
)

# Water level timestamps
water_times = set(
    water_level_final[water_time_col]
)

# Rainfall timestamps
rain_times = rainfall_clean[rain_time_col]

common_mask = rain_times.isin(water_times)

common_count = common_mask.sum()
rainfall_total = len(rainfall_clean)

print("STEP 32 — RAINFALL / WATER LEVEL OVERLAP")
print("=" * 70)

print("Rainfall rows:", rainfall_total)

print("Rainfall timestamps matching water level:",
      common_count)

print("Rainfall timestamps NOT matching water level:",
      rainfall_total - common_count)

print(
    "Exact timestamp coverage:",
    round(common_count / rainfall_total * 100, 2),
    "%"
)

STEP 32 — RAINFALL / WATER LEVEL OVERLAP
======================================================================
Rainfall rows: 1468
Rainfall timestamps matching water level: 436
Rainfall timestamps NOT matching water level: 1032
Exact timestamp coverage: 29.7 %

In [25]:
# STEP 33: RAINFALL TEMPORAL AVAILABILITY AROUND WATER LEVEL

rainfall_times = pd.DataFrame({
    "rainfall_time": rainfall_clean[rain_time_col]
}).sort_values("rainfall_time")

water_times_df = pd.DataFrame({
    "water_time": water_level_final[water_time_col]
}).sort_values("water_time")


# Find most recent rainfall observation at or before
# each water-level timestamp
nearest_previous = pd.merge_asof(
    water_times_df,
    rainfall_times,
    left_on="water_time",
    right_on="rainfall_time",
    direction="backward"
)


nearest_previous["hours_since_rainfall"] = (
    nearest_previous["water_time"]
    - nearest_previous["rainfall_time"]
).dt.total_seconds() / 3600


print("STEP 33 — RAINFALL AVAILABILITY BEFORE WATER LEVEL")
print("=" * 70)

print("Total water-level timestamps:",
      len(nearest_previous))

print(
    "Water-level timestamps with previous rainfall:",
    nearest_previous["rainfall_time"].notna().sum()
)

print(
    "Water-level timestamps with NO previous rainfall:",
    nearest_previous["rainfall_time"].isna().sum()
)

print("\nHours since previous rainfall observation:")

display(
    nearest_previous["hours_since_rainfall"].describe()
)

print("\nAvailability within windows:")

for hours in [1, 3, 6, 12, 24, 48, 72]:
    count = (
        nearest_previous["hours_since_rainfall"] <= hours
    ).sum()

    percentage = count / len(nearest_previous) * 100

    print(
        f"Within {hours:>2} hours : "
        f"{count:>5} "
        f"({percentage:.2f}%)"
    )

STEP 33 — RAINFALL AVAILABILITY BEFORE WATER LEVEL
======================================================================
Total water-level timestamps: 11124
Water-level timestamps with previous rainfall: 10637
Water-level timestamps with NO previous rainfall: 487

Hours since previous rainfall observation:

count    10637.000000
mean      1151.587548
std       1768.366556
min          0.000000
25%         89.000000
50%        422.000000
75%       1173.000000
max       9449.000000
Name: hours_since_rainfall, dtype: float64

Availability within windows:
Within  1 hours :   542 (4.87%)
Within  3 hours :   704 (6.33%)
Within  6 hours :   900 (8.09%)
Within 12 hours :  1187 (10.67%)
Within 24 hours :  1568 (14.10%)
Within 48 hours :  2049 (18.42%)
Within 72 hours :  2422 (21.77%)

In [26]:
# STEP 34: RAINFALL SOURCE / STATION AUDIT

print("STEP 34 — RAINFALL SOURCE AUDIT")
print("=" * 70)

print("\nStation counts:")
display(
    rainfall_all["Station"]
    .value_counts(dropna=False)
    .head(20)
)

print("\nAgency counts:")
display(
    rainfall_all["Agency"]
    .value_counts(dropna=False)
)

print("\nDistrict counts:")
display(
    rainfall_all["District"]
    .value_counts(dropna=False)
    .head(20)
)

print("\nTarget station:")
print("NH15 Crossing Fakirpara Tangni")

print("\nTarget station total records in reconstructed rainfall:")
print(
    (rainfall_all["Station"] == "NH15 Crossing Fakirpara Tangni").sum()
)

STEP 34 — RAINFALL SOURCE AUDIT
======================================================================

Station counts:

Station
NH37 Bridge Katakhal_1            6564
North Lakhimpur                   4093
Dholai Bridge Rukni_1             3920
NH15 Crossing Gainadi             3817
Silgat WR office                  2998
NH27 Crossing Amlighat Killing    2873
AWRMI Basistha Guwahati           2442
NH17 Crossing Boko                2234
Anipur WR Dept Quarter_1          2193
NH27 Crossing Rangia Boralia      1980
Badarpur WR EE Office             1944
Bongaigaon_1                      1918
Dhaligaon PHE                     1896
Kochugaon Child Dev Office        1807
Sorbhag WR Sub Division           1767
NH15 Crossing Fakirpara Tangni    1621
Dibrugarh WR Office               1563
Goalpara_1                        1506
Nagarbera Circle Office           1498
NH15 Crossing Doomdooma Dibru     1493
Name: count, dtype: int64

Agency counts:

Agency
Assam    75896
Name: count, dtype: int64

District counts:

District
Kamrup Metropolitan    12450
HAILAKANDI              8508
CACHAR                  5319
DHEMAJI                 5251
LAKHIMPUR               5177
NAGAON                  4478
BONGAIGAON              4472
BARPETA                 3564
GOALPARA                3541
MARIGAON                2873
DARRANG                 2728
DHUBRI                  2402
KARIMGANJ               2198
DIBRUGARH               1839
NALBARI                 1816
KOKRAJHAR               1807
JORHAT                  1690
TINSUKIA                1493
Biswanath               1399
SIVSAGAR                1308
Name: count, dtype: int64

Target station:
NH15 Crossing Fakirpara Tangni

Target station total records in reconstructed rainfall:
1621

In [27]:
# STEP 35: RAINFALL YEAR-WISE COVERAGE AUDIT

rainfall_clean["year"] = (
    rainfall_clean[rain_time_col].dt.year
)

rainfall_clean["month"] = (
    rainfall_clean[rain_time_col].dt.month
)

year_summary = (
    rainfall_clean
    .groupby("year")
    .agg(
        observations=(rain_time_col, "count"),
        first_timestamp=(rain_time_col, "min"),
        last_timestamp=(rain_time_col, "max")
    )
    .reset_index()
)

print("STEP 35 — RAINFALL YEAR-WISE COVERAGE")
print("=" * 70)

display(year_summary)

STEP 35 — RAINFALL YEAR-WISE COVERAGE
======================================================================

   year  observations     first_timestamp      last_timestamp
0  2022           255 2022-03-24 14:00:00 2022-12-25 13:00:00
1  2023           200 2023-01-05 08:00:00 2023-12-16 23:00:00
2  2024            42 2024-02-02 15:00:00 2024-07-31 19:00:00
3  2025           964 2025-01-18 15:00:00 2025-04-23 13:00:00
4  2026             7 2026-05-22 07:00:00 2026-05-27 06:00:00

In [28]:
# STEP 36: RAINFALL INTEGRATION SOURCE CHECK

print("STEP 36 — RAINFALL INTEGRATION SOURCE CHECK")
print("=" * 70)

print("Rainfall working dataset shape:")
print(rainfall_clean.shape)

print("\nRainfall columns:")
print(rainfall_clean.columns.tolist())

print("\nRainfall value statistics:")
display(
    rainfall_clean[
        "Telemetry Hourly Rainfall (mm)"
    ].describe()
)

print("\nMissing rainfall values:")
print(
    rainfall_clean[
        "Telemetry Hourly Rainfall (mm)"
    ].isna().sum()
)

print("\nDate range:")
print(
    rainfall_clean[rain_time_col].min(),
    "to",
    rainfall_clean[rain_time_col].max()
)

STEP 36 — RAINFALL INTEGRATION SOURCE CHECK
======================================================================
Rainfall working dataset shape:
(1468, 23)

Rainfall columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)', 'time_gap', 'year', 'month']

Rainfall value statistics:

count    1322.000000
mean       49.710287
std        32.783871
min         0.200000
25%        13.250000
50%        61.300000
75%        66.800000
max       381.000000
Name: Telemetry Hourly Rainfall (mm), dtype: float64

Missing rainfall values:
146

Date range:
2022-03-24 14:00:00 to 2026-05-27 06:00:00

In [30]:
# STEP 36: RAINFALL INTEGRATION SOURCE CHECK

print("STEP 36 — RAINFALL INTEGRATION SOURCE CHECK")
print("=" * 70)

print("Rainfall working dataset shape:")
print(rainfall_clean.shape)

print("\nRainfall columns:")
print(rainfall_clean.columns.tolist())

print("\nRainfall value statistics:")
display(
    rainfall_clean[
        "Telemetry Hourly Rainfall (mm)"
    ].describe()
)

print("\nMissing rainfall values:")
print(
    rainfall_clean[
        "Telemetry Hourly Rainfall (mm)"
    ].isna().sum()
)

print("\nDate range:")
print(
    rainfall_clean[rain_time_col].min(),
    "to",
    rainfall_clean[rain_time_col].max()
)

STEP 36 — RAINFALL INTEGRATION SOURCE CHECK
======================================================================
Rainfall working dataset shape:
(1468, 23)

Rainfall columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Telemetry Hourly Rainfall (mm)', 'time_gap', 'year', 'month']

Rainfall value statistics:

count    1322.000000
mean       49.710287
std        32.783871
min         0.200000
25%        13.250000
50%        61.300000
75%        66.800000
max       381.000000
Name: Telemetry Hourly Rainfall (mm), dtype: float64

Missing rainfall values:
146

Date range:
2022-03-24 14:00:00 to 2026-05-27 06:00:00

In [31]:
# STEP 37: VALID RAINFALL OBSERVATION GAP ANALYSIS

valid_rainfall = rainfall_clean[
    rainfall_clean["Telemetry Hourly Rainfall (mm)"].notna()
].copy()

valid_rainfall = valid_rainfall.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

valid_rainfall["rainfall_gap"] = (
    valid_rainfall["Data Acquisition Time"]
    .diff()
)

print("STEP 37 — VALID RAINFALL OBSERVATION GAPS")
print("=" * 70)

print("Valid rainfall observations:")
print(len(valid_rainfall))

print("\nMost common gaps:")

display(
    valid_rainfall["rainfall_gap"]
    .value_counts()
    .head(15)
)

print("\nGap statistics:")

display(
    valid_rainfall["rainfall_gap"]
    .describe()
)

print("\nGaps <= 1 hour:")
print(
    (valid_rainfall["rainfall_gap"] <= pd.Timedelta(hours=1)).sum()
)

print("\nGaps <= 6 hours:")
print(
    (valid_rainfall["rainfall_gap"] <= pd.Timedelta(hours=6)).sum()
)

print("\nGaps <= 24 hours:")
print(
    (valid_rainfall["rainfall_gap"] <= pd.Timedelta(hours=24)).sum()
)

print("\nGaps > 24 hours:")
print(
    (valid_rainfall["rainfall_gap"] > pd.Timedelta(hours=24)).sum()
)

STEP 37 — VALID RAINFALL OBSERVATION GAPS
======================================================================
Valid rainfall observations:
1322

Most common gaps:

rainfall_gap
0 days 01:00:00    1022
0 days 02:00:00      94
0 days 03:00:00      30
0 days 07:00:00      11
0 days 04:00:00      10
0 days 08:00:00       9
0 days 06:00:00       7
0 days 13:00:00       6
0 days 05:00:00       6
0 days 10:00:00       5
0 days 09:00:00       5
0 days 18:00:00       5
0 days 14:00:00       4
0 days 12:00:00       4
0 days 19:00:00       4
Name: count, dtype: int64

Gap statistics:

count                       1321
mean      1 days 03:41:17.214231
std      12 days 22:16:28.041193
min              0 days 00:15:00
25%              0 days 01:00:00
50%              0 days 01:00:00
75%              0 days 01:00:00
max            393 days 18:00:00
Name: rainfall_gap, dtype: object

Gaps <= 1 hour:
1025

Gaps <= 6 hours:
1173

Gaps <= 24 hours:
1244

Gaps > 24 hours:
77

In [35]:
# STEP 38: RAINFALL RECENCY TEST

rainfall_valid = rainfall_clean[
    rainfall_clean["Telemetry Hourly Rainfall (mm)"].notna()
].copy()

rainfall_valid = rainfall_valid[
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].copy()

rainfall_valid = rainfall_valid.rename(
    columns={
        "Data Acquisition Time": "rainfall_time",
        "Telemetry Hourly Rainfall (mm)": "rainfall_value"
    }
)

rainfall_valid = rainfall_valid.sort_values("rainfall_time")

water_base = water_level_final[
    ["Data Acquisition Time"]
].copy()

water_base = water_base.rename(
    columns={
        "Data Acquisition Time": "water_time"
    }
)

water_base = water_base.sort_values("water_time")

# Find latest rainfall observation at or before each water-level timestamp
rainfall_recency = pd.merge_asof(
    water_base,
    rainfall_valid,
    left_on="water_time",
    right_on="rainfall_time",
    direction="backward"
)

# Calculate how old the rainfall observation is
rainfall_recency["rainfall_age_hours"] = (
    rainfall_recency["water_time"]
    - rainfall_recency["rainfall_time"]
).dt.total_seconds() / 3600

print("STEP 38 — RAINFALL RECENCY TEST")
print("=" * 70)

print("Water-level timestamps:", len(rainfall_recency))

print(
    "Water-level timestamps with previous valid rainfall:",
    rainfall_recency["rainfall_time"].notna().sum()
)

print(
    "Water-level timestamps with no previous rainfall:",
    rainfall_recency["rainfall_time"].isna().sum()
)

print("\nRainfall age statistics:")

display(
    rainfall_recency["rainfall_age_hours"].describe()
)

print("\nRainfall availability by recency:")

for hours in [1, 3, 6, 12, 24, 48, 72]:
    
    count = (
        rainfall_recency["rainfall_age_hours"] <= hours
    ).sum()

    percentage = (
        count / len(rainfall_recency) * 100
    )

    print(
        f"Within {hours:>2} hours : "
        f"{count:>5} "
        f"({percentage:.2f}%)"
    )

STEP 38 — RAINFALL RECENCY TEST
======================================================================
Water-level timestamps: 11124
Water-level timestamps with previous valid rainfall: 10637
Water-level timestamps with no previous rainfall: 487

Rainfall age statistics:

count    10637.000000
mean      1272.531705
std       1774.987085
min          0.000000
25%        106.000000
50%        551.000000
75%       1720.000000
max       9449.000000
Name: rainfall_age_hours, dtype: float64

Rainfall availability by recency:
Within  1 hours :   479 (4.31%)
Within  3 hours :   606 (5.45%)
Within  6 hours :   764 (6.87%)
Within 12 hours :  1011 (9.09%)
Within 24 hours :  1337 (12.02%)
Within 48 hours :  1836 (16.50%)
Within 72 hours :  2181 (19.61%)

In [38]:
# STEP 39 — RAINFALL-WATER LEVEL TEMPORAL ALIGNMENT TEST

water_time = pd.to_datetime(
    water_level_final["Data Acquisition Time"]
)

rainfall_valid = rainfall_clean[
    rainfall_clean["Telemetry Hourly Rainfall (mm)"].notna()
].copy()

rainfall_valid = rainfall_valid[
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].sort_values("Data Acquisition Time")

# ---------------------------------------------------------
# Create water-level timeline
# ---------------------------------------------------------

alignment_test = pd.DataFrame({
    "Data Acquisition Time": water_time
}).sort_values("Data Acquisition Time")

# ---------------------------------------------------------
# Find most recent rainfall observation within 72 hours
# ---------------------------------------------------------

alignment_test = pd.merge_asof(
    alignment_test,
    rainfall_valid,
    on="Data Acquisition Time",
    direction="backward",
    tolerance=pd.Timedelta(hours=72)
)

# ---------------------------------------------------------
# Find actual rainfall timestamp separately
# ---------------------------------------------------------

rainfall_timestamp = rainfall_valid[
    ["Data Acquisition Time"]
].rename(
    columns={
        "Data Acquisition Time": "rainfall_timestamp"
    }
)

alignment_test = pd.merge_asof(
    alignment_test.sort_values("Data Acquisition Time"),
    rainfall_timestamp.sort_values("rainfall_timestamp"),
    left_on="Data Acquisition Time",
    right_on="rainfall_timestamp",
    direction="backward",
    tolerance=pd.Timedelta(hours=72)
)

# ---------------------------------------------------------
# Calculate rainfall age
# ---------------------------------------------------------

alignment_test["rainfall_age_hours"] = (
    alignment_test["Data Acquisition Time"]
    - alignment_test["rainfall_timestamp"]
).dt.total_seconds() / 3600

# ---------------------------------------------------------
# Classify rainfall recency
# ---------------------------------------------------------

def classify_rainfall_age(hours):

    if pd.isna(hours):
        return "No rainfall within 72h"

    elif hours <= 1:
        return "0-1 hour"

    elif hours <= 3:
        return "1-3 hours"

    elif hours <= 6:
        return "3-6 hours"

    elif hours <= 12:
        return "6-12 hours"

    elif hours <= 24:
        return "12-24 hours"

    elif hours <= 48:
        return "24-48 hours"

    else:
        return "48-72 hours"


alignment_test["rainfall_recency_group"] = (
    alignment_test["rainfall_age_hours"]
    .apply(classify_rainfall_age)
)

# ---------------------------------------------------------
# FINAL OUTPUT
# ---------------------------------------------------------

print("STEP 39 — RAINFALL-WATER LEVEL TEMPORAL ALIGNMENT")
print("=" * 70)

print(
    "Total water-level timestamps:",
    len(alignment_test)
)

print("\nRainfall alignment groups:")

display(
    alignment_test[
        "rainfall_recency_group"
    ]
    .value_counts()
    .reindex([
        "0-1 hour",
        "1-3 hours",
        "3-6 hours",
        "6-12 hours",
        "12-24 hours",
        "24-48 hours",
        "48-72 hours",
        "No rainfall within 72h"
    ])
    .fillna(0)
    .astype(int)
)

print(
    "\nRainfall aligned within 24 hours:",
    alignment_test["rainfall_age_hours"].le(24).sum()
)

print(
    "Rainfall aligned within 72 hours:",
    alignment_test["rainfall_age_hours"].le(72).sum()
)

print(
    "No rainfall within 72 hours:",
    alignment_test["rainfall_age_hours"].isna().sum()
)

STEP 39 — RAINFALL-WATER LEVEL TEMPORAL ALIGNMENT
======================================================================
Total water-level timestamps: 11124

Rainfall alignment groups:

rainfall_recency_group
0-1 hour                   479
1-3 hours                  127
3-6 hours                  158
6-12 hours                 247
12-24 hours                326
24-48 hours                499
48-72 hours                345
No rainfall within 72h    8943
Name: count, dtype: int64

Rainfall aligned within 24 hours: 1337
Rainfall aligned within 72 hours: 2181
No rainfall within 72 hours: 8943

In [39]:
# STEP 40 — RAINFALL WINDOW AVAILABILITY TEST

print("STEP 40 — RAINFALL WINDOW AVAILABILITY")
print("=" * 70)

water_times = (
    water_level_final[
        ["Data Acquisition Time"]
    ]
    .copy()
    .sort_values("Data Acquisition Time")
)

rainfall_valid = (
    rainfall_clean[
        rainfall_clean["Telemetry Hourly Rainfall (mm)"].notna()
    ][
        [
            "Data Acquisition Time",
            "Telemetry Hourly Rainfall (mm)"
        ]
    ]
    .copy()
    .sort_values("Data Acquisition Time")
)

# ---------------------------------------------------------
# Find latest rainfall observation before each water time
# ---------------------------------------------------------

aligned = pd.merge_asof(
    water_times,
    rainfall_valid,
    on="Data Acquisition Time",
    direction="backward"
)

aligned = aligned.rename(
    columns={
        "Data Acquisition Time": "water_timestamp",
        "Telemetry Hourly Rainfall (mm)": "rainfall_value"
    }
)

# ---------------------------------------------------------
# Find timestamp of latest rainfall observation
# ---------------------------------------------------------

rainfall_lookup = rainfall_valid.rename(
    columns={
        "Data Acquisition Time": "rainfall_timestamp"
    }
)[["rainfall_timestamp"]]

aligned = pd.merge_asof(
    aligned.sort_values("water_timestamp"),
    rainfall_lookup.sort_values("rainfall_timestamp"),
    left_on="water_timestamp",
    right_on="rainfall_timestamp",
    direction="backward"
)

# ---------------------------------------------------------
# Calculate age
# ---------------------------------------------------------

aligned["rainfall_age_hours"] = (
    aligned["water_timestamp"]
    - aligned["rainfall_timestamp"]
).dt.total_seconds() / 3600

# ---------------------------------------------------------
# Availability counts
# ---------------------------------------------------------

windows = [1, 3, 6, 12, 24, 48, 72]

for hours in windows:

    count = (
        aligned["rainfall_age_hours"]
        .le(hours)
        .sum()
    )

    percentage = (
        count / len(aligned) * 100
    )

    print(
        f"Within {hours:>2} hours : "
        f"{count:>5} rows "
        f"({percentage:.2f}%)"
    )

# ---------------------------------------------------------
# Rainfall observation gap at aligned point
# ---------------------------------------------------------

aligned["rainfall_age_group"] = pd.cut(
    aligned["rainfall_age_hours"],
    bins=[-0.001, 1, 3, 6, 12, 24, 48, 72, float("inf")],
    labels=[
        "0-1h",
        "1-3h",
        "3-6h",
        "6-12h",
        "12-24h",
        "24-48h",
        "48-72h",
        ">72h"
    ]
)

print("\nRainfall age distribution:")

display(
    aligned["rainfall_age_group"]
    .value_counts()
    .sort_index()
)

STEP 40 — RAINFALL WINDOW AVAILABILITY
======================================================================
Within  1 hours :   479 rows (4.31%)
Within  3 hours :   606 rows (5.45%)
Within  6 hours :   764 rows (6.87%)
Within 12 hours :  1011 rows (9.09%)
Within 24 hours :  1337 rows (12.02%)
Within 48 hours :  1836 rows (16.50%)
Within 72 hours :  2181 rows (19.61%)

Rainfall age distribution:

rainfall_age_group
0-1h       479
1-3h       127
3-6h       158
6-12h      247
12-24h     326
24-48h     499
48-72h     345
>72h      8456
Name: count, dtype: int64

In [41]:
# STEP 41 — RAINFALL CUMULATIVE WINDOW COVERAGE TEST

print("STEP 41 — RAINFALL CUMULATIVE WINDOW COVERAGE")
print("=" * 70)

# ---------------------------------------------------------
# 1. Prepare valid rainfall data
# ---------------------------------------------------------

rainfall_valid_41 = rainfall_clean[
    rainfall_clean["Telemetry Hourly Rainfall (mm)"].notna()
][
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].copy()

rainfall_valid_41["Data Acquisition Time"] = pd.to_datetime(
    rainfall_valid_41["Data Acquisition Time"]
)

rainfall_valid_41 = (
    rainfall_valid_41
    .sort_values("Data Acquisition Time")
    .drop_duplicates(
        subset="Data Acquisition Time",
        keep="first"
    )
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 2. Prepare water-level timestamps
# ---------------------------------------------------------

water_times_41 = water_level_final[
    ["Data Acquisition Time"]
].copy()

water_times_41["Data Acquisition Time"] = pd.to_datetime(
    water_times_41["Data Acquisition Time"]
)

water_times_41 = (
    water_times_41
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)


# ---------------------------------------------------------
# 3. Calculate rainfall observations inside each window
# ---------------------------------------------------------

window_results = []

for timestamp in water_times_41["Data Acquisition Time"]:

    result = {
        "water_timestamp": timestamp
    }

    for hours in [1, 3, 6, 12, 24]:

        start_time = (
            timestamp - pd.Timedelta(hours=hours)
        )

        observations = rainfall_valid_41[
            (rainfall_valid_41["Data Acquisition Time"] > start_time)
            &
            (rainfall_valid_41["Data Acquisition Time"] <= timestamp)
        ]

        result[f"{hours}h_obs_count"] = len(observations)

    window_results.append(result)


window_test_41 = pd.DataFrame(window_results)


# ---------------------------------------------------------
# 4. Display basic information
# ---------------------------------------------------------

print("Water-level timestamps:",
      len(water_times_41))

print("Valid rainfall observations:",
      len(rainfall_valid_41))

print()


# ---------------------------------------------------------
# 5. Coverage summary
# ---------------------------------------------------------

print("RAINFALL WINDOW OBSERVATION COVERAGE")
print("-" * 70)

for hours in [1, 3, 6, 12, 24]:

    col = f"{hours}h_obs_count"

    # At least one rainfall observation
    available = (
        window_test_41[col] >= 1
    ).sum()

    percentage = (
        available / len(window_test_41) * 100
    )

    print(
        f"Previous {hours:>2}h : "
        f"{available:>5} water-level timestamps "
        f"({percentage:6.2f}%) have >=1 rainfall observation"
    )


# ---------------------------------------------------------
# 6. Observation count statistics
# ---------------------------------------------------------

print("\nOBSERVATION COUNT STATISTICS")
print("-" * 70)

display(
    window_test_41[
        [
            "1h_obs_count",
            "3h_obs_count",
            "6h_obs_count",
            "12h_obs_count",
            "24h_obs_count"
        ]
    ].describe()
)


# ---------------------------------------------------------
# 7. Exact zero-availability counts
# ---------------------------------------------------------

print("\nNO RAINFALL OBSERVATION INSIDE WINDOW")
print("-" * 70)

for hours in [1, 3, 6, 12, 24]:

    col = f"{hours}h_obs_count"

    no_data = (
        window_test_41[col] == 0
    ).sum()

    percentage = (
        no_data / len(window_test_41) * 100
    )

    print(
        f"Previous {hours:>2}h : "
        f"{no_data:>5} timestamps "
        f"({percentage:6.2f}%)"
    )


# ---------------------------------------------------------
# 8. Save result in notebook
# ---------------------------------------------------------

print("\nWindow coverage test completed.")

print(
    "\nResult DataFrame:",
    "window_test_41",
    "Shape:",
    window_test_41.shape
)

STEP 41 — RAINFALL CUMULATIVE WINDOW COVERAGE
======================================================================
Water-level timestamps: 11124
Valid rainfall observations: 1322

RAINFALL WINDOW OBSERVATION COVERAGE
----------------------------------------------------------------------
Previous  1h :   393 water-level timestamps (  3.53%) have >=1 rainfall observation
Previous  3h :   548 water-level timestamps (  4.93%) have >=1 rainfall observation
Previous  6h :   714 water-level timestamps (  6.42%) have >=1 rainfall observation
Previous 12h :   978 water-level timestamps (  8.79%) have >=1 rainfall observation
Previous 24h :  1316 water-level timestamps ( 11.83%) have >=1 rainfall observation

OBSERVATION COUNT STATISTICS
----------------------------------------------------------------------

       1h_obs_count  3h_obs_count  6h_obs_count  12h_obs_count  24h_obs_count
count  11124.000000  11124.000000  11124.000000   11124.000000   11124.000000
mean       0.035419      0.104908      0.208828       0.413700       0.810590
std        0.185330      0.503389      0.972881       1.888993       3.666021
min        0.000000      0.000000      0.000000       0.000000       0.000000
25%        0.000000      0.000000      0.000000       0.000000       0.000000
50%        0.000000      0.000000      0.000000       0.000000       0.000000
75%        0.000000      0.000000      0.000000       0.000000       0.000000
max        2.000000      3.000000      6.000000      12.000000      24.000000

NO RAINFALL OBSERVATION INSIDE WINDOW
----------------------------------------------------------------------
Previous  1h : 10731 timestamps ( 96.47%)
Previous  3h : 10576 timestamps ( 95.07%)
Previous  6h : 10410 timestamps ( 93.58%)
Previous 12h : 10146 timestamps ( 91.21%)
Previous 24h :  9808 timestamps ( 88.17%)

Window coverage test completed.

Result DataFrame: window_test_41 Shape: (11124, 6)

In [42]:
# STEP 42 — RAINFALL CUMULATIVE VALUE AVAILABILITY

import pandas as pd
import numpy as np

# ---------------------------------------------------------
# 1. Prepare water-level timestamps
# ---------------------------------------------------------

water_base = water_level_final[
    ["Data Acquisition Time"]
].copy()

water_base["Data Acquisition Time"] = pd.to_datetime(
    water_base["Data Acquisition Time"]
)

water_base = water_base.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)


# ---------------------------------------------------------
# 2. Prepare valid rainfall observations
# ---------------------------------------------------------

rainfall_valid = rainfall_clean[
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].copy()

rainfall_valid["Data Acquisition Time"] = pd.to_datetime(
    rainfall_valid["Data Acquisition Time"]
)

rainfall_valid = rainfall_valid.dropna(
    subset=["Telemetry Hourly Rainfall (mm)"]
)

rainfall_valid = rainfall_valid.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)


# ---------------------------------------------------------
# 3. Create cumulative rainfall windows
# ---------------------------------------------------------

rainfall_series = rainfall_valid.set_index(
    "Data Acquisition Time"
)["Telemetry Hourly Rainfall (mm)"]


for window in ["1h", "3h", "6h", "12h", "24h"]:
    
    cumulative = rainfall_series.rolling(
        window=window,
        closed="both"
    ).sum()
    
    water_base[f"rainfall_{window}_sum"] = (
        water_base["Data Acquisition Time"]
        .map(cumulative)
    )


# ---------------------------------------------------------
# 4. Availability summary
# ---------------------------------------------------------

print("STEP 42 — RAINFALL CUMULATIVE VALUE AVAILABILITY")
print("=" * 70)

print(f"Water-level timestamps: {len(water_base)}")
print(f"Valid rainfall observations: {len(rainfall_valid)}")
print()

print("CUMULATIVE RAINFALL FEATURE AVAILABILITY")
print("-" * 70)

for window in ["1h", "3h", "6h", "12h", "24h"]:
    
    col = f"rainfall_{window}_sum"
    
    available = water_base[col].notna().sum()
    percentage = available / len(water_base) * 100
    
    print(
        f"Previous {window:>3} : "
        f"{available:5d} timestamps "
        f"({percentage:6.2f}%)"
    )


# ---------------------------------------------------------
# 5. Statistics
# ---------------------------------------------------------

print()
print("CUMULATIVE RAINFALL STATISTICS")
print("-" * 70)

print(
    water_base[
        [
            "rainfall_1h_sum",
            "rainfall_3h_sum",
            "rainfall_6h_sum",
            "rainfall_12h_sum",
            "rainfall_24h_sum"
        ]
    ].describe()
)


# ---------------------------------------------------------
# 6. Save result in memory
# ---------------------------------------------------------

rainfall_cumulative_42 = water_base.copy()

print()
print("Result DataFrame:")
print(
    "rainfall_cumulative_42 Shape:",
    rainfall_cumulative_42.shape
)

STEP 42 — RAINFALL CUMULATIVE VALUE AVAILABILITY
======================================================================
Water-level timestamps: 11124
Valid rainfall observations: 1322

CUMULATIVE RAINFALL FEATURE AVAILABILITY
----------------------------------------------------------------------
Previous  1h :   393 timestamps (  3.53%)
Previous  3h :   393 timestamps (  3.53%)
Previous  6h :   393 timestamps (  3.53%)
Previous 12h :   393 timestamps (  3.53%)
Previous 24h :   393 timestamps (  3.53%)

CUMULATIVE RAINFALL STATISTICS
----------------------------------------------------------------------
       rainfall_1h_sum  rainfall_3h_sum  rainfall_6h_sum  rainfall_12h_sum  \
count       393.000000       393.000000       393.000000        393.000000
mean         98.118575       187.269720       318.722646        576.071756
std          55.552077       103.164016       177.197399        325.303979
min           0.200000         0.200000         0.200000          0.200000
25%          61.300000       133.600000       245.100000        381.000000
50%         122.600000       245.200000       400.800000        735.600000
75%         133.600000       261.700000       440.100000        796.900000
max         381.000000       381.000000       484.300000        885.100000

       rainfall_24h_sum
count        393.000000
mean        1077.303308
std          624.325625
min            0.200000
25%          417.500000
50%         1419.500000
75%         1497.700000
max         1670.000000

Result DataFrame:
rainfall_cumulative_42 Shape: (11124, 6)

In [ ]:
# ============================================================
# STEP 43 — FINAL RAINFALL FEATURE CONSTRUCTION CHECK
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Base water-level dataset
# ------------------------------------------------------------

water_base = water_level_final[
    ["Data Acquisition Time"]
].copy()

water_base["Data Acquisition Time"] = pd.to_datetime(
    water_base["Data Acquisition Time"]
)

water_base = water_base.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Valid rainfall observations
# ------------------------------------------------------------

rainfall_valid = rainfall_clean[
    [
        "Data Acquisition Time",
        "Telemetry Hourly Rainfall (mm)"
    ]
].copy()

rainfall_valid["Data Acquisition Time"] = pd.to_datetime(
    rainfall_valid["Data Acquisition Time"]
)

rainfall_valid = rainfall_valid.dropna(
    subset=["Telemetry Hourly Rainfall (mm)"]
)

rainfall_valid = rainfall_valid.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Create rainfall cumulative features
# ------------------------------------------------------------

feature_data = water_base.copy()

rainfall_col = "Telemetry Hourly Rainfall (mm)"

for hours in [1, 3, 6, 12, 24]:

    counts = []
    sums = []

    for water_time in feature_data["Data Acquisition Time"]:

        start_time = water_time - pd.Timedelta(hours=hours)

        window = rainfall_valid[
            (rainfall_valid["Data Acquisition Time"] > start_time)
            &
            (rainfall_valid["Data Acquisition Time"] <= water_time)
        ]

        counts.append(len(window))

        if len(window) > 0:
            sums.append(window[rainfall_col].sum())
        else:
            sums.append(np.nan)

    feature_data[f"rainfall_{hours}h_count"] = counts
    feature_data[f"rainfall_{hours}h_sum"] = sums

# ------------------------------------------------------------
# Final check
# ------------------------------------------------------------

print("=" * 70)
print("STEP 43 — FINAL RAINFALL FEATURE CONSTRUCTION CHECK")
print("=" * 70)

print("Rows:", len(feature_data))
print("Columns:", len(feature_data.columns))

print("\nColumns:")
print(feature_data.columns.tolist())

print("\nRainfall feature availability:")
for hours in [1, 3, 6, 12, 24]:

    col = f"rainfall_{hours}h_sum"

    available = feature_data[col].notna().sum()
    percentage = available / len(feature_data) * 100

    print(
        f"Previous {hours:2d}h : "
        f"{available:5d} timestamps "
        f"({percentage:6.2f}%)"
    )

print("\nMissing values:")
print(feature_data.isna().sum())

print("\nFirst 10 rows:")
display(feature_data.head(10))

print("\nFinal rainfall feature dataset shape:")
print(feature_data.shape)

In [2]:
# ============================================================
# RECOVER STEP 42 DATAFRAME
# ============================================================

import pandas as pd
import numpy as np

# Load the cleaned rainfall dataset
rainfall_clean = pd.read_csv(
    "data/cleaned/darrang_fakipara_cleaned.csv"
)

rainfall_clean["Data Acquisition Time"] = pd.to_datetime(
    rainfall_clean["Data Acquisition Time"],
    errors="coerce"
)

# Load water-level final dataset
water_level_final = pd.read_csv(
    "data/final/darrang_water_level_final.csv"
)

water_level_final["Data Acquisition Time"] = pd.to_datetime(
    water_level_final["Data Acquisition Time"],
    errors="coerce"
)

print("Recovered source datasets")
print("-" * 60)
print("Rainfall:", rainfall_clean.shape)
print("Water level:", water_level_final.shape)

Recovered source datasets
------------------------------------------------------------
Rainfall: (11124, 24)
Water level: (11124, 24)

In [3]:
print("RAINFALL DATASET CHECK")
print("=" * 70)

print("Shape:", rainfall_clean.shape)

print("\nColumns:")
print(rainfall_clean.columns.tolist())

print("\nFirst 3 rows:")
display(rainfall_clean.head(3))

RAINFALL DATASET CHECK
======================================================================
Shape: (11124, 24)

Columns:
['Data Acquisition Time', '_id', 'SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Is_DischargeDataAvailable', 'RL_of_zeroGauge', 'MeanSeaLevel', 'River Water Level Telemetry Hourly (meter)']

First 3 rows:

,Data Acquisition Time,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,...,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,River Water Level Telemetry Hourly (meter)
0,2022-01-01 20:00:00,16499,16499,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,1.275
1,2022-01-03 00:00:00,16534,16534,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.159
2,2022-01-03 01:00:00,16535,16535,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,...,-,-,-,-,26.508333,92.116389,No,0,0,0.158

In [6]:
# ============================================================
# RECOVER RAINFALL DATASET FROM VERIFIED RAW FILES
# ============================================================

import pandas as pd
import numpy as np

print("STEP 42 — RECOVERING RAINFALL WORKING DATASET")
print("=" * 70)

# ------------------------------------------------------------
# Load the TWO VERIFIED rainfall raw files
# ------------------------------------------------------------

rainfall_2021_2025 = pd.read_csv(
    "data/raw/assam_rainfall_2021_2025.csv"
)

rainfall_2026_2030 = pd.read_csv(
    "data/raw/assam_rainfall_2026_2030.csv"
)

print("Raw rainfall files loaded:")
print("2021-2025:", rainfall_2021_2025.shape)
print("2026-2030:", rainfall_2026_2030.shape)

# ------------------------------------------------------------
# Combine
# ------------------------------------------------------------

rainfall_all = pd.concat(
    [rainfall_2021_2025, rainfall_2026_2030],
    ignore_index=True
)

# ------------------------------------------------------------
# Parse timestamp
# ------------------------------------------------------------

rainfall_all["Data Acquisition Time"] = pd.to_datetime(
    rainfall_all["Data Acquisition Time"],
    errors="coerce",
    dayfirst=True
)

rainfall_col = "Telemetry Hourly Rainfall (mm)"

# ------------------------------------------------------------
# Select TARGET station
# ------------------------------------------------------------

rainfall_fakirpara = rainfall_all[
    rainfall_all["Station"].astype(str).str.strip()
    == "NH15 Crossing Fakirpara Tangni"
].copy()

rainfall_fakirpara = rainfall_fakirpara.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Remove duplicate timestamps
#
# IMPORTANT:
# We do NOT resolve the conflicting values here.
# The validated duplicate-resolution logic from Steps 27-28
# will be reconstructed separately.
# ------------------------------------------------------------

duplicate_mask = rainfall_fakirpara[
    "Data Acquisition Time"
].duplicated(keep=False)

duplicate_rows = rainfall_fakirpara[duplicate_mask].copy()

# ------------------------------------------------------------
# Identify exact duplicate pairs
# ------------------------------------------------------------

duplicate_groups = (
    rainfall_fakirpara[
        rainfall_fakirpara["Data Acquisition Time"].duplicated(keep=False)
    ]
    .groupby("Data Acquisition Time")
)

exact_duplicate_times = []

for timestamp, group in duplicate_groups:
    values = group[rainfall_col].dropna().tolist()

    if len(values) == 2 and values[0] == values[1]:
        exact_duplicate_times.append(timestamp)

# ------------------------------------------------------------
# Keep one copy of exact duplicates
# ------------------------------------------------------------

exact_duplicate_clean = rainfall_fakirpara[
    rainfall_fakirpara["Data Acquisition Time"].isin(
        exact_duplicate_times
    )
].drop_duplicates(
    subset=["Data Acquisition Time"],
    keep="first"
)

# ------------------------------------------------------------
# Remove ALL duplicate timestamps first
# ------------------------------------------------------------

rainfall_unique = rainfall_fakirpara[
    ~rainfall_fakirpara["Data Acquisition Time"].duplicated(
        keep=False
    )
].copy()

# ------------------------------------------------------------
# Add exact duplicates back
# ------------------------------------------------------------

rainfall_clean = pd.concat(
    [rainfall_unique, exact_duplicate_clean],
    ignore_index=True
)

rainfall_clean = rainfall_clean.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Add time features
# ------------------------------------------------------------

rainfall_clean["time_gap"] = (
    rainfall_clean["Data Acquisition Time"].diff()
)

rainfall_clean["year"] = (
    rainfall_clean["Data Acquisition Time"].dt.year
)

rainfall_clean["month"] = (
    rainfall_clean["Data Acquisition Time"].dt.month
)

# ------------------------------------------------------------
# FINAL CHECK
# ------------------------------------------------------------

print()
print("RECOVERED RAINFALL DATASET")
print("-" * 70)

print("Shape:", rainfall_clean.shape)

print(
    "Duplicate timestamps:",
    rainfall_clean["Data Acquisition Time"].duplicated().sum()
)

print(
    "Missing rainfall:",
    rainfall_clean[rainfall_col].isna().sum()
)

print(
    "Valid rainfall:",
    rainfall_clean[rainfall_col].notna().sum()
)

print(
    "Date range:",
    rainfall_clean["Data Acquisition Time"].min(),
    "to",
    rainfall_clean["Data Acquisition Time"].max()
)

STEP 42 — RECOVERING RAINFALL WORKING DATASET
======================================================================
Raw rainfall files loaded:
2021-2025: (74560, 20)
2026-2030: (1336, 20)

RECOVERED RAINFALL DATASET
----------------------------------------------------------------------
Shape: (1322, 23)
Duplicate timestamps: 0
Missing rainfall: 0
Valid rainfall: 1322
Date range: 2022-03-25 06:00:00 to 2026-05-27 06:00:00

In [7]:
# ============================================================
# STEP 42 — EXACT RECOVERY OF VALIDATED RAINFALL CLEAN DATA
# ============================================================

rainfall_col = "Telemetry Hourly Rainfall (mm)"

# Start from the target-station raw data
station_data = rainfall_fakirpara.copy()

station_data = station_data.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Find duplicate timestamps
# ------------------------------------------------------------

duplicate_mask = station_data[
    "Data Acquisition Time"
].duplicated(keep=False)

duplicate_rows = station_data[duplicate_mask].copy()

# ------------------------------------------------------------
# Separate exact and conflicting duplicate timestamps
# ------------------------------------------------------------

duplicate_groups = (
    duplicate_rows
    .groupby("Data Acquisition Time")
)

exact_duplicate_times = []
conflicting_duplicate_times = []

for timestamp, group in duplicate_groups:

    values = group[rainfall_col].tolist()

    if len(set(values)) == 1:
        exact_duplicate_times.append(timestamp)
    else:
        conflicting_duplicate_times.append(timestamp)

# ------------------------------------------------------------
# Keep ONE row for exact duplicates
# ------------------------------------------------------------

exact_duplicate_clean = (
    station_data[
        station_data["Data Acquisition Time"].isin(
            exact_duplicate_times
        )
    ]
    .drop_duplicates(
        subset=["Data Acquisition Time"],
        keep="first"
    )
    .copy()
)

# ------------------------------------------------------------
# Keep all non-duplicate rows
# ------------------------------------------------------------

unique_rows = station_data[
    ~station_data["Data Acquisition Time"].duplicated(
        keep=False
    )
].copy()

# ------------------------------------------------------------
# Keep ONE row for each conflicting timestamp
# BUT set rainfall to NaN because the true value is unresolved
# ------------------------------------------------------------

conflicting_clean = (
    station_data[
        station_data["Data Acquisition Time"].isin(
            conflicting_duplicate_times
        )
    ]
    .sort_values("Data Acquisition Time")
    .groupby("Data Acquisition Time", as_index=False)
    .first()
    .copy()
)

conflicting_clean[rainfall_col] = np.nan

# ------------------------------------------------------------
# Combine
# ------------------------------------------------------------

rainfall_clean = pd.concat(
    [
        unique_rows,
        exact_duplicate_clean,
        conflicting_clean
    ],
    ignore_index=True
)

rainfall_clean = rainfall_clean.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

# ------------------------------------------------------------
# Add validated time features
# ------------------------------------------------------------

rainfall_clean["time_gap"] = (
    rainfall_clean["Data Acquisition Time"].diff()
)

rainfall_clean["year"] = (
    rainfall_clean["Data Acquisition Time"].dt.year
)

rainfall_clean["month"] = (
    rainfall_clean["Data Acquisition Time"].dt.month
)

# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print("STEP 42 — VALIDATED RAINFALL DATASET RECOVERED")
print("=" * 70)

print("Shape:", rainfall_clean.shape)

print(
    "Duplicate timestamps:",
    rainfall_clean["Data Acquisition Time"].duplicated().sum()
)

print(
    "Missing rainfall:",
    rainfall_clean[rainfall_col].isna().sum()
)

print(
    "Valid rainfall:",
    rainfall_clean[rainfall_col].notna().sum()
)

print(
    "Exact duplicate timestamps retained:",
    len(exact_duplicate_times)
)

print(
    "Conflicting duplicate timestamps flagged:",
    len(conflicting_duplicate_times)
)

print(
    "Date range:",
    rainfall_clean["Data Acquisition Time"].min(),
    "to",
    rainfall_clean["Data Acquisition Time"].max()
)

STEP 42 — VALIDATED RAINFALL DATASET RECOVERED
======================================================================
Shape: (1468, 23)
Duplicate timestamps: 0
Missing rainfall: 146
Valid rainfall: 1322
Exact duplicate timestamps retained: 7
Conflicting duplicate timestamps flagged: 146
Date range: 2022-03-24 14:00:00 to 2026-05-27 06:00:00

In [11]:
# ================================================================
# STEP 43 — RAINFALL CUMULATIVE FEATURE QUALITY CHECK
# ================================================================

import pandas as pd
import numpy as np

print("STEP 43 — RAINFALL CUMULATIVE FEATURE QUALITY CHECK")
print("=" * 70)

# ---------------------------------------------------------------
# 1. SOURCE DATA
# ---------------------------------------------------------------

water = water_level_final.copy()
rain = rainfall_clean.copy()

time_col = "Data Acquisition Time"
rainfall_col = "Telemetry Hourly Rainfall (mm)"

water[time_col] = pd.to_datetime(water[time_col], errors="coerce")
rain[time_col] = pd.to_datetime(rain[time_col], errors="coerce")

water = (
    water
    .dropna(subset=[time_col])
    .sort_values(time_col)
    .drop_duplicates(subset=[time_col])
    .reset_index(drop=True)
)

# Only VALID rainfall observations
rain[rainfall_col] = pd.to_numeric(
    rain[rainfall_col],
    errors="coerce"
)

rain_valid = (
    rain[
        rain[time_col].notna() &
        rain[rainfall_col].notna()
    ][[time_col, rainfall_col]]
    .sort_values(time_col)
    .drop_duplicates(subset=[time_col])
    .reset_index(drop=True)
)

print("Water-level timestamps:", len(water))
print("Valid rainfall observations:", len(rain_valid))

# ---------------------------------------------------------------
# 2. CALCULATE PREVIOUS RAINFALL WINDOW FEATURES
# ---------------------------------------------------------------

water_times = water[time_col].values
rain_times = rain_valid[time_col].values
rain_values = rain_valid[rainfall_col].astype(float).values

rain_ns = rain_times.astype("datetime64[ns]").astype("int64")
water_ns = water_times.astype("datetime64[ns]").astype("int64")

# Cumulative sum of rainfall
rain_cumsum = np.concatenate(
    ([0.0], np.cumsum(rain_values))
)

def calculate_window(window_hours):

    window_ns = window_hours * 60 * 60 * 1_000_000_000

    # Include rainfall at exact water timestamp
    right_idx = np.searchsorted(
        rain_ns,
        water_ns,
        side="right"
    )

    # Include observations from (t-window, t]
    left_idx = np.searchsorted(
        rain_ns,
        water_ns - window_ns,
        side="right"
    )

    sums = (
        rain_cumsum[right_idx]
        - rain_cumsum[left_idx]
    )

    counts = right_idx - left_idx

    return sums, counts


windows = [1, 3, 6, 12, 24]

rainfall_cumulative_43 = water[
    [time_col]
].copy()

for h in windows:

    sums, counts = calculate_window(h)

    rainfall_cumulative_43[f"rainfall_{h}h_sum"] = sums
    rainfall_cumulative_43[f"rainfall_{h}h_count"] = counts


# ---------------------------------------------------------------
# 3. WHERE NO RAINFALL EXISTS, SET FEATURES TO NaN
# ---------------------------------------------------------------

for h in windows:

    count_col = f"rainfall_{h}h_count"
    sum_col = f"rainfall_{h}h_sum"

    rainfall_cumulative_43.loc[
        rainfall_cumulative_43[count_col] == 0,
        sum_col
    ] = np.nan


# ---------------------------------------------------------------
# 4. QUALITY CHECK
# ---------------------------------------------------------------

print("\nCUMULATIVE FEATURE COVERAGE")
print("-" * 70)

for h in windows:

    count_col = f"rainfall_{h}h_count"
    sum_col = f"rainfall_{h}h_sum"

    available = (
        rainfall_cumulative_43[count_col] > 0
    ).sum()

    percentage = (
        available / len(rainfall_cumulative_43) * 100
    )

    print(
        f"Previous {h:2d}h : "
        f"{available:5d} timestamps "
        f"({percentage:6.2f}%)"
    )


# ---------------------------------------------------------------
# 5. CHECK CUMULATIVE LOGIC
# ---------------------------------------------------------------

print("\nCUMULATIVE SUM LOGIC CHECK")
print("-" * 70)

logic_checks = []

for h1, h2 in [(1, 3), (3, 6), (6, 12), (12, 24)]:

    col1 = f"rainfall_{h1}h_sum"
    col2 = f"rainfall_{h2}h_sum"

    valid = (
        rainfall_cumulative_43[col1].notna() &
        rainfall_cumulative_43[col2].notna()
    )

    violations = (
        rainfall_cumulative_43.loc[valid, col2]
        <
        rainfall_cumulative_43.loc[valid, col1]
    ).sum()

    logic_checks.append(
        [f"{h1}h <= {h2}h", violations]
    )

logic_check_df = pd.DataFrame(
    logic_checks,
    columns=["Comparison", "Violations"]
)

print(logic_check_df.to_string(index=False))


# ---------------------------------------------------------------
# 6. FEATURE STATISTICS
# ---------------------------------------------------------------

print("\nRAINFALL CUMULATIVE FEATURE STATISTICS")
print("-" * 70)

sum_cols = [
    f"rainfall_{h}h_sum"
    for h in windows
]

print(
    rainfall_cumulative_43[sum_cols]
    .describe()
    .round(3)
)


# ---------------------------------------------------------------
# 7. FINAL RESULT
# ---------------------------------------------------------------

print("\nFINAL RESULT")
print("-" * 70)

print(
    "rainfall_cumulative_43 Shape:",
    rainfall_cumulative_43.shape
)

print(
    "Duplicate timestamps:",
    rainfall_cumulative_43[time_col]
    .duplicated()
    .sum()
)

print("\nSTEP 43 COMPLETED.")

STEP 43 — RAINFALL CUMULATIVE FEATURE QUALITY CHECK
======================================================================
Water-level timestamps: 11124
Valid rainfall observations: 1322

CUMULATIVE FEATURE COVERAGE
----------------------------------------------------------------------
Previous  1h :   393 timestamps (  3.53%)
Previous  3h :   548 timestamps (  4.93%)
Previous  6h :   714 timestamps (  6.42%)
Previous 12h :   978 timestamps (  8.79%)
Previous 24h :  1316 timestamps ( 11.83%)

CUMULATIVE SUM LOGIC CHECK
----------------------------------------------------------------------
Comparison  Violations
  1h <= 3h           0
  3h <= 6h           0
 6h <= 12h           0
12h <= 24h           0

RAINFALL CUMULATIVE FEATURE STATISTICS
----------------------------------------------------------------------
       rainfall_1h_sum  rainfall_3h_sum  rainfall_6h_sum  rainfall_12h_sum  \
count          393.000          548.000          714.000           978.000
mean            52.909          112.432          171.677           247.134
std             35.842           91.230          173.633           321.352
min              0.200            0.200            0.200             0.200
25%             61.200            1.375            1.000             1.000
50%             61.300          144.700          108.550             7.000
75%             66.800          189.400          367.800           656.900
max            381.000          381.000          417.500           818.300

       rainfall_24h_sum
count          1316.000
mean            359.542
std             579.039
min               0.200
25%               1.000
50%               6.000
75%             381.000
max            1603.200

FINAL RESULT
----------------------------------------------------------------------
rainfall_cumulative_43 Shape: (11124, 11)
Duplicate timestamps: 0

STEP 43 COMPLETED.

In [12]:
# ================================================================
# STEP 44 — RAINFALL FEATURE INTEGRATION READINESS CHECK
# ================================================================

print("STEP 44 — RAINFALL FEATURE INTEGRATION READINESS CHECK")
print("=" * 70)

df = rainfall_cumulative_43.copy()

sum_cols = [
    "rainfall_1h_sum",
    "rainfall_3h_sum",
    "rainfall_6h_sum",
    "rainfall_12h_sum",
    "rainfall_24h_sum"
]

count_cols = [
    "rainfall_1h_count",
    "rainfall_3h_count",
    "rainfall_6h_count",
    "rainfall_12h_count",
    "rainfall_24h_count"
]

# ---------------------------------------------------------------
# 1. CHECK FEATURES EXIST
# ---------------------------------------------------------------

print("Required rainfall features:")
for col in sum_cols + count_cols:
    print(f"{col:25s} ->", "OK" if col in df.columns else "MISSING")


# ---------------------------------------------------------------
# 2. CHECK DUPLICATES
# ---------------------------------------------------------------

print("\nTimestamp checks")
print("-" * 70)

print(
    "Total rows:",
    len(df)
)

print(
    "Duplicate timestamps:",
    df["Data Acquisition Time"].duplicated().sum()
)


# ---------------------------------------------------------------
# 3. AVAILABILITY SUMMARY
# ---------------------------------------------------------------

print("\nRainfall feature availability")
print("-" * 70)

for col in sum_cols:

    available = df[col].notna().sum()
    pct = available / len(df) * 100

    print(
        f"{col:25s}: "
        f"{available:5d} ({pct:6.2f}%)"
    )


# ---------------------------------------------------------------
# 4. MISSINGNESS SUMMARY
# ---------------------------------------------------------------

print("\nRainfall feature missingness")
print("-" * 70)

for col in sum_cols:

    missing = df[col].isna().sum()
    pct = missing / len(df) * 100

    print(
        f"{col:25s}: "
        f"{missing:5d} ({pct:6.2f}%)"
    )


# ---------------------------------------------------------------
# 5. CHECK MONOTONIC CUMULATIVE RELATION
# ---------------------------------------------------------------

print("\nCumulative relationship check")
print("-" * 70)

comparisons = [
    ("rainfall_1h_sum", "rainfall_3h_sum"),
    ("rainfall_3h_sum", "rainfall_6h_sum"),
    ("rainfall_6h_sum", "rainfall_12h_sum"),
    ("rainfall_12h_sum", "rainfall_24h_sum")
]

for a, b in comparisons:

    valid = df[a].notna() & df[b].notna()

    violations = (
        df.loc[valid, b] < df.loc[valid, a]
    ).sum()

    print(
        f"{a} <= {b} : "
        f"{violations} violations"
    )


# ---------------------------------------------------------------
# FINAL
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 44 COMPLETED")
print("=" * 70)
print("Rainfall features are ready for integration.")

STEP 44 — RAINFALL FEATURE INTEGRATION READINESS CHECK
======================================================================
Required rainfall features:
rainfall_1h_sum           -> OK
rainfall_3h_sum           -> OK
rainfall_6h_sum           -> OK
rainfall_12h_sum          -> OK
rainfall_24h_sum          -> OK
rainfall_1h_count         -> OK
rainfall_3h_count         -> OK
rainfall_6h_count         -> OK
rainfall_12h_count        -> OK
rainfall_24h_count        -> OK

Timestamp checks
----------------------------------------------------------------------
Total rows: 11124
Duplicate timestamps: 0

Rainfall feature availability
----------------------------------------------------------------------
rainfall_1h_sum          :   393 (  3.53%)
rainfall_3h_sum          :   548 (  4.93%)
rainfall_6h_sum          :   714 (  6.42%)
rainfall_12h_sum         :   978 (  8.79%)
rainfall_24h_sum         :  1316 ( 11.83%)

Rainfall feature missingness
----------------------------------------------------------------------
rainfall_1h_sum          : 10731 ( 96.47%)
rainfall_3h_sum          : 10576 ( 95.07%)
rainfall_6h_sum          : 10410 ( 93.58%)
rainfall_12h_sum         : 10146 ( 91.21%)
rainfall_24h_sum         :  9808 ( 88.17%)

Cumulative relationship check
----------------------------------------------------------------------
rainfall_1h_sum <= rainfall_3h_sum : 0 violations
rainfall_3h_sum <= rainfall_6h_sum : 0 violations
rainfall_6h_sum <= rainfall_12h_sum : 0 violations
rainfall_12h_sum <= rainfall_24h_sum : 0 violations

======================================================================
STEP 44 COMPLETED
======================================================================
Rainfall features are ready for integration.

In [13]:
# ================================================================
# STEP 45 — RAINFALL + WATER LEVEL FEATURE INTEGRATION
# ================================================================

import pandas as pd
import numpy as np

print("STEP 45 — RAINFALL + WATER LEVEL FEATURE INTEGRATION")
print("=" * 70)

# ---------------------------------------------------------------
# 1. BASE DATASETS
# ---------------------------------------------------------------

water = water_level_final.copy()
rain_features = rainfall_cumulative_43.copy()

time_col = "Data Acquisition Time"

water[time_col] = pd.to_datetime(
    water[time_col],
    errors="coerce"
)

rain_features[time_col] = pd.to_datetime(
    rain_features[time_col],
    errors="coerce"
)

# ---------------------------------------------------------------
# 2. SELECT ONLY RAINFALL FEATURES
# ---------------------------------------------------------------

rain_cols = [
    "rainfall_1h_sum",
    "rainfall_3h_sum",
    "rainfall_6h_sum",
    "rainfall_12h_sum",
    "rainfall_24h_sum",
    "rainfall_1h_count",
    "rainfall_3h_count",
    "rainfall_6h_count",
    "rainfall_12h_count",
    "rainfall_24h_count"
]

rain_features = rain_features[
    [time_col] + rain_cols
].copy()

# Safety check
assert not rain_features[time_col].duplicated().any(), \
    "Rainfall timestamps are duplicated."

assert not water[time_col].duplicated().any(), \
    "Water-level timestamps are duplicated."

# ---------------------------------------------------------------
# 3. LEFT JOIN
# ---------------------------------------------------------------

model_integrated = water.merge(
    rain_features,
    on=time_col,
    how="left",
    validate="one_to_one"
)

# ---------------------------------------------------------------
# 4. VERIFY ROW COUNT
# ---------------------------------------------------------------

print("\nROW COUNT CHECK")
print("-" * 70)

print("Water-level rows :", len(water))
print("Integrated rows  :", len(model_integrated))
print(
    "Rows changed     :",
    len(model_integrated) - len(water)
)

# ---------------------------------------------------------------
# 5. DUPLICATE CHECK
# ---------------------------------------------------------------

print("\nTIMESTAMP CHECK")
print("-" * 70)

print(
    "Duplicate timestamps:",
    model_integrated[time_col].duplicated().sum()
)

# ---------------------------------------------------------------
# 6. RAINFALL FEATURE COVERAGE AFTER MERGE
# ---------------------------------------------------------------

print("\nRAINFALL FEATURE COVERAGE AFTER INTEGRATION")
print("-" * 70)

for col in rain_cols:

    available = model_integrated[col].notna().sum()
    percentage = available / len(model_integrated) * 100

    print(
        f"{col:25s}: "
        f"{available:5d} "
        f"({percentage:6.2f}%)"
    )

# ---------------------------------------------------------------
# 7. WATER LEVEL CHECK
# ---------------------------------------------------------------

water_col = "River Water Level Telemetry Hourly (meter)"

print("\nWATER LEVEL CHECK")
print("-" * 70)

print(
    "Missing water levels:",
    model_integrated[water_col].isna().sum()
)

print(
    "Valid water levels:",
    model_integrated[water_col].notna().sum()
)

# ---------------------------------------------------------------
# 8. FINAL SHAPE
# ---------------------------------------------------------------

print("\nFINAL INTEGRATED DATASET")
print("-" * 70)

print(
    "Shape:",
    model_integrated.shape
)

print(
    "Columns:",
    len(model_integrated.columns)
)

print("\nSTEP 45 COMPLETED.")

STEP 45 — RAINFALL + WATER LEVEL FEATURE INTEGRATION
======================================================================

ROW COUNT CHECK
----------------------------------------------------------------------
Water-level rows : 11124
Integrated rows  : 11124
Rows changed     : 0

TIMESTAMP CHECK
----------------------------------------------------------------------
Duplicate timestamps: 0

RAINFALL FEATURE COVERAGE AFTER INTEGRATION
----------------------------------------------------------------------
rainfall_1h_sum          :   393 (  3.53%)
rainfall_3h_sum          :   548 (  4.93%)
rainfall_6h_sum          :   714 (  6.42%)
rainfall_12h_sum         :   978 (  8.79%)
rainfall_24h_sum         :  1316 ( 11.83%)
rainfall_1h_count        : 11124 (100.00%)
rainfall_3h_count        : 11124 (100.00%)
rainfall_6h_count        : 11124 (100.00%)
rainfall_12h_count       : 11124 (100.00%)
rainfall_24h_count       : 11124 (100.00%)

WATER LEVEL CHECK
----------------------------------------------------------------------
Missing water levels: 45
Valid water levels: 11079

FINAL INTEGRATED DATASET
----------------------------------------------------------------------
Shape: (11124, 34)
Columns: 34

STEP 45 COMPLETED.

In [14]:
# ================================================================
# STEP 46 — WATER LEVEL LEAKAGE / SUSPICIOUS VALUE AUDIT
# ================================================================

import pandas as pd
import numpy as np

print("STEP 46 — WATER LEVEL LEAKAGE / SUSPICIOUS VALUE AUDIT")
print("=" * 70)

df = model_integrated.copy()

time_col = "Data Acquisition Time"
water_col = "River Water Level Telemetry Hourly (meter)"

df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
df[water_col] = pd.to_numeric(df[water_col], errors="coerce")

df = (
    df.sort_values(time_col)
      .drop_duplicates(subset=[time_col])
      .reset_index(drop=True)
)

# ---------------------------------------------------------------
# BASIC CHECK
# ---------------------------------------------------------------

print("\nBASIC WATER LEVEL STATUS")
print("-" * 70)

print("Rows:", len(df))
print("Missing water levels:", df[water_col].isna().sum())
print("Valid water levels:", df[water_col].notna().sum())

# ---------------------------------------------------------------
# EXTREME VALUE COUNTS
# ---------------------------------------------------------------

print("\nEXTREME VALUE CHECK")
print("-" * 70)

thresholds = [50, 100, 200, 300, 500]

for t in thresholds:
    count = (df[water_col] > t).sum()
    print(f"Values > {t:3d} m : {count}")

# ---------------------------------------------------------------
# LARGEST VALUES
# ---------------------------------------------------------------

print("\nTOP 20 HIGHEST WATER-LEVEL VALUES")
print("-" * 70)

top_values = (
    df[
        [time_col, water_col]
    ]
    .sort_values(water_col, ascending=False)
    .head(20)
)

print(top_values.to_string(index=False))

# ---------------------------------------------------------------
# ABRUPT CHANGE CHECK
# ---------------------------------------------------------------

df["water_level_change"] = df[water_col].diff()

print("\nLARGEST ABSOLUTE HOURLY CHANGES")
print("-" * 70)

largest_changes = (
    df[
        [
            time_col,
            water_col,
            "water_level_change"
        ]
    ]
    .dropna()
    .assign(
        abs_change=lambda x:
        x["water_level_change"].abs()
    )
    .sort_values(
        "abs_change",
        ascending=False
    )
    .head(20)
)

print(
    largest_changes.to_string(index=False)
)

# ---------------------------------------------------------------
# VERY LARGE JUMPS
# ---------------------------------------------------------------

print("\nVERY LARGE CHANGES")
print("-" * 70)

for threshold in [5, 10, 20, 50, 100]:

    count = (
        df["water_level_change"]
        .abs()
        .gt(threshold)
        .sum()
    )

    print(
        f"Absolute change > {threshold:3d} m : {count}"
    )

# ---------------------------------------------------------------
# FINAL
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 46 COMPLETED")
print("=" * 70)

STEP 46 — WATER LEVEL LEAKAGE / SUSPICIOUS VALUE AUDIT
======================================================================

BASIC WATER LEVEL STATUS
----------------------------------------------------------------------
Rows: 11124
Missing water levels: 45
Valid water levels: 11079

EXTREME VALUE CHECK
----------------------------------------------------------------------
Values >  50 m : 1760
Values > 100 m : 4
Values > 200 m : 4
Values > 300 m : 4
Values > 500 m : 4

TOP 20 HIGHEST WATER-LEVEL VALUES
----------------------------------------------------------------------
Data Acquisition Time  River Water Level Telemetry Hourly (meter)
  2023-06-09 22:00:00                                     641.231
  2022-06-09 21:00:00                                     624.669
  2024-01-09 15:00:00                                     608.700
  2023-08-08 14:00:00                                     529.533
  2025-05-06 11:00:00                                      62.636
  2025-05-06 12:00:00                                      62.593
  2025-05-06 10:00:00                                      62.588
  2025-05-06 08:00:00                                      62.559
  2025-05-06 09:00:00                                      62.547
  2025-05-06 07:00:00                                      62.524
  2025-05-06 13:00:00                                      62.497
  2025-05-06 06:00:00                                      62.447
  2025-05-06 14:00:00                                      62.315
  2025-05-06 05:00:00                                      62.309
  2025-05-06 15:00:00                                      62.278
  2025-05-06 18:00:00                                      62.255
  2025-05-06 19:00:00                                      62.248
  2025-05-06 16:00:00                                      62.247
  2025-05-06 17:00:00                                      62.227
  2025-05-06 20:00:00                                      62.227

LARGEST ABSOLUTE HOURLY CHANGES
----------------------------------------------------------------------
Data Acquisition Time  River Water Level Telemetry Hourly (meter)  water_level_change  abs_change
  2023-06-09 23:00:00                                       1.229            -640.002     640.002
  2023-06-09 22:00:00                                     641.231             639.998     639.998
  2022-06-09 22:00:00                                       0.641            -624.028     624.028
  2022-06-09 21:00:00                                     624.669             624.016     624.016
  2024-01-09 16:00:00                                      32.700            -576.000     576.000
  2024-01-09 15:00:00                                     608.700             576.000     576.000
  2023-08-08 15:00:00                                       1.419            -528.114     528.114
  2023-08-08 14:00:00                                     529.533             528.104     528.104
  2025-07-05 00:00:00                                      60.670              49.270      49.270
  2025-04-05 00:00:00                                      60.658              49.158      49.158
  2025-08-05 00:00:00                                      60.604              48.204      48.204
  2025-10-05 00:00:00                                      60.593              48.193      48.193
  2025-09-05 00:00:00                                      60.626              48.126      48.126
  2025-02-05 00:00:00                                      60.748              48.048      48.048
  2025-05-05 00:00:00                                      60.640              48.040      48.040
  2025-06-05 00:00:00                                      60.695              47.995      47.995
  2025-03-05 00:00:00                                      60.691              47.991      47.991
  2025-01-05 00:00:00                                      60.691              47.991      47.991
  2025-12-05 00:00:00                                      60.641              47.941      47.941
  2025-11-05 00:00:00                                      60.636              47.636      47.636

VERY LARGE CHANGES
----------------------------------------------------------------------
Absolute change >   5 m : 66
Absolute change >  10 m : 66
Absolute change >  20 m : 65
Absolute change >  50 m : 8
Absolute change > 100 m : 8

======================================================================
STEP 46 COMPLETED
======================================================================

In [15]:
# ================================================================
# STEP 47 — REMOVE DEFINITE WATER LEVEL LEAKAGE
# ================================================================

import numpy as np

print("STEP 47 — REMOVE DEFINITE WATER LEAKAGE")
print("="*70)

df = model_integrated.copy()

water_col = "River Water Level Telemetry Hourly (meter)"

# ---------------------------------------------------------
# Count before cleaning
# ---------------------------------------------------------

extreme_before = (df[water_col] > 100).sum()

print("Values >100 before cleaning:", extreme_before)

# ---------------------------------------------------------
# Replace impossible values with NaN
# ---------------------------------------------------------

df.loc[
    df[water_col] > 100,
    water_col
] = np.nan

# ---------------------------------------------------------
# Check
# ---------------------------------------------------------

extreme_after = (df[water_col] > 100).sum()

print("Values >100 after cleaning:", extreme_after)

print(
    "New missing water levels:",
    df[water_col].isna().sum()
)

print(
    "Valid water levels:",
    df[water_col].notna().sum()
)

# Save

model_clean = df.copy()

print("\nmodel_clean created")
print("Shape:", model_clean.shape)

STEP 47 — REMOVE DEFINITE WATER LEAKAGE
======================================================================
Values >100 before cleaning: 4
Values >100 after cleaning: 0
New missing water levels: 49
Valid water levels: 11075

model_clean created
Shape: (11124, 34)

In [16]:
# STEP 48 — POST-CLEANING WATER LEVEL VALIDATION

print("STEP 48 — POST-CLEANING WATER LEVEL VALIDATION")
print("=" * 70)

df = model_clean.copy()

time_col = "Data Acquisition Time"
water_col = "River Water Level Telemetry Hourly (meter)"

# ---------------------------------------------------------
# Basic checks
# ---------------------------------------------------------
df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
df[water_col] = pd.to_numeric(df[water_col], errors="coerce")

print("Rows:", len(df))
print("Duplicate timestamps:", df[time_col].duplicated().sum())
print("Missing timestamps:", df[time_col].isna().sum())

print("\nWATER LEVEL STATUS")
print("-" * 70)

print("Missing water levels:", df[water_col].isna().sum())
print("Valid water levels:", df[water_col].notna().sum())

# ---------------------------------------------------------
# Leakage check
# ---------------------------------------------------------
print("\nLEAKAGE CHECK")
print("-" * 70)

print("Values > 100 m:", (df[water_col] > 100).sum())
print("Values > 50 m :", (df[water_col] > 50).sum())

# ---------------------------------------------------------
# Remaining high values
# ---------------------------------------------------------
print("\nREMAINING HIGHEST VALUES")
print("-" * 70)

print(
    df[[time_col, water_col]]
    .dropna()
    .nlargest(10, water_col)
    .to_string(index=False)
)

# ---------------------------------------------------------
# Change analysis
# ---------------------------------------------------------
df = df.sort_values(time_col).reset_index(drop=True)

df["water_level_change"] = df[water_col].diff()
df["abs_water_level_change"] = df["water_level_change"].abs()

print("\nLARGE REMAINING CHANGES")
print("-" * 70)

for threshold in [5, 10, 20, 50, 100]:
    print(
        f"Absolute change > {threshold:3} m : "
        f"{(df['abs_water_level_change'] > threshold).sum()}"
    )

# ---------------------------------------------------------
# Final status
# ---------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 48 COMPLETED")
print("=" * 70)

STEP 48 — POST-CLEANING WATER LEVEL VALIDATION
======================================================================
Rows: 11124
Duplicate timestamps: 0
Missing timestamps: 0

WATER LEVEL STATUS
----------------------------------------------------------------------
Missing water levels: 49
Valid water levels: 11075

LEAKAGE CHECK
----------------------------------------------------------------------
Values > 100 m: 0
Values > 50 m : 1756

REMAINING HIGHEST VALUES
----------------------------------------------------------------------
Data Acquisition Time  River Water Level Telemetry Hourly (meter)
  2025-05-06 11:00:00                                      62.636
  2025-05-06 12:00:00                                      62.593
  2025-05-06 10:00:00                                      62.588
  2025-05-06 08:00:00                                      62.559
  2025-05-06 09:00:00                                      62.547
  2025-05-06 07:00:00                                      62.524
  2025-05-06 13:00:00                                      62.497
  2025-05-06 06:00:00                                      62.447
  2025-05-06 14:00:00                                      62.315
  2025-05-06 05:00:00                                      62.309

LARGE REMAINING CHANGES
----------------------------------------------------------------------
Absolute change >   5 m : 58
Absolute change >  10 m : 58
Absolute change >  20 m : 57
Absolute change >  50 m : 0
Absolute change > 100 m : 0

======================================================================
STEP 48 COMPLETED
======================================================================

In [18]:
# ================================================================
# STEP 49 — WATER DISCHARGE DATA AVAILABILITY AUDIT
# ================================================================

print("STEP 49 — WATER DISCHARGE DATA AVAILABILITY AUDIT")
print("=" * 70)

# Use current cleaned/integrated dataset
df = model_clean.copy()

# ------------------------------------------------
# 1. Identify discharge-related columns
# ------------------------------------------------
discharge_cols = [
    col for col in df.columns
    if "discharge" in col.lower()
]

print("\nDISCHARGE-RELATED COLUMNS FOUND")
print("-" * 70)

if discharge_cols:
    for col in discharge_cols:
        print(col)
else:
    print("No discharge-related columns found.")

# ------------------------------------------------
# 2. Audit availability flag
# ------------------------------------------------
availability_col = "Is_DischargeDataAvailable"

if availability_col in df.columns:

    print("\nDISCHARGE AVAILABILITY FLAG")
    print("-" * 70)

    print("Column:", availability_col)
    print("Data type:", df[availability_col].dtype)
    print("Total rows:", len(df))

    # Missing
    missing = df[availability_col].isna().sum()

    # Normalize values for checking
    availability_values = (
        df[availability_col]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    print("Missing availability flag:", missing)

    print("\nAvailability value counts:")
    print(df[availability_col].value_counts(dropna=False))

    # Yes / No
    yes_count = (availability_values == "yes").sum()
    no_count = (availability_values == "no").sum()

    print("\nAvailability summary")
    print("-" * 70)
    print(f"Discharge available (Yes): {yes_count}")
    print(f"Discharge unavailable (No): {no_count}")
    print(f"Missing flag             : {missing}")

    # Unexpected values
    valid_flags = {"yes", "no"}
    unexpected = availability_values[
        ~availability_values.isin(valid_flags)
        & availability_values.notna()
    ]

    print("\nUnexpected flag values:", len(unexpected))

else:

    print("\nWARNING:")
    print("Is_DischargeDataAvailable column not found.")

# ------------------------------------------------
# 3. Confirm whether actual numeric discharge exists
# ------------------------------------------------
numeric_discharge_cols = []

for col in discharge_cols:
    if col != availability_col:
        if pd.api.types.is_numeric_dtype(df[col]):
            numeric_discharge_cols.append(col)

print("\nACTUAL NUMERIC DISCHARGE DATA")
print("-" * 70)

if numeric_discharge_cols:
    print("Numeric discharge columns found:")
    for col in numeric_discharge_cols:
        print(col)
else:
    print("NO ACTUAL NUMERIC DISCHARGE COLUMN FOUND.")
    print("Current dataset contains only discharge availability information.")

# ------------------------------------------------
# 4. Final conclusion
# ------------------------------------------------
print("\n" + "=" * 70)
print("STEP 49 COMPLETED")
print("=" * 70)

if numeric_discharge_cols:
    print("Numeric discharge data is present and requires further audit.")
else:
    print("No numeric discharge data is present.")
    print("Is_DischargeDataAvailable is only an availability flag.")

STEP 49 — WATER DISCHARGE DATA AVAILABILITY AUDIT
======================================================================

DISCHARGE-RELATED COLUMNS FOUND
----------------------------------------------------------------------
Is_DischargeDataAvailable

DISCHARGE AVAILABILITY FLAG
----------------------------------------------------------------------
Column: Is_DischargeDataAvailable
Data type: str
Total rows: 11124
Missing availability flag: 0

Availability value counts:
Is_DischargeDataAvailable
No    11124
Name: count, dtype: int64

Availability summary
----------------------------------------------------------------------
Discharge available (Yes): 0
Discharge unavailable (No): 11124
Missing flag             : 0

Unexpected flag values: 0

ACTUAL NUMERIC DISCHARGE DATA
----------------------------------------------------------------------
NO ACTUAL NUMERIC DISCHARGE COLUMN FOUND.
Current dataset contains only discharge availability information.

======================================================================
STEP 49 COMPLETED
======================================================================
No numeric discharge data is present.
Is_DischargeDataAvailable is only an availability flag.

In [19]:
# ============================================================
# STEP 50 — FREEZE WATER + RAINFALL INTEGRATED DATASET
# ============================================================

import os
import pandas as pd

print("=" * 70)
print("STEP 50 — FREEZE WATER + RAINFALL DATASET")
print("=" * 70)

# Current final integrated dataset
final_water_rainfall = model_clean.copy()

# ------------------------------------------------------------
# Basic validation
# ------------------------------------------------------------

time_col = "Data Acquisition Time"
water_col = "River Water Level Telemetry Hourly (meter)"

final_water_rainfall[time_col] = pd.to_datetime(
    final_water_rainfall[time_col],
    errors="coerce"
)

final_water_rainfall = (
    final_water_rainfall
    .sort_values(time_col)
    .reset_index(drop=True)
)

print("\nDATASET STATUS")
print("-" * 70)

print("Shape:", final_water_rainfall.shape)
print("Duplicate timestamps:",
      final_water_rainfall[time_col].duplicated().sum())

print("Missing timestamps:",
      final_water_rainfall[time_col].isna().sum())

print("Missing water levels:",
      final_water_rainfall[water_col].isna().sum())

# ------------------------------------------------------------
# Rainfall feature check
# ------------------------------------------------------------

rainfall_features = [
    "rainfall_1h_sum",
    "rainfall_3h_sum",
    "rainfall_6h_sum",
    "rainfall_12h_sum",
    "rainfall_24h_sum",
    "rainfall_1h_count",
    "rainfall_3h_count",
    "rainfall_6h_count",
    "rainfall_12h_count",
    "rainfall_24h_count"
]

print("\nRAINFALL FEATURES")
print("-" * 70)

for col in rainfall_features:
    if col in final_water_rainfall.columns:
        print(
            f"{col:<25} "
            f"present | non-null: "
            f"{final_water_rainfall[col].notna().sum()}"
        )
    else:
        print(f"{col:<25} MISSING")

# ------------------------------------------------------------
# Save frozen dataset
# ------------------------------------------------------------

output_dir = r"D:\document\Brahmaputra-FloodCast\data\cleaned"
os.makedirs(output_dir, exist_ok=True)

output_file = os.path.join(
    output_dir,
    "water_rainfall_integrated_clean.csv"
)

final_water_rainfall.to_csv(
    output_file,
    index=False
)

print("\n" + "=" * 70)
print("STEP 50 COMPLETED")
print("=" * 70)

print("Frozen dataset:")
print(output_file)

print("Final shape:", final_water_rainfall.shape)

======================================================================
STEP 50 — FREEZE WATER + RAINFALL DATASET
======================================================================

DATASET STATUS
----------------------------------------------------------------------
Shape: (11124, 34)
Duplicate timestamps: 0
Missing timestamps: 0
Missing water levels: 49

RAINFALL FEATURES
----------------------------------------------------------------------
rainfall_1h_sum           present | non-null: 393
rainfall_3h_sum           present | non-null: 548
rainfall_6h_sum           present | non-null: 714
rainfall_12h_sum          present | non-null: 978
rainfall_24h_sum          present | non-null: 1316
rainfall_1h_count         present | non-null: 11124
rainfall_3h_count         present | non-null: 11124
rainfall_6h_count         present | non-null: 11124
rainfall_12h_count        present | non-null: 11124
rainfall_24h_count        present | non-null: 11124

======================================================================
STEP 50 COMPLETED
======================================================================
Frozen dataset:
D:\document\Brahmaputra-FloodCast\data\cleaned\water_rainfall_integrated_clean.csv
Final shape: (11124, 34)

In [6]:
# ============================================================
# STEP 1 — FINAL ML DATASET BASIC INTEGRITY CHECK
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 1 — FINAL ML DATASET BASIC INTEGRITY CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Dataset shape
# ------------------------------------------------------------
print("\n1. Dataset Shape:")
print(df.shape)

# ------------------------------------------------------------
# 2. Columns
# ------------------------------------------------------------
print("\n2. Number of Columns:")
print(len(df.columns))

# ------------------------------------------------------------
# 3. Missing values
# ------------------------------------------------------------
print("\n3. Missing Values:")
missing = df.isna().sum()
print(missing)

print("\nTotal Missing Values:")
print(missing.sum())

# ------------------------------------------------------------
# 4. Duplicate rows
# ------------------------------------------------------------
print("\n4. Duplicate Rows:")
print(df.duplicated().sum())

# ------------------------------------------------------------
# 5. Timestamp validation
# ------------------------------------------------------------
print("\n5. Timestamp Validation:")

df["Data Acquisition Time"] = pd.to_datetime(
    df["Data Acquisition Time"],
    errors="coerce"
)

print("Invalid timestamps:")
print(df["Data Acquisition Time"].isna().sum())

print("Duplicate timestamps:")
print(df["Data Acquisition Time"].duplicated().sum())

print("Chronologically sorted:")
print(df["Data Acquisition Time"].is_monotonic_increasing)

print("Start:")
print(df["Data Acquisition Time"].min())

print("End:")
print(df["Data Acquisition Time"].max())

# ------------------------------------------------------------
# 6. Target validation
# ------------------------------------------------------------
print("\n6. Target Validation:")

target = "High_Water_6h"

print("Missing target:")
print(df[target].isna().sum())

print("Unique target values:")
print(sorted(df[target].unique()))

print("\nTarget distribution:")
print(df[target].value_counts().sort_index())

print("\nTarget percentage:")
print(
    df[target]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\n" + "=" * 70)
print("STEP 1 COMPLETE")
print("=" * 70)

======================================================================
STEP 1 — FINAL ML DATASET BASIC INTEGRITY CHECK
======================================================================

1. Dataset Shape:
(7309, 21)

2. Number of Columns:
21

3. Missing Values:
Data Acquisition Time         0
Current_Water_Level           0
Month                         0
Hour                          0
DayOfYear                     0
WaterLevel_Lag_1h             0
WaterLevel_Lag_3h             0
WaterLevel_Lag_6h             0
WaterLevel_Lag_12h            0
WaterLevel_Lag_24h            0
WaterLevel_RollingMean_6h     0
WaterLevel_RollingMean_12h    0
WaterLevel_RollingMean_24h    0
WaterLevel_RollingMax_24h     0
WaterLevel_RollingMin_24h     0
WaterLevel_Change_1h          0
WaterLevel_Change_3h          0
WaterLevel_Change_6h          0
WaterLevel_Change_12h         0
WaterLevel_Change_24h         0
High_Water_6h                 0
dtype: int64

Total Missing Values:
0

4. Duplicate Rows:
0

5. Timestamp Validation:
Invalid timestamps:
0
Duplicate timestamps:
0
Chronologically sorted:
True
Start:
2022-01-04 04:00:00
End:
2026-06-03 17:00:00

6. Target Validation:
Missing target:
0
Unique target values:
[np.float64(0.0), np.float64(1.0)]

Target distribution:
High_Water_6h
0.0    5845
1.0    1464
Name: count, dtype: int64

Target percentage:
High_Water_6h
0.0    79.97
1.0    20.03
Name: proportion, dtype: float64

======================================================================
STEP 1 COMPLETE
======================================================================

In [7]:
# ============================================================
# STEP 2 — TIME GAP AUDIT
# ============================================================

print("=" * 70)
print("STEP 2 — TIME GAP AUDIT")
print("=" * 70)

# Calculate gap between consecutive observations
time_diff = (
    df["Data Acquisition Time"]
    .sort_values()
    .diff()
    .dropna()
)

# Convert to hours
gap_hours = time_diff.dt.total_seconds() / 3600

# ------------------------------------------------------------
# 1. Basic gap statistics
# ------------------------------------------------------------
print("\n1. Gap Statistics:")
print(gap_hours.describe())

# ------------------------------------------------------------
# 2. Most common gaps
# ------------------------------------------------------------
print("\n2. Most Common Time Gaps (hours):")
print(
    gap_hours
    .value_counts()
    .head(15)
    .sort_index()
)

# ------------------------------------------------------------
# 3. Gaps greater than 1 hour
# ------------------------------------------------------------
print("\n3. Gaps Greater Than 1 Hour:")

gaps_gt_1 = gap_hours[gap_hours > 1]

print("Count:", len(gaps_gt_1))

# ------------------------------------------------------------
# 4. Gaps greater than 3 hours
# ------------------------------------------------------------
print("\n4. Gaps Greater Than 3 Hours:")

gaps_gt_3 = gap_hours[gap_hours > 3]

print("Count:", len(gaps_gt_3))

# ------------------------------------------------------------
# 5. Gaps greater than 6 hours
# ------------------------------------------------------------
print("\n5. Gaps Greater Than 6 Hours:")

gaps_gt_6 = gap_hours[gap_hours > 6]

print("Count:", len(gaps_gt_6))

# ------------------------------------------------------------
# 6. Gaps greater than 24 hours
# ------------------------------------------------------------
print("\n6. Gaps Greater Than 24 Hours:")

gaps_gt_24 = gap_hours[gap_hours > 24]

print("Count:", len(gaps_gt_24))

# ------------------------------------------------------------
# 7. Maximum gap
# ------------------------------------------------------------
print("\n7. Maximum Gap:")

print(gap_hours.max(), "hours")
print("≈", round(gap_hours.max() / 24, 2), "days")

# ------------------------------------------------------------
# 8. Show largest gaps
# ------------------------------------------------------------
print("\n8. Five Largest Gaps:")

largest_gaps = gap_hours.nlargest(5)

for idx, gap in largest_gaps.items():
    current_time = df.loc[idx, "Data Acquisition Time"]
    previous_time = df.loc[idx - 1, "Data Acquisition Time"]

    print(
        f"{previous_time} → {current_time} : "
        f"{gap:.2f} hours"
    )

print("\n" + "=" * 70)
print("STEP 2 COMPLETE")
print("=" * 70)

======================================================================
STEP 2 — TIME GAP AUDIT
======================================================================

1. Gap Statistics:
count    7308.000000
mean        5.292419
std        59.949399
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      3627.000000
Name: Data Acquisition Time, dtype: float64

2. Most Common Time Gaps (hours):
Data Acquisition Time
1.0      6507
2.0       379
3.0       198
4.0        40
5.0        29
6.0        33
7.0        12
8.0         8
9.0         8
11.0        5
12.0        9
55.0        4
127.0       4
511.0       4
535.0       7
Name: count, dtype: int64

3. Gaps Greater Than 1 Hour:
Count: 801

4. Gaps Greater Than 3 Hours:
Count: 224

5. Gaps Greater Than 6 Hours:
Count: 122

6. Gaps Greater Than 24 Hours:
Count: 67

7. Maximum Gap:
3627.0 hours
≈ 151.12 days

8. Five Largest Gaps:
2025-12-08 17:00:00 → 2026-05-08 20:00:00 : 3627.00 hours
2022-08-12 17:00:00 → 2022-09-06 22:00:00 : 605.00 hours
2022-07-12 17:00:00 → 2022-08-06 17:00:00 : 600.00 hours
2025-08-08 16:00:00 → 2025-09-02 02:00:00 : 586.00 hours
2025-10-08 16:00:00 → 2025-11-02 00:00:00 : 584.00 hours

======================================================================
STEP 2 COMPLETE
======================================================================

In [8]:
# ============================================================
# STEP 3 — LAG FEATURE TIME-ALIGNMENT VALIDATION
# ============================================================

print("=" * 70)
print("STEP 3 — LAG FEATURE TIME-ALIGNMENT VALIDATION")
print("=" * 70)

# Work on a sorted copy
check = df.sort_values("Data Acquisition Time").reset_index(drop=True).copy()

# Calculate actual time difference from previous row
check["Actual_Gap_Hours"] = (
    check["Data Acquisition Time"]
    .diff()
    .dt.total_seconds()
    / 3600
)

# ------------------------------------------------------------
# Function to validate each lag
# ------------------------------------------------------------

lag_columns = {
    "WaterLevel_Lag_1h": 1,
    "WaterLevel_Lag_3h": 3,
    "WaterLevel_Lag_6h": 6,
    "WaterLevel_Lag_12h": 12,
    "WaterLevel_Lag_24h": 24
}

for lag_col, hours in lag_columns.items():

    print("\n" + "-" * 60)
    print(f"Checking {lag_col} ({hours}h)")
    print("-" * 60)

    # Find timestamp exactly `hours` before current timestamp
    expected_time = (
        check["Data Acquisition Time"]
        - pd.to_timedelta(hours, unit="h")
    )

    # Map timestamp → current water level
    level_map = pd.Series(
        check["Current_Water_Level"].values,
        index=check["Data Acquisition Time"]
    )

    expected_level = expected_time.map(level_map)

    # Rows where exact historical timestamp exists
    valid = expected_level.notna()

    # Compare feature with expected value
    difference = (
        check.loc[valid, lag_col].astype(float)
        - expected_level[valid].astype(float)
    ).abs()

    matches = (difference < 1e-8).sum()
    total = valid.sum()
    mismatches = total - matches

    print("Exact historical timestamp available:", total)
    print("Matching lag values:", matches)
    print("Mismatching lag values:", mismatches)

    if total > 0:
        print(
            "Match rate:",
            round(matches / total * 100, 2),
            "%"
        )

print("\n" + "=" * 70)
print("STEP 3 COMPLETE")
print("=" * 70)

======================================================================
STEP 3 — LAG FEATURE TIME-ALIGNMENT VALIDATION
======================================================================

------------------------------------------------------------
Checking WaterLevel_Lag_1h (1h)
------------------------------------------------------------
Exact historical timestamp available: 6507
Matching lag values: 6507
Mismatching lag values: 0
Match rate: 100.0 %

------------------------------------------------------------
Checking WaterLevel_Lag_3h (3h)
------------------------------------------------------------
Exact historical timestamp available: 6448
Matching lag values: 6448
Mismatching lag values: 0
Match rate: 100.0 %

------------------------------------------------------------
Checking WaterLevel_Lag_6h (6h)
------------------------------------------------------------
Exact historical timestamp available: 6362
Matching lag values: 6362
Mismatching lag values: 0
Match rate: 100.0 %

------------------------------------------------------------
Checking WaterLevel_Lag_12h (12h)
------------------------------------------------------------
Exact historical timestamp available: 6108
Matching lag values: 6108
Mismatching lag values: 0
Match rate: 100.0 %

------------------------------------------------------------
Checking WaterLevel_Lag_24h (24h)
------------------------------------------------------------
Exact historical timestamp available: 5240
Matching lag values: 5240
Mismatching lag values: 0
Match rate: 100.0 %

======================================================================
STEP 3 COMPLETE
======================================================================

In [9]:
# ============================================================
# STEP 4 — ROLLING FEATURE VALIDATION
# ============================================================

print("=" * 70)
print("STEP 4 — ROLLING FEATURE VALIDATION")
print("=" * 70)

check = df.sort_values("Data Acquisition Time").reset_index(drop=True).copy()

# ------------------------------------------------------------
# Helper function
# ------------------------------------------------------------

def validate_rolling_feature(df_check, feature_col, window_hours, operation):
    
    timestamps = df_check["Data Acquisition Time"]
    values = df_check["Current_Water_Level"]

    results = []

    for i in range(len(df_check)):

        current_time = timestamps.iloc[i]

        # IMPORTANT:
        # Only data from the past/current timestamp is allowed.
        start_time = current_time - pd.Timedelta(hours=window_hours)

        window = values[
            (timestamps >= start_time) &
            (timestamps <= current_time)
        ]

        if len(window) == 0:
            results.append(np.nan)
            continue

        if operation == "mean":
            results.append(window.mean())

        elif operation == "max":
            results.append(window.max())

        elif operation == "min":
            results.append(window.min())

    expected = pd.Series(results, index=df_check.index)

    valid = expected.notna()

    difference = (
        df_check.loc[valid, feature_col].astype(float)
        - expected.loc[valid].astype(float)
    ).abs()

    matches = (difference < 1e-8).sum()
    total = valid.sum()
    mismatches = total - matches

    print(f"\n{feature_col}")
    print(f"Expected window: previous {window_hours}h + current")
    print(f"Operation: {operation}")
    print(f"Checked rows: {total}")
    print(f"Matching rows: {matches}")
    print(f"Mismatching rows: {mismatches}")

    if total > 0:
        print(f"Match rate: {matches / total * 100:.2f}%")

# ------------------------------------------------------------
# Validate rolling features
# ------------------------------------------------------------

validate_rolling_feature(
    check,
    "WaterLevel_RollingMean_6h",
    6,
    "mean"
)

validate_rolling_feature(
    check,
    "WaterLevel_RollingMean_12h",
    12,
    "mean"
)

validate_rolling_feature(
    check,
    "WaterLevel_RollingMean_24h",
    24,
    "mean"
)

validate_rolling_feature(
    check,
    "WaterLevel_RollingMax_24h",
    24,
    "max"
)

validate_rolling_feature(
    check,
    "WaterLevel_RollingMin_24h",
    24,
    "min"
)

print("\n" + "=" * 70)
print("STEP 4 COMPLETE")
print("=" * 70)

======================================================================
STEP 4 — ROLLING FEATURE VALIDATION
======================================================================

WaterLevel_RollingMean_6h
Expected window: previous 6h + current
Operation: mean
Checked rows: 7309
Matching rows: 2873
Mismatching rows: 4436
Match rate: 39.31%

WaterLevel_RollingMean_12h
Expected window: previous 12h + current
Operation: mean
Checked rows: 7309
Matching rows: 2487
Mismatching rows: 4822
Match rate: 34.03%

WaterLevel_RollingMean_24h
Expected window: previous 24h + current
Operation: mean
Checked rows: 7309
Matching rows: 2057
Mismatching rows: 5252
Match rate: 28.14%

WaterLevel_RollingMax_24h
Expected window: previous 24h + current
Operation: max
Checked rows: 7309
Matching rows: 6390
Mismatching rows: 919
Match rate: 87.43%

WaterLevel_RollingMin_24h
Expected window: previous 24h + current
Operation: min
Checked rows: 7309
Matching rows: 5993
Mismatching rows: 1316
Match rate: 81.99%

======================================================================
STEP 4 COMPLETE
======================================================================

In [11]:
# ======================================================================
# STEP 4.1 — ROLLING FEATURE DIAGNOSTIC (AUTO COLUMN DETECTION)
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.1 — ROLLING FEATURE DIAGNOSTIC")
print("=" * 70)

# ----------------------------------------------------------------------
# 1. Show all available columns
# ----------------------------------------------------------------------

print("\nAVAILABLE COLUMNS:")
for i, col in enumerate(df.columns, 1):
    print(f"{i:02d}. {col}")

# ----------------------------------------------------------------------
# 2. Automatically identify timestamp column
# ----------------------------------------------------------------------

timestamp_candidates = [
    col for col in df.columns
    if any(word in col.lower() for word in [
        "datetime",
        "timestamp",
        "date_time",
        "date",
        "time"
    ])
]

print("\n" + "-" * 70)
print("TIMESTAMP COLUMN CANDIDATES")
print("-" * 70)

for col in timestamp_candidates:
    print("-", col)

# ----------------------------------------------------------------------
# 3. Automatically identify water-level source column
# ----------------------------------------------------------------------

water_candidates = [
    col for col in df.columns
    if (
        "waterlevel" in col.lower()
        or "water_level" in col.lower()
        or "water level" in col.lower()
        or "river water level" in col.lower()
    )
    and "lag" not in col.lower()
    and "rolling" not in col.lower()
]

print("\n" + "-" * 70)
print("WATER LEVEL SOURCE COLUMN CANDIDATES")
print("-" * 70)

for col in water_candidates:
    print("-", col)

# ----------------------------------------------------------------------
# 4. Automatically identify rolling columns
# ----------------------------------------------------------------------

rolling_cols = [
    col for col in df.columns
    if "rolling" in col.lower()
]

print("\n" + "-" * 70)
print("ROLLING FEATURE COLUMNS")
print("-" * 70)

for col in rolling_cols:
    print("-", col)

# ----------------------------------------------------------------------
# 5. Safety check
# ----------------------------------------------------------------------

if len(timestamp_candidates) == 0:
    raise ValueError(
        "No timestamp/date column could be detected. "
        "See AVAILABLE COLUMNS above."
    )

if len(water_candidates) == 0:
    raise ValueError(
        "No original water-level column could be detected. "
        "See AVAILABLE COLUMNS above."
    )

if len(rolling_cols) == 0:
    raise ValueError(
        "No rolling feature columns could be detected."
    )

# ----------------------------------------------------------------------
# 6. Select columns
#
# Prefer exact known project naming if present.
# Otherwise use first detected candidate.
# ----------------------------------------------------------------------

preferred_timestamp = [
    col for col in timestamp_candidates
    if col.lower() in [
        "datetime",
        "timestamp",
        "date_time"
    ]
]

if preferred_timestamp:
    timestamp_col = preferred_timestamp[0]
else:
    timestamp_col = timestamp_candidates[0]

preferred_water = [
    col for col in water_candidates
    if "river water level telemetry hourly" in col.lower()
]

if preferred_water:
    water_col = preferred_water[0]
else:
    water_col = water_candidates[0]

print("\n" + "=" * 70)
print("SELECTED SOURCE COLUMNS")
print("=" * 70)

print("Timestamp column :", timestamp_col)
print("Water level      :", water_col)

# ----------------------------------------------------------------------
# 7. Create diagnostic dataframe
# ----------------------------------------------------------------------

diag = df.copy()

diag[timestamp_col] = pd.to_datetime(
    diag[timestamp_col],
    errors="coerce"
)

diag = (
    diag
    .sort_values(timestamp_col)
    .reset_index(drop=True)
)

# ----------------------------------------------------------------------
# 8. Timestamp validity
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("TIMESTAMP QUALITY")
print("=" * 70)

print(
    "Invalid timestamps:",
    diag[timestamp_col].isna().sum()
)

print(
    "Duplicate timestamps:",
    diag[timestamp_col].duplicated().sum()
)

# ----------------------------------------------------------------------
# 9. Calculate timestamp gaps
# ----------------------------------------------------------------------

diag["Diagnostic_TimeGap"] = (
    diag[timestamp_col].diff()
)

print("\n" + "-" * 70)
print("TIMESTAMP GAP DISTRIBUTION")
print("-" * 70)

print(
    diag["Diagnostic_TimeGap"]
    .value_counts()
    .head(15)
)

# ----------------------------------------------------------------------
# 10. Water-level missingness
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WATER LEVEL QUALITY")
print("=" * 70)

print(
    "Water-level NaN:",
    diag[water_col].isna().sum()
)

print(
    "Water-level valid:",
    diag[water_col].notna().sum()
)

# ----------------------------------------------------------------------
# 11. Rolling feature NaN counts
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("ROLLING FEATURE NaN COUNTS")
print("=" * 70)

for col in rolling_cols:
    print(
        f"{col}: {diag[col].isna().sum()}"
    )

# ======================================================================
# 12. RECREATE ROLLING FEATURES USING ROW-BASED WINDOWS
# ======================================================================

print("\n" + "=" * 70)
print("ROW-BASED ROLLING RECREATION")
print("=" * 70)

diag["Diagnostic_Mean_6rows"] = (
    diag[water_col]
    .rolling(
        window=7,
        min_periods=7
    )
    .mean()
)

diag["Diagnostic_Mean_12rows"] = (
    diag[water_col]
    .rolling(
        window=13,
        min_periods=13
    )
    .mean()
)

diag["Diagnostic_Mean_24rows"] = (
    diag[water_col]
    .rolling(
        window=25,
        min_periods=25
    )
    .mean()
)

diag["Diagnostic_Max_24rows"] = (
    diag[water_col]
    .rolling(
        window=25,
        min_periods=25
    )
    .max()
)

diag["Diagnostic_Min_24rows"] = (
    diag[water_col]
    .rolling(
        window=25,
        min_periods=25
    )
    .min()
)

# ----------------------------------------------------------------------
# 13. Define comparisons
# ----------------------------------------------------------------------

comparison_map = {}

for col in rolling_cols:

    lower = col.lower()

    if "rollingmean_6h" in lower:
        comparison_map[col] = "Diagnostic_Mean_6rows"

    elif "rollingmean_12h" in lower:
        comparison_map[col] = "Diagnostic_Mean_12rows"

    elif "rollingmean_24h" in lower:
        comparison_map[col] = "Diagnostic_Mean_24rows"

    elif "rollingmax_24h" in lower:
        comparison_map[col] = "Diagnostic_Max_24rows"

    elif "rollingmin_24h" in lower:
        comparison_map[col] = "Diagnostic_Min_24rows"

# ----------------------------------------------------------------------
# 14. Compare original vs recreated
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("ROW-BASED RECREATION VALIDATION")
print("=" * 70)

validation_results = []

for original, recreated in comparison_map.items():

    valid = (
        diag[original].notna()
        &
        diag[recreated].notna()
    )

    checked = int(valid.sum())

    if checked == 0:

        print(f"\n{original}")
        print("No comparable rows.")

        validation_results.append({
            "Feature": original,
            "Checked": 0,
            "Matching": 0,
            "Mismatching": 0,
            "MatchRate": 0.0
        })

        continue

    difference = np.abs(
        diag.loc[valid, original]
        -
        diag.loc[valid, recreated]
    )

    matches = difference <= 1e-6

    matching = int(matches.sum())
    mismatching = int((~matches).sum())
    match_rate = matching / checked * 100

    validation_results.append({
        "Feature": original,
        "Checked": checked,
        "Matching": matching,
        "Mismatching": mismatching,
        "MatchRate": match_rate
    })

    print(f"\n{original}")
    print("-" * 50)
    print("Checked rows :", checked)
    print("Matching     :", matching)
    print("Mismatching  :", mismatching)
    print(f"Match rate   : {match_rate:.2f}%")
    print(
        f"Maximum diff : {difference.max():.10f}"
    )

# ----------------------------------------------------------------------
# 15. Validation summary table
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("VALIDATION SUMMARY")
print("=" * 70)

validation_df = pd.DataFrame(validation_results)

print(
    validation_df.to_string(index=False)
)

# ======================================================================
# 16. FIRST MISMATCHING EXAMPLES — ROLLING MEAN 6H
# ======================================================================

target_feature = None

for col in rolling_cols:
    if "rollingmean_6h" in col.lower():
        target_feature = col
        break

if target_feature is not None:

    print("\n" + "=" * 70)
    print("FIRST MISMATCHING EXAMPLES — ROLLING MEAN 6H")
    print("=" * 70)

    recreated_col = "Diagnostic_Mean_6rows"

    valid = (
        diag[target_feature].notna()
        &
        diag[recreated_col].notna()
    )

    difference = np.abs(
        diag[target_feature]
        -
        diag[recreated_col]
    )

    mismatch = (
        valid
        &
        (difference > 1e-6)
    )

    example_cols = [
        timestamp_col,
        "Diagnostic_TimeGap",
        water_col,
        target_feature,
        recreated_col
    ]

    print(
        diag.loc[
            mismatch,
            example_cols
        ]
        .head(20)
        .to_string(index=False)
    )

# ======================================================================
# 17. CHECK WHETHER MISMATCHES OCCUR AROUND TIME GAPS
# ======================================================================

print("\n" + "=" * 70)
print("MISMATCH + TIME-GAP DIAGNOSTIC")
print("=" * 70)

for original, recreated in comparison_map.items():

    valid = (
        diag[original].notna()
        &
        diag[recreated].notna()
    )

    difference = np.abs(
        diag[original]
        -
        diag[recreated]
    )

    mismatch = (
        valid
        &
        (difference > 1e-6)
    )

    mismatch_rows = diag.loc[mismatch]

    if len(mismatch_rows) == 0:
        print(f"\n{original}: No mismatches.")
        continue

    gap_rows = mismatch_rows[
        mismatch_rows["Diagnostic_TimeGap"] != pd.Timedelta(hours=1)
    ]

    print(f"\n{original}")
    print("Total mismatches              :", len(mismatch_rows))
    print("Mismatches near non-1h gaps   :", len(gap_rows))

# ======================================================================
# 18. FINAL DIAGNOSTIC STATUS
# ======================================================================

print("\n" + "=" * 70)
print("STEP 4.1 COMPLETE")
print("=" * 70)

print("\nIMPORTANT:")
print("This step ONLY diagnoses the rolling features.")
print("No existing rolling feature was modified.")
print("No rows were deleted.")
print("No model training was performed.")

print("\nWait for the diagnostic output before making any changes.")

======================================================================
STEP 4.1 — ROLLING FEATURE DIAGNOSTIC
======================================================================

AVAILABLE COLUMNS:
01. Data Acquisition Time
02. Current_Water_Level
03. Month
04. Hour
05. DayOfYear
06. WaterLevel_Lag_1h
07. WaterLevel_Lag_3h
08. WaterLevel_Lag_6h
09. WaterLevel_Lag_12h
10. WaterLevel_Lag_24h
11. WaterLevel_RollingMean_6h
12. WaterLevel_RollingMean_12h
13. WaterLevel_RollingMean_24h
14. WaterLevel_RollingMax_24h
15. WaterLevel_RollingMin_24h
16. WaterLevel_Change_1h
17. WaterLevel_Change_3h
18. WaterLevel_Change_6h
19. WaterLevel_Change_12h
20. WaterLevel_Change_24h
21. High_Water_6h

----------------------------------------------------------------------
TIMESTAMP COLUMN CANDIDATES
----------------------------------------------------------------------
- Data Acquisition Time

----------------------------------------------------------------------
WATER LEVEL SOURCE COLUMN CANDIDATES
----------------------------------------------------------------------
- Current_Water_Level
- WaterLevel_Change_1h
- WaterLevel_Change_3h
- WaterLevel_Change_6h
- WaterLevel_Change_12h
- WaterLevel_Change_24h

----------------------------------------------------------------------
ROLLING FEATURE COLUMNS
----------------------------------------------------------------------
- WaterLevel_RollingMean_6h
- WaterLevel_RollingMean_12h
- WaterLevel_RollingMean_24h
- WaterLevel_RollingMax_24h
- WaterLevel_RollingMin_24h

======================================================================
SELECTED SOURCE COLUMNS
======================================================================
Timestamp column : Data Acquisition Time
Water level      : Current_Water_Level

======================================================================
TIMESTAMP QUALITY
======================================================================
Invalid timestamps: 0
Duplicate timestamps: 0

----------------------------------------------------------------------
TIMESTAMP GAP DISTRIBUTION
----------------------------------------------------------------------
Diagnostic_TimeGap
0 days 01:00:00     6507
0 days 02:00:00      379
0 days 03:00:00      198
0 days 04:00:00       40
0 days 06:00:00       33
0 days 05:00:00       29
0 days 07:00:00       12
0 days 12:00:00        9
0 days 09:00:00        8
0 days 08:00:00        8
22 days 07:00:00       7
0 days 11:00:00        5
5 days 07:00:00        4
21 days 07:00:00       4
2 days 07:00:00        4
Name: count, dtype: int64

======================================================================
WATER LEVEL QUALITY
======================================================================
Water-level NaN: 0
Water-level valid: 7309

======================================================================
ROLLING FEATURE NaN COUNTS
======================================================================
WaterLevel_RollingMean_6h: 0
WaterLevel_RollingMean_12h: 0
WaterLevel_RollingMean_24h: 0
WaterLevel_RollingMax_24h: 0
WaterLevel_RollingMin_24h: 0

======================================================================
ROW-BASED ROLLING RECREATION
======================================================================

======================================================================
ROW-BASED RECREATION VALIDATION
======================================================================

WaterLevel_RollingMean_6h
--------------------------------------------------
Checked rows : 7303
Matching     : 2603
Mismatching  : 4700
Match rate   : 35.64%
Maximum diff : 40.9162380952

WaterLevel_RollingMean_12h
--------------------------------------------------
Checked rows : 7297
Matching     : 2215
Mismatching  : 5082
Match rate   : 30.35%
Maximum diff : 44.0437948718

WaterLevel_RollingMean_24h
--------------------------------------------------
Checked rows : 7285
Matching     : 1761
Mismatching  : 5524
Match rate   : 24.17%
Maximum diff : 35.9159504762

WaterLevel_RollingMax_24h
--------------------------------------------------
Checked rows : 7285
Matching     : 5695
Mismatching  : 1590
Match rate   : 78.17%
Maximum diff : 46.8390000000

WaterLevel_RollingMin_24h
--------------------------------------------------
Checked rows : 7285
Matching     : 5560
Mismatching  : 1725
Match rate   : 76.32%
Maximum diff : 48.8610000000

======================================================================
VALIDATION SUMMARY
======================================================================
                   Feature  Checked  Matching  Mismatching  MatchRate
 WaterLevel_RollingMean_6h     7303      2603         4700  35.642886
WaterLevel_RollingMean_12h     7297      2215         5082  30.354940
WaterLevel_RollingMean_24h     7285      1761         5524  24.172958
 WaterLevel_RollingMax_24h     7285      5695         1590  78.174331
 WaterLevel_RollingMin_24h     7285      5560         1725  76.321208

======================================================================
FIRST MISMATCHING EXAMPLES — ROLLING MEAN 6H
======================================================================
Data Acquisition Time Diagnostic_TimeGap  Current_Water_Level  WaterLevel_RollingMean_6h  Diagnostic_Mean_6rows
  2022-01-04 16:00:00    0 days 01:00:00               0.4520                   0.418591               0.370584
  2022-01-04 17:00:00    0 days 01:00:00               0.5250                   0.441894               0.405156
  2022-01-09 00:00:00    4 days 07:00:00               0.5240                   0.731667               0.436442
  2022-01-09 01:00:00    0 days 01:00:00               0.5310                   0.689667               0.464909
  2022-01-09 02:00:00    0 days 01:00:00               0.5370                   0.647500               0.488506
  2022-01-09 03:00:00    0 days 01:00:00               0.5340                   0.607500               0.505948
  2022-01-09 04:00:00    0 days 01:00:00               0.5315                   0.569083               0.519214
  2022-01-09 05:00:00    0 days 01:00:00               0.5290                   0.531083               0.530214
  2022-01-09 06:00:00    0 days 01:00:00               0.5225                   0.530833               0.529857
  2022-01-09 07:00:00    0 days 01:00:00               0.5160                   0.528333               0.528714
  2022-01-09 08:00:00    0 days 01:00:00               0.5150                   0.524667               0.526429
  2022-01-09 09:00:00    0 days 01:00:00               0.5155                   0.521583               0.523357
  2022-01-09 10:00:00    0 days 01:00:00               0.5160                   0.519000               0.520786
  2022-01-09 11:00:00    0 days 01:00:00               0.5210                   0.517667               0.519286
  2022-01-09 12:00:00    0 days 01:00:00               0.5260                   0.518250               0.518857
  2022-01-09 13:00:00    0 days 01:00:00               0.5275                   0.520167               0.519571
  2022-01-09 14:00:00    0 days 01:00:00               0.5290                   0.522500               0.521429
  2022-01-09 15:00:00    0 days 01:00:00               0.5305                   0.525000               0.523643
  2022-01-09 16:00:00    0 days 01:00:00               0.5320                   0.527667               0.526000
  2022-01-09 17:00:00    0 days 01:00:00               0.5370                   0.530333               0.529000

======================================================================
MISMATCH + TIME-GAP DIAGNOSTIC
======================================================================

WaterLevel_RollingMean_6h
Total mismatches              : 4700
Mismatches near non-1h gaps   : 556

WaterLevel_RollingMean_12h
Total mismatches              : 5082
Mismatches near non-1h gaps   : 596

WaterLevel_RollingMean_24h
Total mismatches              : 5524
Mismatches near non-1h gaps   : 662

WaterLevel_RollingMax_24h
Total mismatches              : 1590
Mismatches near non-1h gaps   : 362

WaterLevel_RollingMin_24h
Total mismatches              : 1725
Mismatches near non-1h gaps   : 394

======================================================================
STEP 4.1 COMPLETE
======================================================================

IMPORTANT:
This step ONLY diagnoses the rolling features.
No existing rolling feature was modified.
No rows were deleted.
No model training was performed.

Wait for the diagnostic output before making any changes.

In [12]:
# ======================================================================
# STEP 4.2 — EXACT ROLLING FORMULA IDENTIFICATION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.2 — EXACT ROLLING FORMULA IDENTIFICATION")
print("=" * 70)

# ----------------------------------------------------------------------
# SOURCE COLUMNS
# ----------------------------------------------------------------------

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"

diag = df.copy()

diag[time_col] = pd.to_datetime(
    diag[time_col],
    errors="coerce"
)

diag = (
    diag
    .sort_values(time_col)
    .reset_index(drop=True)
)

# ----------------------------------------------------------------------
# TEST DIFFERENT ROW-BASED WINDOW DEFINITIONS
# ----------------------------------------------------------------------

# 6h possibilities:
# A = 6 rows total
# B = 7 rows total (previous 6 + current)

diag["Test_Mean_6rows"] = (
    diag[water_col]
    .rolling(window=6, min_periods=6)
    .mean()
)

diag["Test_Mean_7rows"] = (
    diag[water_col]
    .rolling(window=7, min_periods=7)
    .mean()
)

# 12h possibilities
diag["Test_Mean_12rows"] = (
    diag[water_col]
    .rolling(window=12, min_periods=12)
    .mean()
)

diag["Test_Mean_13rows"] = (
    diag[water_col]
    .rolling(window=13, min_periods=13)
    .mean()
)

# 24h possibilities
diag["Test_Mean_24rows"] = (
    diag[water_col]
    .rolling(window=24, min_periods=24)
    .mean()
)

diag["Test_Mean_25rows"] = (
    diag[water_col]
    .rolling(window=25, min_periods=25)
    .mean()
)

# Max
diag["Test_Max_24rows"] = (
    diag[water_col]
    .rolling(window=24, min_periods=24)
    .max()
)

diag["Test_Max_25rows"] = (
    diag[water_col]
    .rolling(window=25, min_periods=25)
    .max()
)

# Min
diag["Test_Min_24rows"] = (
    diag[water_col]
    .rolling(window=24, min_periods=24)
    .min()
)

diag["Test_Min_25rows"] = (
    diag[water_col]
    .rolling(window=25, min_periods=25)
    .min()
)

# ----------------------------------------------------------------------
# FUNCTION TO CALCULATE MATCH RATE
# ----------------------------------------------------------------------

def compare_feature(original_col, test_col):

    valid = (
        diag[original_col].notna()
        &
        diag[test_col].notna()
    )

    if valid.sum() == 0:
        return 0.0, 0, 0

    diff = np.abs(
        diag.loc[valid, original_col]
        -
        diag.loc[valid, test_col]
    )

    matches = diff <= 1e-6

    return (
        matches.mean() * 100,
        int(matches.sum()),
        int((~matches).sum())
    )

# ----------------------------------------------------------------------
# ROLLING MEAN 6H
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WaterLevel_RollingMean_6h")
print("=" * 70)

rate6, match6, mismatch6 = compare_feature(
    "WaterLevel_RollingMean_6h",
    "Test_Mean_6rows"
)

rate7, match7, mismatch7 = compare_feature(
    "WaterLevel_RollingMean_6h",
    "Test_Mean_7rows"
)

print("\n6 ROWS TOTAL")
print("Matching    :", match6)
print("Mismatching :", mismatch6)
print(f"Match rate  : {rate6:.2f}%")

print("\n7 ROWS TOTAL")
print("Matching    :", match7)
print("Mismatching :", mismatch7)
print(f"Match rate  : {rate7:.2f}%")

# ----------------------------------------------------------------------
# ROLLING MEAN 12H
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WaterLevel_RollingMean_12h")
print("=" * 70)

rate12, match12, mismatch12 = compare_feature(
    "WaterLevel_RollingMean_12h",
    "Test_Mean_12rows"
)

rate13, match13, mismatch13 = compare_feature(
    "WaterLevel_RollingMean_12h",
    "Test_Mean_13rows"
)

print("\n12 ROWS TOTAL")
print("Matching    :", match12)
print("Mismatching :", mismatch12)
print(f"Match rate  : {rate12:.2f}%")

print("\n13 ROWS TOTAL")
print("Matching    :", match13)
print("Mismatching :", mismatch13)
print(f"Match rate  : {rate13:.2f}%")

# ----------------------------------------------------------------------
# ROLLING MEAN 24H
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WaterLevel_RollingMean_24h")
print("=" * 70)

rate24, match24, mismatch24 = compare_feature(
    "WaterLevel_RollingMean_24h",
    "Test_Mean_24rows"
)

rate25, match25, mismatch25 = compare_feature(
    "WaterLevel_RollingMean_24h",
    "Test_Mean_25rows"
)

print("\n24 ROWS TOTAL")
print("Matching    :", match24)
print("Mismatching :", mismatch24)
print(f"Match rate  : {rate24:.2f}%")

print("\n25 ROWS TOTAL")
print("Matching    :", match25)
print("Mismatching :", mismatch25)
print(f"Match rate  : {rate25:.2f}%")

# ----------------------------------------------------------------------
# MAX 24H
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WaterLevel_RollingMax_24h")
print("=" * 70)

rate_max24, match_max24, mismatch_max24 = compare_feature(
    "WaterLevel_RollingMax_24h",
    "Test_Max_24rows"
)

rate_max25, match_max25, mismatch_max25 = compare_feature(
    "WaterLevel_RollingMax_24h",
    "Test_Max_25rows"
)

print("\n24 ROWS TOTAL")
print("Matching    :", match_max24)
print("Mismatching :", mismatch_max24)
print(f"Match rate  : {rate_max24:.2f}%")

print("\n25 ROWS TOTAL")
print("Matching    :", match_max25)
print("Mismatching :", mismatch_max25)
print(f"Match rate  : {rate_max25:.2f}%")

# ----------------------------------------------------------------------
# MIN 24H
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("WaterLevel_RollingMin_24h")
print("=" * 70)

rate_min24, match_min24, mismatch_min24 = compare_feature(
    "WaterLevel_RollingMin_24h",
    "Test_Min_24rows"
)

rate_min25, match_min25, mismatch_min25 = compare_feature(
    "WaterLevel_RollingMin_24h",
    "Test_Min_25rows"
)

print("\n24 ROWS TOTAL")
print("Matching    :", match_min24)
print("Mismatching :", mismatch_min24)
print(f"Match rate  : {rate_min24:.2f}%")

print("\n25 ROWS TOTAL")
print("Matching    :", match_min25)
print("Mismatching :", mismatch_min25)
print(f"Match rate  : {rate_min25:.2f}%")

# ======================================================================
# SHOW ONE REAL EXAMPLE
# ======================================================================

print("\n" + "=" * 70)
print("REAL EXAMPLE — 2022-01-04 16:00")
print("=" * 70)

target_time = pd.Timestamp("2022-01-04 16:00:00")

example = diag[
    diag[time_col] == target_time
]

if len(example) > 0:

    cols = [
        time_col,
        water_col,
        "WaterLevel_RollingMean_6h",
        "Test_Mean_6rows",
        "Test_Mean_7rows"
    ]

    print(
        example[cols]
        .to_string(index=False)
    )

else:
    print("Target timestamp not found.")

# ======================================================================
# SHOW PREVIOUS 8 WATER LEVELS FOR MANUAL VERIFICATION
# ======================================================================

print("\n" + "=" * 70)
print("PREVIOUS WATER-LEVEL VALUES AROUND 2022-01-04 16:00")
print("=" * 70)

example_idx = diag.index[
    diag[time_col] == target_time
]

if len(example_idx) > 0:

    idx = example_idx[0]

    start = max(0, idx - 8)
    end = min(len(diag), idx + 2)

    cols = [
        time_col,
        water_col,
        "WaterLevel_RollingMean_6h",
        "Test_Mean_6rows",
        "Test_Mean_7rows"
    ]

    print(
        diag.loc[start:end, cols]
        .to_string(index=False)
    )

# ======================================================================
# STEP 4.2 COMPLETE
# ======================================================================

print("\n" + "=" * 70)
print("STEP 4.2 COMPLETE")
print("=" * 70)

print("\nNo existing feature was modified.")
print("No rows were deleted.")
print("No model was trained.")

======================================================================
STEP 4.2 — EXACT ROLLING FORMULA IDENTIFICATION
======================================================================

======================================================================
WaterLevel_RollingMean_6h
======================================================================

6 ROWS TOTAL
Matching    : 5996
Mismatching : 1308
Match rate  : 82.09%

7 ROWS TOTAL
Matching    : 2603
Mismatching : 4700
Match rate  : 35.64%

======================================================================
WaterLevel_RollingMean_12h
======================================================================

12 ROWS TOTAL
Matching    : 5317
Mismatching : 1981
Match rate  : 72.86%

13 ROWS TOTAL
Matching    : 2215
Mismatching : 5082
Match rate  : 30.35%

======================================================================
WaterLevel_RollingMean_24h
======================================================================

24 ROWS TOTAL
Matching    : 4445
Mismatching : 2841
Match rate  : 61.01%

25 ROWS TOTAL
Matching    : 1761
Mismatching : 5524
Match rate  : 24.17%

======================================================================
WaterLevel_RollingMax_24h
======================================================================

24 ROWS TOTAL
Matching    : 6081
Mismatching : 1205
Match rate  : 83.46%

25 ROWS TOTAL
Matching    : 5695
Mismatching : 1590
Match rate  : 78.17%

======================================================================
WaterLevel_RollingMin_24h
======================================================================

24 ROWS TOTAL
Matching    : 5763
Mismatching : 1523
Match rate  : 79.10%

25 ROWS TOTAL
Matching    : 5560
Mismatching : 1725
Match rate  : 76.32%

======================================================================
REAL EXAMPLE — 2022-01-04 16:00
======================================================================
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  Test_Mean_6rows  Test_Mean_7rows
  2022-01-04 16:00:00                0.452                   0.418591         0.385182         0.370584

======================================================================
PREVIOUS WATER-LEVEL VALUES AROUND 2022-01-04 16:00
======================================================================
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  Test_Mean_6rows  Test_Mean_7rows
  2022-01-04 04:00:00             0.283000                   0.272400              NaN              NaN
  2022-01-04 05:00:00             0.305000                   0.288000              NaN              NaN
  2022-01-04 07:00:00             0.331727                   0.304182              NaN              NaN
  2022-01-04 10:00:00             0.371818                   0.337073              NaN              NaN
  2022-01-04 13:00:00             0.411909                   0.385182              NaN              NaN
  2022-01-04 15:00:00             0.438636                   0.405227         0.357015              NaN
  2022-01-04 16:00:00             0.452000                   0.418591         0.385182         0.370584
  2022-01-04 17:00:00             0.525000                   0.441894         0.421848         0.405156
  2022-01-09 00:00:00             0.524000                   0.731667         0.453894         0.436442

======================================================================
STEP 4.2 COMPLETE
======================================================================

No existing feature was modified.
No rows were deleted.
No model was trained.

In [13]:
# ======================================================================
# STEP 4.3 — TIME-BASED ROLLING VALIDATION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.3 — TIME-BASED ROLLING VALIDATION")
print("=" * 70)

# ----------------------------------------------------------------------
# SOURCE COLUMNS
# ----------------------------------------------------------------------

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"

diag = df.copy()

diag[time_col] = pd.to_datetime(
    diag[time_col],
    errors="coerce"
)

diag = (
    diag
    .sort_values(time_col)
    .reset_index(drop=True)
)

# ----------------------------------------------------------------------
# Create timestamp index
# ----------------------------------------------------------------------

time_indexed = (
    diag
    .set_index(time_col)
)

# ----------------------------------------------------------------------
# TIME-BASED ROLLING FEATURES
#
# closed="both" means:
# previous N hours + current timestamp
# ----------------------------------------------------------------------

diag["TimeMean_6h"] = (
    time_indexed[water_col]
    .rolling(
        "6h",
        closed="both",
        min_periods=1
    )
    .mean()
    .to_numpy()
)

diag["TimeMean_12h"] = (
    time_indexed[water_col]
    .rolling(
        "12h",
        closed="both",
        min_periods=1
    )
    .mean()
    .to_numpy()
)

diag["TimeMean_24h"] = (
    time_indexed[water_col]
    .rolling(
        "24h",
        closed="both",
        min_periods=1
    )
    .mean()
    .to_numpy()
)

diag["TimeMax_24h"] = (
    time_indexed[water_col]
    .rolling(
        "24h",
        closed="both",
        min_periods=1
    )
    .max()
    .to_numpy()
)

diag["TimeMin_24h"] = (
    time_indexed[water_col]
    .rolling(
        "24h",
        closed="both",
        min_periods=1
    )
    .min()
    .to_numpy()
)

# ----------------------------------------------------------------------
# Validation function
# ----------------------------------------------------------------------

def validate(original_col, calculated_col):

    valid = (
        diag[original_col].notna()
        &
        diag[calculated_col].notna()
    )

    checked = int(valid.sum())

    if checked == 0:
        return 0, 0, 0, 0

    diff = np.abs(
        diag.loc[valid, original_col]
        -
        diag.loc[valid, calculated_col]
    )

    matches = diff <= 1e-6

    return (
        checked,
        int(matches.sum()),
        int((~matches).sum()),
        float(matches.mean() * 100)
    )

# ----------------------------------------------------------------------
# Validate all features
# ----------------------------------------------------------------------

tests = [
    (
        "WaterLevel_RollingMean_6h",
        "TimeMean_6h"
    ),
    (
        "WaterLevel_RollingMean_12h",
        "TimeMean_12h"
    ),
    (
        "WaterLevel_RollingMean_24h",
        "TimeMean_24h"
    ),
    (
        "WaterLevel_RollingMax_24h",
        "TimeMax_24h"
    ),
    (
        "WaterLevel_RollingMin_24h",
        "TimeMin_24h"
    )
]

print("\n" + "=" * 70)
print("TIME-BASED VALIDATION RESULTS")
print("=" * 70)

for original, calculated in tests:

    checked, matching, mismatching, rate = validate(
        original,
        calculated
    )

    print(f"\n{original}")
    print("-" * 55)
    print("Checked rows :", checked)
    print("Matching     :", matching)
    print("Mismatching  :", mismatching)
    print(f"Match rate   : {rate:.2f}%")

# ----------------------------------------------------------------------
# Detailed example: 2022-01-04 16:00
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("EXACT TIME-WINDOW EXAMPLE — 2022-01-04 16:00")
print("=" * 70)

target_time = pd.Timestamp(
    "2022-01-04 16:00:00"
)

example = diag[
    diag[time_col] == target_time
]

if len(example) > 0:

    cols = [
        time_col,
        water_col,
        "WaterLevel_RollingMean_6h",
        "TimeMean_6h",
        "WaterLevel_RollingMean_12h",
        "TimeMean_12h",
        "WaterLevel_RollingMean_24h",
        "TimeMean_24h"
    ]

    print(
        example[cols]
        .to_string(index=False)
    )

# ----------------------------------------------------------------------
# Show all records inside the previous 6-hour window
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("RECORDS INSIDE PREVIOUS 6 HOURS")
print("=" * 70)

window_start = target_time - pd.Timedelta(hours=6)

window_rows = diag[
    (diag[time_col] >= window_start)
    &
    (diag[time_col] <= target_time)
]

print(
    window_rows[
        [time_col, water_col]
    ].to_string(index=False)
)

# ----------------------------------------------------------------------
# Manual mean
# ----------------------------------------------------------------------

if len(window_rows) > 0:

    manual_mean = window_rows[water_col].mean()

    print("\nManual 6-hour mean:", manual_mean)

# ======================================================================
# STEP 4.3 COMPLETE
# ======================================================================

print("\n" + "=" * 70)
print("STEP 4.3 COMPLETE")
print("=" * 70)

print("\nNo existing rolling feature was modified.")
print("No rows were deleted.")
print("No model was trained.")

======================================================================
STEP 4.3 — TIME-BASED ROLLING VALIDATION
======================================================================

======================================================================
TIME-BASED VALIDATION RESULTS
======================================================================

WaterLevel_RollingMean_6h
-------------------------------------------------------
Checked rows : 7309
Matching     : 2873
Mismatching  : 4436
Match rate   : 39.31%

WaterLevel_RollingMean_12h
-------------------------------------------------------
Checked rows : 7309
Matching     : 2487
Mismatching  : 4822
Match rate   : 34.03%

WaterLevel_RollingMean_24h
-------------------------------------------------------
Checked rows : 7309
Matching     : 2057
Mismatching  : 5252
Match rate   : 28.14%

WaterLevel_RollingMax_24h
-------------------------------------------------------
Checked rows : 7309
Matching     : 6390
Mismatching  : 919
Match rate   : 87.43%

WaterLevel_RollingMin_24h
-------------------------------------------------------
Checked rows : 7309
Matching     : 5993
Mismatching  : 1316
Match rate   : 81.99%

======================================================================
EXACT TIME-WINDOW EXAMPLE — 2022-01-04 16:00
======================================================================
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  TimeMean_6h  WaterLevel_RollingMean_12h  TimeMean_12h  WaterLevel_RollingMean_24h  TimeMean_24h
  2022-01-04 16:00:00                0.452                   0.418591     0.418591                    0.381537      0.370584                    0.317405      0.370584

======================================================================
RECORDS INSIDE PREVIOUS 6 HOURS
======================================================================
Data Acquisition Time  Current_Water_Level
  2022-01-04 10:00:00             0.371818
  2022-01-04 13:00:00             0.411909
  2022-01-04 15:00:00             0.438636
  2022-01-04 16:00:00             0.452000

Manual 6-hour mean: 0.41859090909090907

======================================================================
STEP 4.3 COMPLETE
======================================================================

No existing rolling feature was modified.
No rows were deleted.
No model was trained.

In [14]:
# ======================================================================
# STEP 4.4 — ROLLING WINDOW FORENSIC VALIDATION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.4 — ROLLING WINDOW FORENSIC VALIDATION")
print("=" * 70)

# ----------------------------------------------------------------------
# SOURCE COLUMNS
# ----------------------------------------------------------------------

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"

diag = df.copy()

diag[time_col] = pd.to_datetime(
    diag[time_col],
    errors="coerce"
)

diag = (
    diag
    .sort_values(time_col)
    .reset_index(drop=True)
)

# ----------------------------------------------------------------------
# Helper function
# ----------------------------------------------------------------------

def match_rate(original, calculated):

    valid = (
        diag[original].notna()
        &
        calculated.notna()
    )

    if valid.sum() == 0:
        return 0.0

    diff = np.abs(
        diag.loc[valid, original]
        -
        calculated.loc[valid]
    )

    return float((diff <= 1e-6).mean() * 100)


# ======================================================================
# PART A — TEST TIME-BASED WINDOWS WITH ALL CLOSED OPTIONS
# ======================================================================

print("\n" + "=" * 70)
print("PART A — TIME-BASED WINDOW / CLOSED-BOUNDARY TEST")
print("=" * 70)

time_indexed = diag.set_index(time_col)

closed_options = [
    "right",
    "left",
    "both",
    "neither"
]

features = {
    "6h": "WaterLevel_RollingMean_6h",
    "12h": "WaterLevel_RollingMean_12h",
    "24h": "WaterLevel_RollingMean_24h"
}

results = []

for window_name, original_col in features.items():

    for closed in closed_options:

        calculated = (
            time_indexed[water_col]
            .rolling(
                window_name,
                closed=closed,
                min_periods=1
            )
            .mean()
        )

        rate = match_rate(
            original_col,
            calculated
        )

        results.append({
            "Feature": original_col,
            "Window": window_name,
            "Closed": closed,
            "MatchRate": rate
        })

        print(
            f"{original_col:35s} | "
            f"{window_name:4s} | "
            f"closed={closed:7s} | "
            f"{rate:6.2f}%"
        )


# ======================================================================
# PART B — TEST DIFFERENT ROW WINDOWS
# ======================================================================

print("\n" + "=" * 70)
print("PART B — ROW WINDOW TEST")
print("=" * 70)

row_tests = [
    ("WaterLevel_RollingMean_6h", "mean", range(4, 10)),
    ("WaterLevel_RollingMean_12h", "mean", range(9, 16)),
    ("WaterLevel_RollingMean_24h", "mean", range(20, 28)),
]

row_results = []

for original_col, operation, windows in row_tests:

    print(f"\n{original_col}")
    print("-" * 60)

    for w in windows:

        if operation == "mean":
            calculated = (
                diag[water_col]
                .rolling(
                    window=w,
                    min_periods=w
                )
                .mean()
            )

        rate = match_rate(
            original_col,
            calculated
        )

        row_results.append({
            "Feature": original_col,
            "Rows": w,
            "MatchRate": rate
        })

        print(
            f"Window = {w:2d} rows"
            f"   Match = {rate:6.2f}%"
        )


# ======================================================================
# PART C — TEST POSSIBLE SHIFTING
# ======================================================================

print("\n" + "=" * 70)
print("PART C — POSSIBLE FEATURE SHIFT TEST")
print("=" * 70)

shift_results = []

for window_name, original_col in features.items():

    calculated = (
        time_indexed[water_col]
        .rolling(
            window_name,
            closed="both",
            min_periods=1
        )
        .mean()
        .reset_index(drop=True)
    )

    original = diag[original_col]

    for shift in range(-3, 4):

        shifted = calculated.shift(shift)

        rate = match_rate(
            original_col,
            shifted
        )

        shift_results.append({
            "Feature": original_col,
            "Shift": shift,
            "MatchRate": rate
        })

        print(
            f"{original_col:35s} | "
            f"Shift={shift:+d} | "
            f"Match={rate:6.2f}%"
        )


# ======================================================================
# PART D — MAX / MIN WITH CLOSED OPTIONS
# ======================================================================

print("\n" + "=" * 70)
print("PART D — MAX/MIN BOUNDARY TEST")
print("=" * 70)

extreme_features = {
    "WaterLevel_RollingMax_24h": "max",
    "WaterLevel_RollingMin_24h": "min"
}

extreme_results = []

for original_col, operation in extreme_features.items():

    for closed in closed_options:

        if operation == "max":

            calculated = (
                time_indexed[water_col]
                .rolling(
                    "24h",
                    closed=closed,
                    min_periods=1
                )
                .max()
            )

        else:

            calculated = (
                time_indexed[water_col]
                .rolling(
                    "24h",
                    closed=closed,
                    min_periods=1
                )
                .min()
            )

        rate = match_rate(
            original_col,
            calculated
        )

        extreme_results.append({
            "Feature": original_col,
            "Operation": operation,
            "Closed": closed,
            "MatchRate": rate
        })

        print(
            f"{original_col:35s} | "
            f"closed={closed:7s} | "
            f"{rate:6.2f}%"
        )


# ======================================================================
# PART E — BEST CANDIDATE FOR EACH FEATURE
# ======================================================================

print("\n" + "=" * 70)
print("BEST TIME-BASED CANDIDATES")
print("=" * 70)

results_df = pd.DataFrame(results)

for feature in results_df["Feature"].unique():

    subset = (
        results_df[
            results_df["Feature"] == feature
        ]
        .sort_values(
            "MatchRate",
            ascending=False
        )
    )

    best = subset.iloc[0]

    print(
        f"\n{feature}"
    )
    print(
        f"Best window : {best['Window']}"
    )
    print(
        f"Closed      : {best['Closed']}"
    )
    print(
        f"Match rate  : {best['MatchRate']:.2f}%"
    )


# ======================================================================
# PART F — BEST ROW-BASED CANDIDATES
# ======================================================================

print("\n" + "=" * 70)
print("BEST ROW-BASED CANDIDATES")
print("=" * 70)

row_results_df = pd.DataFrame(row_results)

for feature in row_results_df["Feature"].unique():

    subset = (
        row_results_df[
            row_results_df["Feature"] == feature
        ]
        .sort_values(
            "MatchRate",
            ascending=False
        )
    )

    best = subset.iloc[0]

    print(
        f"\n{feature}"
    )

    print(
        f"Best rows   : {int(best['Rows'])}"
    )

    print(
        f"Match rate  : {best['MatchRate']:.2f}%"
    )


# ======================================================================
# PART G — BEST SHIFT CANDIDATES
# ======================================================================

print("\n" + "=" * 70)
print("BEST SHIFT CANDIDATES")
print("=" * 70)

shift_results_df = pd.DataFrame(shift_results)

for feature in shift_results_df["Feature"].unique():

    subset = (
        shift_results_df[
            shift_results_df["Feature"] == feature
        ]
        .sort_values(
            "MatchRate",
            ascending=False
        )
    )

    best = subset.iloc[0]

    print(
        f"\n{feature}"
    )

    print(
        f"Best shift  : {int(best['Shift']):+d}"
    )

    print(
        f"Match rate  : {best['MatchRate']:.2f}%"
    )


# ======================================================================
# PART H — EXACT EXAMPLE AGAIN
# ======================================================================

print("\n" + "=" * 70)
print("REFERENCE EXAMPLE — 2022-01-04 16:00")
print("=" * 70)

target_time = pd.Timestamp(
    "2022-01-04 16:00:00"
)

example = diag[
    diag[time_col] == target_time
]

if len(example) > 0:

    print(
        example[
            [
                time_col,
                water_col,
                "WaterLevel_RollingMean_6h",
                "WaterLevel_RollingMean_12h",
                "WaterLevel_RollingMean_24h",
                "WaterLevel_RollingMax_24h",
                "WaterLevel_RollingMin_24h"
            ]
        ]
        .to_string(index=False)
    )


# ======================================================================
# FINAL STATUS
# ======================================================================

print("\n" + "=" * 70)
print("STEP 4.4 COMPLETE")
print("=" * 70)

print("\nNO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")
print("NO MODEL WAS TRAINED.")

print("\nSend the COMPLETE output before proceeding.")

======================================================================
STEP 4.4 — ROLLING WINDOW FORENSIC VALIDATION
======================================================================

======================================================================
PART A — TIME-BASED WINDOW / CLOSED-BOUNDARY TEST
======================================================================
WaterLevel_RollingMean_6h           | 6h   | closed=right   |   0.00%
WaterLevel_RollingMean_6h           | 6h   | closed=left    |   0.00%
WaterLevel_RollingMean_6h           | 6h   | closed=both    |   0.00%
WaterLevel_RollingMean_6h           | 6h   | closed=neither |   0.00%
WaterLevel_RollingMean_12h          | 12h  | closed=right   |   0.00%
WaterLevel_RollingMean_12h          | 12h  | closed=left    |   0.00%
WaterLevel_RollingMean_12h          | 12h  | closed=both    |   0.00%
WaterLevel_RollingMean_12h          | 12h  | closed=neither |   0.00%
WaterLevel_RollingMean_24h          | 24h  | closed=right   |   0.00%
WaterLevel_RollingMean_24h          | 24h  | closed=left    |   0.00%
WaterLevel_RollingMean_24h          | 24h  | closed=both    |   0.00%
WaterLevel_RollingMean_24h          | 24h  | closed=neither |   0.00%

======================================================================
PART B — ROW WINDOW TEST
======================================================================

WaterLevel_RollingMean_6h
------------------------------------------------------------
Window =  4 rows   Match =  37.74%
Window =  5 rows   Match =  37.39%
Window =  6 rows   Match =  82.09%
Window =  7 rows   Match =  35.64%
Window =  8 rows   Match =  34.77%
Window =  9 rows   Match =  33.86%

WaterLevel_RollingMean_12h
------------------------------------------------------------
Window =  9 rows   Match =  31.74%
Window = 10 rows   Match =  31.48%
Window = 11 rows   Match =  31.35%
Window = 12 rows   Match =  72.86%
Window = 13 rows   Match =  30.35%
Window = 14 rows   Match =  29.74%
Window = 15 rows   Match =  29.20%

WaterLevel_RollingMean_24h
------------------------------------------------------------
Window = 20 rows   Match =  25.05%
Window = 21 rows   Match =  24.90%
Window = 22 rows   Match =  24.92%
Window = 23 rows   Match =  24.89%
Window = 24 rows   Match =  61.01%
Window = 25 rows   Match =  24.17%
Window = 26 rows   Match =  23.87%
Window = 27 rows   Match =  23.55%

======================================================================
PART C — POSSIBLE FEATURE SHIFT TEST
======================================================================
WaterLevel_RollingMean_6h           | Shift=-3 | Match= 34.81%
WaterLevel_RollingMean_6h           | Shift=-2 | Match= 35.79%
WaterLevel_RollingMean_6h           | Shift=-1 | Match= 37.25%
WaterLevel_RollingMean_6h           | Shift=+0 | Match= 39.31%
WaterLevel_RollingMean_6h           | Shift=+1 | Match= 36.38%
WaterLevel_RollingMean_6h           | Shift=+2 | Match= 35.36%
WaterLevel_RollingMean_6h           | Shift=+3 | Match= 34.36%
WaterLevel_RollingMean_12h          | Shift=-3 | Match= 31.11%
WaterLevel_RollingMean_12h          | Shift=-2 | Match= 31.76%
WaterLevel_RollingMean_12h          | Shift=-1 | Match= 32.64%
WaterLevel_RollingMean_12h          | Shift=+0 | Match= 34.03%
WaterLevel_RollingMean_12h          | Shift=+1 | Match= 32.16%
WaterLevel_RollingMean_12h          | Shift=+2 | Match= 31.46%
WaterLevel_RollingMean_12h          | Shift=+3 | Match= 30.84%
WaterLevel_RollingMean_24h          | Shift=-3 | Match= 25.95%
WaterLevel_RollingMean_24h          | Shift=-2 | Match= 26.48%
WaterLevel_RollingMean_24h          | Shift=-1 | Match= 27.31%
WaterLevel_RollingMean_24h          | Shift=+0 | Match= 28.14%
WaterLevel_RollingMean_24h          | Shift=+1 | Match= 26.92%
WaterLevel_RollingMean_24h          | Shift=+2 | Match= 26.43%
WaterLevel_RollingMean_24h          | Shift=+3 | Match= 26.01%

======================================================================
PART D — MAX/MIN BOUNDARY TEST
======================================================================
WaterLevel_RollingMax_24h           | closed=right   |   0.00%
WaterLevel_RollingMax_24h           | closed=left    |   0.00%
WaterLevel_RollingMax_24h           | closed=both    |   0.00%
WaterLevel_RollingMax_24h           | closed=neither |   0.00%
WaterLevel_RollingMin_24h           | closed=right   |   0.00%
WaterLevel_RollingMin_24h           | closed=left    |   0.00%
WaterLevel_RollingMin_24h           | closed=both    |   0.00%
WaterLevel_RollingMin_24h           | closed=neither |   0.00%

======================================================================
BEST TIME-BASED CANDIDATES
======================================================================

WaterLevel_RollingMean_6h
Best window : 6h
Closed      : right
Match rate  : 0.00%

WaterLevel_RollingMean_12h
Best window : 12h
Closed      : right
Match rate  : 0.00%

WaterLevel_RollingMean_24h
Best window : 24h
Closed      : right
Match rate  : 0.00%

======================================================================
BEST ROW-BASED CANDIDATES
======================================================================

WaterLevel_RollingMean_6h
Best rows   : 6
Match rate  : 82.09%

WaterLevel_RollingMean_12h
Best rows   : 12
Match rate  : 72.86%

WaterLevel_RollingMean_24h
Best rows   : 24
Match rate  : 61.01%

======================================================================
BEST SHIFT CANDIDATES
======================================================================

WaterLevel_RollingMean_6h
Best shift  : +0
Match rate  : 39.31%

WaterLevel_RollingMean_12h
Best shift  : +0
Match rate  : 34.03%

WaterLevel_RollingMean_24h
Best shift  : +0
Match rate  : 28.14%

======================================================================
REFERENCE EXAMPLE — 2022-01-04 16:00
======================================================================
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  WaterLevel_RollingMean_12h  WaterLevel_RollingMean_24h  WaterLevel_RollingMax_24h  WaterLevel_RollingMin_24h
  2022-01-04 16:00:00                0.452                   0.418591                    0.381537                    0.317405                      0.452                      0.221

======================================================================
STEP 4.4 COMPLETE
======================================================================

NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.
NO MODEL WAS TRAINED.

Send the COMPLETE output before proceeding.

In [15]:
# ======================================================================
# STEP 4.5 — CORRECTED ROLLING VALIDATION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.5 — CORRECTED ROLLING VALIDATION")
print("=" * 70)

# ----------------------------------------------------------------------
# SOURCE COLUMNS
# ----------------------------------------------------------------------

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"

diag = df.copy()

diag[time_col] = pd.to_datetime(
    diag[time_col],
    errors="coerce"
)

diag = (
    diag
    .sort_values(time_col)
    .reset_index(drop=True)
)

# ======================================================================
# PART A — CORRECT TIME-BASED VALIDATION
# ======================================================================

print("\n" + "=" * 70)
print("PART A — CORRECT TIME-BASED VALIDATION")
print("=" * 70)

time_indexed = diag.set_index(time_col)

time_tests = [
    ("WaterLevel_RollingMean_6h", "6h"),
    ("WaterLevel_RollingMean_12h", "12h"),
    ("WaterLevel_RollingMean_24h", "24h"),
    ("WaterLevel_RollingMax_24h", "24h"),
    ("WaterLevel_RollingMin_24h", "24h")
]

for original_col, window in time_tests:

    print(f"\n{original_col}")
    print("-" * 60)

    for closed in ["right", "left", "both", "neither"]:

        if "Mean" in original_col:

            calculated = (
                time_indexed[water_col]
                .rolling(
                    window,
                    closed=closed,
                    min_periods=1
                )
                .mean()
                .to_numpy()
            )

        elif "Max" in original_col:

            calculated = (
                time_indexed[water_col]
                .rolling(
                    window,
                    closed=closed,
                    min_periods=1
                )
                .max()
                .to_numpy()
            )

        else:

            calculated = (
                time_indexed[water_col]
                .rolling(
                    window,
                    closed=closed,
                    min_periods=1
                )
                .min()
                .to_numpy()
            )

        original = diag[original_col].to_numpy()

        valid = (
            ~np.isnan(original)
            &
            ~np.isnan(calculated)
        )

        diff = np.abs(
            original[valid]
            -
            calculated[valid]
        )

        matching = np.sum(diff <= 1e-6)
        checked = len(diff)

        rate = (
            matching / checked * 100
            if checked > 0
            else 0
        )

        print(
            f"closed={closed:7s} | "
            f"Checked={checked:4d} | "
            f"Matching={matching:4d} | "
            f"Match={rate:6.2f}%"
        )


# ======================================================================
# PART B — ROW-BASED VALIDATION WITH DIFFERENT WINDOWS
# ======================================================================

print("\n" + "=" * 70)
print("PART B — ROW-BASED WINDOW VALIDATION")
print("=" * 70)

row_tests = {
    "WaterLevel_RollingMean_6h": range(4, 9),
    "WaterLevel_RollingMean_12h": range(10, 15),
    "WaterLevel_RollingMean_24h": range(22, 27),
    "WaterLevel_RollingMax_24h": range(22, 27),
    "WaterLevel_RollingMin_24h": range(22, 27)
}

for original_col, windows in row_tests.items():

    print(f"\n{original_col}")
    print("-" * 60)

    for window in windows:

        if "Mean" in original_col:

            calculated = (
                diag[water_col]
                .rolling(
                    window=window,
                    min_periods=window
                )
                .mean()
                .to_numpy()
            )

        elif "Max" in original_col:

            calculated = (
                diag[water_col]
                .rolling(
                    window=window,
                    min_periods=window
                )
                .max()
                .to_numpy()
            )

        else:

            calculated = (
                diag[water_col]
                .rolling(
                    window=window,
                    min_periods=window
                )
                .min()
                .to_numpy()
            )

        original = diag[original_col].to_numpy()

        valid = (
            ~np.isnan(original)
            &
            ~np.isnan(calculated)
        )

        diff = np.abs(
            original[valid]
            -
            calculated[valid]
        )

        matching = np.sum(diff <= 1e-6)
        checked = len(diff)

        rate = (
            matching / checked * 100
            if checked > 0
            else 0
        )

        print(
            f"Window={window:2d} rows | "
            f"Checked={checked:4d} | "
            f"Matching={matching:4d} | "
            f"Match={rate:6.2f}%"
        )


# ======================================================================
# PART C — INVESTIGATE THE 82% MATCHING CASE
# ======================================================================

print("\n" + "=" * 70)
print("PART C — 6-ROW ROLLING DETAILED INVESTIGATION")
print("=" * 70)

recreated_6 = (
    diag[water_col]
    .rolling(
        window=6,
        min_periods=6
    )
    .mean()
)

original_6 = diag["WaterLevel_RollingMean_6h"]

valid = (
    original_6.notna()
    &
    recreated_6.notna()
)

difference = np.abs(
    original_6 - recreated_6
)

match = (
    valid &
    (difference <= 1e-6)
)

mismatch = (
    valid &
    (difference > 1e-6)
)

print("\n6-row rolling result:")
print("Checked     :", valid.sum())
print("Matching    :", match.sum())
print("Mismatching :", mismatch.sum())
print(
    f"Match rate  : "
    f"{match.sum() / valid.sum() * 100:.2f}%"
)

# ----------------------------------------------------------------------
# Show first matching examples
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST 10 MATCHING EXAMPLES")
print("-" * 70)

match_cols = [
    time_col,
    water_col,
    "WaterLevel_RollingMean_6h"
]

match_display = diag.loc[
    match,
    match_cols
].copy()

match_display["Recreated"] = (
    recreated_6[match]
)

print(
    match_display
    .head(10)
    .to_string(index=False)
)

# ----------------------------------------------------------------------
# Show first mismatching examples
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST 20 MISMATCHING EXAMPLES")
print("-" * 70)

mismatch_display = diag.loc[
    mismatch,
    [
        time_col,
        water_col,
        "WaterLevel_RollingMean_6h"
    ]
].copy()

mismatch_display["Recreated"] = (
    recreated_6[mismatch]
)

mismatch_display["Difference"] = (
    difference[mismatch]
)

print(
    mismatch_display
    .head(20)
    .to_string(index=False)
)


# ======================================================================
# PART D — CHECK IF MISMATCHES FOLLOW LARGE TIME GAPS
# ======================================================================

print("\n" + "=" * 70)
print("PART D — GAP ANALYSIS OF 6-ROW MISMATCHES")
print("=" * 70)

diag["Diagnostic_Gap"] = (
    diag[time_col].diff()
)

mismatch_indices = np.where(
    mismatch.to_numpy()
)[0]

gap_at_mismatch = (
    diag.loc[
        mismatch_indices,
        "Diagnostic_Gap"
    ]
)

print(
    "\nGap distribution among mismatching rows:"
)

print(
    gap_at_mismatch
    .value_counts()
    .head(20)
)

non_one_hour = (
    gap_at_mismatch != pd.Timedelta(hours=1)
)

print(
    "\nMismatches after non-1h gap:",
    non_one_hour.sum()
)

print(
    "Total mismatches:",
    len(gap_at_mismatch)
)

print(
    f"Percentage explained directly by "
    f"non-1h gap: "
    f"{non_one_hour.mean() * 100:.2f}%"
)


# ======================================================================
# STEP 4.5 COMPLETE
# ======================================================================

print("\n" + "=" * 70)
print("STEP 4.5 COMPLETE")
print("=" * 70)

print("\nNO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")
print("NO MODEL WAS TRAINED.")

print("\nSend the COMPLETE output.")

======================================================================
STEP 4.5 — CORRECTED ROLLING VALIDATION
======================================================================

======================================================================
PART A — CORRECT TIME-BASED VALIDATION
======================================================================

WaterLevel_RollingMean_6h
------------------------------------------------------------
closed=right   | Checked=7309 | Matching=6057 | Match= 82.87%
closed=left    | Checked=7186 | Matching=2752 | Match= 38.30%
closed=both    | Checked=7309 | Matching=2873 | Match= 39.31%
closed=neither | Checked=7153 | Matching=2768 | Match= 38.70%

WaterLevel_RollingMean_12h
------------------------------------------------------------
closed=right   | Checked=7309 | Matching=5386 | Match= 73.69%
closed=left    | Checked=7231 | Matching=2407 | Match= 33.29%
closed=both    | Checked=7309 | Matching=2487 | Match= 34.03%
closed=neither | Checked=7222 | Matching=2397 | Match= 33.19%

WaterLevel_RollingMean_24h
------------------------------------------------------------
closed=right   | Checked=7309 | Matching=4587 | Match= 62.76%
closed=left    | Checked=7241 | Matching=2056 | Match= 28.39%
closed=both    | Checked=7309 | Matching=2057 | Match= 28.14%
closed=neither | Checked=7241 | Matching=1980 | Match= 27.34%

WaterLevel_RollingMax_24h
------------------------------------------------------------
closed=right   | Checked=7309 | Matching=6809 | Match= 93.16%
closed=left    | Checked=7241 | Matching=5961 | Match= 82.32%
closed=both    | Checked=7309 | Matching=6390 | Match= 87.43%
closed=neither | Checked=7241 | Matching=6377 | Match= 88.07%

WaterLevel_RollingMin_24h
------------------------------------------------------------
closed=right   | Checked=7309 | Matching=6215 | Match= 85.03%
closed=left    | Checked=7241 | Matching=5316 | Match= 73.42%
closed=both    | Checked=7309 | Matching=5993 | Match= 81.99%
closed=neither | Checked=7241 | Matching=5530 | Match= 76.37%

======================================================================
PART B — ROW-BASED WINDOW VALIDATION
======================================================================

WaterLevel_RollingMean_6h
------------------------------------------------------------
Window= 4 rows | Checked=7306 | Matching=2757 | Match= 37.74%
Window= 5 rows | Checked=7305 | Matching=2731 | Match= 37.39%
Window= 6 rows | Checked=7304 | Matching=5996 | Match= 82.09%
Window= 7 rows | Checked=7303 | Matching=2603 | Match= 35.64%
Window= 8 rows | Checked=7302 | Matching=2539 | Match= 34.77%

WaterLevel_RollingMean_12h
------------------------------------------------------------
Window=10 rows | Checked=7300 | Matching=2298 | Match= 31.48%
Window=11 rows | Checked=7299 | Matching=2288 | Match= 31.35%
Window=12 rows | Checked=7298 | Matching=5317 | Match= 72.86%
Window=13 rows | Checked=7297 | Matching=2215 | Match= 30.35%
Window=14 rows | Checked=7296 | Matching=2170 | Match= 29.74%

WaterLevel_RollingMean_24h
------------------------------------------------------------
Window=22 rows | Checked=7288 | Matching=1816 | Match= 24.92%
Window=23 rows | Checked=7287 | Matching=1814 | Match= 24.89%
Window=24 rows | Checked=7286 | Matching=4445 | Match= 61.01%
Window=25 rows | Checked=7285 | Matching=1761 | Match= 24.17%
Window=26 rows | Checked=7284 | Matching=1739 | Match= 23.87%

WaterLevel_RollingMax_24h
------------------------------------------------------------
Window=22 rows | Checked=7288 | Matching=5724 | Match= 78.54%
Window=23 rows | Checked=7287 | Matching=5811 | Match= 79.74%
Window=24 rows | Checked=7286 | Matching=6081 | Match= 83.46%
Window=25 rows | Checked=7285 | Matching=5695 | Match= 78.17%
Window=26 rows | Checked=7284 | Matching=5574 | Match= 76.52%

WaterLevel_RollingMin_24h
------------------------------------------------------------
Window=22 rows | Checked=7288 | Matching=5645 | Match= 77.46%
Window=23 rows | Checked=7287 | Matching=5688 | Match= 78.06%
Window=24 rows | Checked=7286 | Matching=5763 | Match= 79.10%
Window=25 rows | Checked=7285 | Matching=5560 | Match= 76.32%
Window=26 rows | Checked=7284 | Matching=5431 | Match= 74.56%

======================================================================
PART C — 6-ROW ROLLING DETAILED INVESTIGATION
======================================================================

6-row rolling result:
Checked     : 7304
Matching    : 5996
Mismatching : 1308
Match rate  : 82.09%

----------------------------------------------------------------------
FIRST 10 MATCHING EXAMPLES
----------------------------------------------------------------------
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  Recreated
  2022-01-09 05:00:00               0.5290                   0.531083   0.531083
  2022-01-09 06:00:00               0.5225                   0.530833   0.530833
  2022-01-09 07:00:00               0.5160                   0.528333   0.528333
  2022-01-09 08:00:00               0.5150                   0.524667   0.524667
  2022-01-09 09:00:00               0.5155                   0.521583   0.521583
  2022-01-09 10:00:00               0.5160                   0.519000   0.519000
  2022-01-09 11:00:00               0.5210                   0.517667   0.517667
  2022-01-09 12:00:00               0.5260                   0.518250   0.518250
  2022-01-09 13:00:00               0.5275                   0.520167   0.520167
  2022-01-09 14:00:00               0.5290                   0.522500   0.522500

----------------------------------------------------------------------
FIRST 20 MISMATCHING EXAMPLES
----------------------------------------------------------------------
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  Recreated  Difference
  2022-01-04 15:00:00             0.438636                   0.405227   0.357015    0.048212
  2022-01-04 16:00:00             0.452000                   0.418591   0.385182    0.033409
  2022-01-04 17:00:00             0.525000                   0.441894   0.421848    0.020045
  2022-01-09 00:00:00             0.524000                   0.731667   0.453894    0.277773
  2022-01-09 01:00:00             0.531000                   0.689667   0.480424    0.209242
  2022-01-09 02:00:00             0.537000                   0.647500   0.501273    0.146227
  2022-01-09 03:00:00             0.534000                   0.607500   0.517167    0.090333
  2022-01-09 04:00:00             0.531500                   0.569083   0.530417    0.038667
  2022-01-10 09:00:00             0.473000                   0.480750   0.485417    0.004667
  2022-01-10 10:00:00             0.482000                   0.480083   0.483528    0.003444
  2022-01-10 12:00:00             0.474000                   0.477833   0.480917    0.003083
  2022-01-10 21:00:00             1.222000                   1.173733   0.603583    0.570150
  2022-01-10 22:00:00             1.221000                   1.223000   0.726167    0.496833
  2022-01-11 00:00:00             1.247000                   1.226500   0.853167    0.373333
  2022-01-11 03:00:00             1.248000                   1.238500   0.982333    0.256167
  2022-01-11 04:00:00             1.244000                   1.242333   1.109333    0.133000
  2022-01-11 06:00:00             1.283000                   1.251833   1.244167    0.007667
  2022-01-11 07:00:00             1.280000                   1.257500   1.253833    0.003667
  2022-01-11 08:00:00             1.275000                   1.262167   1.262833    0.000667
  2022-01-11 09:00:00             1.273000                   1.266333   1.267167    0.000833

======================================================================
PART D — GAP ANALYSIS OF 6-ROW MISMATCHES
======================================================================

Gap distribution among mismatching rows:
Diagnostic_Gap
0 days 01:00:00     765
0 days 02:00:00     250
0 days 03:00:00     127
0 days 04:00:00      23
0 days 06:00:00      21
0 days 05:00:00      19
0 days 07:00:00       9
0 days 09:00:00       8
22 days 07:00:00      7
0 days 08:00:00       7
0 days 12:00:00       6
5 days 07:00:00       4
21 days 07:00:00      4
2 days 07:00:00       4
19 days 07:00:00      4
24 days 07:00:00      4
0 days 11:00:00       3
0 days 18:00:00       3
23 days 14:00:00      2
21 days 09:00:00      2
Name: count, dtype: int64

Mismatches after non-1h gap: 543
Total mismatches: 1308
Percentage explained directly by non-1h gap: 41.51%

======================================================================
STEP 4.5 COMPLETE
======================================================================

NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.
NO MODEL WAS TRAINED.

Send the COMPLETE output.

In [16]:
# ======================================================================
# STEP 4.6 — 1-HOUR-GAP MISMATCH FORENSIC INVESTIGATION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.6 — 1-HOUR-GAP MISMATCH FORENSIC INVESTIGATION")
print("=" * 70)

# ----------------------------------------------------------------------
# SAFETY CHECK
# ----------------------------------------------------------------------

df_check = df.copy()

df_check["Data Acquisition Time"] = pd.to_datetime(
    df_check["Data Acquisition Time"]
)

df_check = df_check.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"
feature_col = "WaterLevel_RollingMean_6h"

# ----------------------------------------------------------------------
# RECREATE 6-ROW ROLLING VALUE FOR DIAGNOSTIC PURPOSE ONLY
# ----------------------------------------------------------------------

df_check["Recreated_6Row"] = (
    df_check[water_col]
    .rolling(window=6, min_periods=6)
    .mean()
)

df_check["Difference"] = (
    df_check[feature_col] -
    df_check["Recreated_6Row"]
).abs()

# ----------------------------------------------------------------------
# ACTUAL PREVIOUS TIMESTAMP GAP
# ----------------------------------------------------------------------

df_check["Previous_Time"] = df_check[time_col].shift(1)

df_check["Diagnostic_Gap"] = (
    df_check[time_col] -
    df_check["Previous_Time"]
)

# ----------------------------------------------------------------------
# MISMATCH MASK
# ----------------------------------------------------------------------

tolerance = 1e-6

mismatch_mask = (
    df_check["Recreated_6Row"].notna() &
    df_check[feature_col].notna() &
    (
        df_check["Difference"] > tolerance
    )
)

one_hour_mismatch = df_check[
    mismatch_mask &
    (df_check["Diagnostic_Gap"] == pd.Timedelta(hours=1))
].copy()

print("\n" + "-" * 70)
print("1-HOUR-GAP MISMATCH SUMMARY")
print("-" * 70)

print("Total 1-hour-gap mismatches :", len(one_hour_mismatch))

print(
    "Mean absolute difference     :",
    one_hour_mismatch["Difference"].mean()
)

print(
    "Maximum absolute difference  :",
    one_hour_mismatch["Difference"].max()
)

print(
    "Median absolute difference   :",
    one_hour_mismatch["Difference"].median()
)

# ----------------------------------------------------------------------
# DUPLICATE TIMESTAMP CHECK
# ----------------------------------------------------------------------

duplicate_times = (
    df_check[time_col]
    .duplicated(keep=False)
)

print("\n" + "-" * 70)
print("DUPLICATE TIMESTAMP CHECK")
print("-" * 70)

print(
    "Total rows involved in duplicate timestamps:",
    duplicate_times.sum()
)

print(
    "Unique duplicate timestamps:",
    df_check.loc[
        duplicate_times,
        time_col
    ].nunique()
)

# ----------------------------------------------------------------------
# NaN CHECK
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("WATER LEVEL NaN CHECK")
print("-" * 70)

print(
    "Total NaN water-level rows:",
    df_check[water_col].isna().sum()
)

print(
    "1-hour-gap mismatches having NaN current value:",
    one_hour_mismatch[water_col].isna().sum()
)

# ----------------------------------------------------------------------
# INSPECT FIRST 20 ONE-HOUR MISMATCHES
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST 20 ONE-HOUR-GAP MISMATCHES")
print("-" * 70)

cols = [
    time_col,
    water_col,
    feature_col,
    "Recreated_6Row",
    "Difference",
    "Diagnostic_Gap"
]

print(
    one_hour_mismatch[cols]
    .head(20)
    .to_string(index=False)
)

# ----------------------------------------------------------------------
# FULL 6-ROW TIMESTAMP WINDOW FOR FIRST 10 MISMATCHES
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("DETAILED 6-ROW HISTORY FOR FIRST 10 ONE-HOUR MISMATCHES")
print("-" * 70)

for idx in one_hour_mismatch.index[:10]:

    print("\n" + "=" * 70)
    print("Mismatch row index:", idx)
    print("Current timestamp  :", df_check.loc[idx, time_col])
    print("Stored feature     :", df_check.loc[idx, feature_col])
    print("6-row recreation   :", df_check.loc[idx, "Recreated_6Row"])
    print("Difference          :", df_check.loc[idx, "Difference"])

    start_idx = max(0, idx - 5)

    history = df_check.loc[
        start_idx:idx,
        [
            time_col,
            water_col
        ]
    ].copy()

    history["Gap_From_Previous"] = (
        history[time_col].diff()
    )

    print("\n6-row history:")
    print(history.to_string(index=True))

    elapsed = (
        history[time_col].iloc[-1]
        - history[time_col].iloc[0]
    )

    print("\nActual elapsed duration across 6 rows:", elapsed)

print("\n" + "=" * 70)
print("STEP 4.6 DIAGNOSTIC COMPLETE")
print("=" * 70)

print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.6 — 1-HOUR-GAP MISMATCH FORENSIC INVESTIGATION
======================================================================

----------------------------------------------------------------------
1-HOUR-GAP MISMATCH SUMMARY
----------------------------------------------------------------------
Total 1-hour-gap mismatches : 765
Mean absolute difference     : 1.5275444942892984
Maximum absolute difference  : 31.771500000000003
Median absolute difference   : 0.03333333333333144

----------------------------------------------------------------------
DUPLICATE TIMESTAMP CHECK
----------------------------------------------------------------------
Total rows involved in duplicate timestamps: 0
Unique duplicate timestamps: 0

----------------------------------------------------------------------
WATER LEVEL NaN CHECK
----------------------------------------------------------------------
Total NaN water-level rows: 0
1-hour-gap mismatches having NaN current value: 0

----------------------------------------------------------------------
FIRST 20 ONE-HOUR-GAP MISMATCHES
----------------------------------------------------------------------
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  Recreated_6Row  Difference  Diagnostic_Gap
  2022-01-04 16:00:00               0.4520                   0.418591        0.385182    0.033409 0 days 01:00:00
  2022-01-04 17:00:00               0.5250                   0.441894        0.421848    0.020045 0 days 01:00:00
  2022-01-09 01:00:00               0.5310                   0.689667        0.480424    0.209242 0 days 01:00:00
  2022-01-09 02:00:00               0.5370                   0.647500        0.501273    0.146227 0 days 01:00:00
  2022-01-09 03:00:00               0.5340                   0.607500        0.517167    0.090333 0 days 01:00:00
  2022-01-09 04:00:00               0.5315                   0.569083        0.530417    0.038667 0 days 01:00:00
  2022-01-10 10:00:00               0.4820                   0.480083        0.483528    0.003444 0 days 01:00:00
  2022-01-10 22:00:00               1.2210                   1.223000        0.726167    0.496833 0 days 01:00:00
  2022-01-11 04:00:00               1.2440                   1.242333        1.109333    0.133000 0 days 01:00:00
  2022-01-11 07:00:00               1.2800                   1.257500        1.253833    0.003667 0 days 01:00:00
  2022-01-11 08:00:00               1.2750                   1.262167        1.262833    0.000667 0 days 01:00:00
  2022-01-11 09:00:00               1.2730                   1.266333        1.267167    0.000833 0 days 01:00:00
  2022-01-11 10:00:00               1.2710                   1.270833        1.271000    0.000167 0 days 01:00:00
  2022-01-11 16:00:00               1.2500                   1.256667        1.262333    0.005667 0 days 01:00:00
  2022-01-11 19:00:00               1.2420                   1.248500        1.252667    0.004167 0 days 01:00:00
  2022-01-11 20:00:00               1.2390                   1.246000        1.248167    0.002167 0 days 01:00:00
  2022-01-11 21:00:00               1.2390                   1.243333        1.244833    0.001500 0 days 01:00:00
  2022-01-12 03:00:00               1.2880                   1.273333        1.264833    0.008500 0 days 01:00:00
  2022-02-04 01:00:00               0.5500                   0.337167        1.049667    0.712500 0 days 01:00:00
  2022-02-04 02:00:00               0.5420                   0.385000        0.925333    0.540333 0 days 01:00:00

----------------------------------------------------------------------
DETAILED 6-ROW HISTORY FOR FIRST 10 ONE-HOUR MISMATCHES
----------------------------------------------------------------------

======================================================================
Mismatch row index: 6
Current timestamp  : 2022-01-04 16:00:00
Stored feature     : 0.418590909090909
6-row recreation   : 0.38518181818181824
Difference          : 0.03340909090909078

6-row history:
  Data Acquisition Time  Current_Water_Level Gap_From_Previous
1   2022-01-04 05:00:00             0.305000               NaT
2   2022-01-04 07:00:00             0.331727   0 days 02:00:00
3   2022-01-04 10:00:00             0.371818   0 days 03:00:00
4   2022-01-04 13:00:00             0.411909   0 days 03:00:00
5   2022-01-04 15:00:00             0.438636   0 days 02:00:00
6   2022-01-04 16:00:00             0.452000   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 11:00:00

======================================================================
Mismatch row index: 7
Current timestamp  : 2022-01-04 17:00:00
Stored feature     : 0.4418939393939394
6-row recreation   : 0.42184848484848486
Difference          : 0.020045454545454533

6-row history:
  Data Acquisition Time  Current_Water_Level Gap_From_Previous
2   2022-01-04 07:00:00             0.331727               NaT
3   2022-01-04 10:00:00             0.371818   0 days 03:00:00
4   2022-01-04 13:00:00             0.411909   0 days 03:00:00
5   2022-01-04 15:00:00             0.438636   0 days 02:00:00
6   2022-01-04 16:00:00             0.452000   0 days 01:00:00
7   2022-01-04 17:00:00             0.525000   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 10:00:00

======================================================================
Mismatch row index: 9
Current timestamp  : 2022-01-09 01:00:00
Stored feature     : 0.6896666666666667
6-row recreation   : 0.4804242424242425
Difference          : 0.20924242424242417

6-row history:
  Data Acquisition Time  Current_Water_Level Gap_From_Previous
4   2022-01-04 13:00:00             0.411909               NaT
5   2022-01-04 15:00:00             0.438636   0 days 02:00:00
6   2022-01-04 16:00:00             0.452000   0 days 01:00:00
7   2022-01-04 17:00:00             0.525000   0 days 01:00:00
8   2022-01-09 00:00:00             0.524000   4 days 07:00:00
9   2022-01-09 01:00:00             0.531000   0 days 01:00:00

Actual elapsed duration across 6 rows: 4 days 12:00:00

======================================================================
Mismatch row index: 10
Current timestamp  : 2022-01-09 02:00:00
Stored feature     : 0.6475
6-row recreation   : 0.5012727272727273
Difference          : 0.14622727272727265

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
5    2022-01-04 15:00:00             0.438636               NaT
6    2022-01-04 16:00:00             0.452000   0 days 01:00:00
7    2022-01-04 17:00:00             0.525000   0 days 01:00:00
8    2022-01-09 00:00:00             0.524000   4 days 07:00:00
9    2022-01-09 01:00:00             0.531000   0 days 01:00:00
10   2022-01-09 02:00:00             0.537000   0 days 01:00:00

Actual elapsed duration across 6 rows: 4 days 11:00:00

======================================================================
Mismatch row index: 11
Current timestamp  : 2022-01-09 03:00:00
Stored feature     : 0.6075
6-row recreation   : 0.5171666666666667
Difference          : 0.09033333333333338

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
6    2022-01-04 16:00:00                0.452               NaT
7    2022-01-04 17:00:00                0.525   0 days 01:00:00
8    2022-01-09 00:00:00                0.524   4 days 07:00:00
9    2022-01-09 01:00:00                0.531   0 days 01:00:00
10   2022-01-09 02:00:00                0.537   0 days 01:00:00
11   2022-01-09 03:00:00                0.534   0 days 01:00:00

Actual elapsed duration across 6 rows: 4 days 11:00:00

======================================================================
Mismatch row index: 12
Current timestamp  : 2022-01-09 04:00:00
Stored feature     : 0.5690833333333334
6-row recreation   : 0.5304166666666666
Difference          : 0.03866666666666674

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
7    2022-01-04 17:00:00               0.5250               NaT
8    2022-01-09 00:00:00               0.5240   4 days 07:00:00
9    2022-01-09 01:00:00               0.5310   0 days 01:00:00
10   2022-01-09 02:00:00               0.5370   0 days 01:00:00
11   2022-01-09 03:00:00               0.5340   0 days 01:00:00
12   2022-01-09 04:00:00               0.5315   0 days 01:00:00

Actual elapsed duration across 6 rows: 4 days 11:00:00

======================================================================
Mismatch row index: 40
Current timestamp  : 2022-01-10 10:00:00
Stored feature     : 0.4800833333333333
6-row recreation   : 0.4835277777777778
Difference          : 0.003444444444444472

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
35   2022-01-10 03:00:00             0.489667               NaT
36   2022-01-10 04:00:00             0.486000   0 days 01:00:00
37   2022-01-10 05:00:00             0.485500   0 days 01:00:00
38   2022-01-10 06:00:00             0.485000   0 days 01:00:00
39   2022-01-10 09:00:00             0.473000   0 days 03:00:00
40   2022-01-10 10:00:00             0.482000   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 07:00:00

======================================================================
Mismatch row index: 43
Current timestamp  : 2022-01-10 22:00:00
Stored feature     : 1.223
6-row recreation   : 0.7261666666666665
Difference          : 0.49683333333333357

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
38   2022-01-10 06:00:00                0.485               NaT
39   2022-01-10 09:00:00                0.473   0 days 03:00:00
40   2022-01-10 10:00:00                0.482   0 days 01:00:00
41   2022-01-10 12:00:00                0.474   0 days 02:00:00
42   2022-01-10 21:00:00                1.222   0 days 09:00:00
43   2022-01-10 22:00:00                1.221   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 16:00:00

======================================================================
Mismatch row index: 46
Current timestamp  : 2022-01-11 04:00:00
Stored feature     : 1.2423333333333335
6-row recreation   : 1.1093333333333333
Difference          : 0.13300000000000023

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
41   2022-01-10 12:00:00                0.474               NaT
42   2022-01-10 21:00:00                1.222   0 days 09:00:00
43   2022-01-10 22:00:00                1.221   0 days 01:00:00
44   2022-01-11 00:00:00                1.247   0 days 02:00:00
45   2022-01-11 03:00:00                1.248   0 days 03:00:00
46   2022-01-11 04:00:00                1.244   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 16:00:00

======================================================================
Mismatch row index: 48
Current timestamp  : 2022-01-11 07:00:00
Stored feature     : 1.2575
6-row recreation   : 1.2538333333333334
Difference          : 0.003666666666666707

6-row history:
   Data Acquisition Time  Current_Water_Level Gap_From_Previous
43   2022-01-10 22:00:00                1.221               NaT
44   2022-01-11 00:00:00                1.247   0 days 02:00:00
45   2022-01-11 03:00:00                1.248   0 days 03:00:00
46   2022-01-11 04:00:00                1.244   0 days 01:00:00
47   2022-01-11 06:00:00                1.283   0 days 02:00:00
48   2022-01-11 07:00:00                1.280   0 days 01:00:00

Actual elapsed duration across 6 rows: 0 days 09:00:00

======================================================================
STEP 4.6 DIAGNOSTIC COMPLETE
======================================================================
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [17]:
# ======================================================================
# STEP 4.7 — DIRECT TIME-BASED ROLLING RECONSTRUCTION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.7 — DIRECT TIME-BASED ROLLING RECONSTRUCTION")
print("=" * 70)

# ----------------------------------------------------------------------
# SAFETY: WORK ON COPY ONLY
# ----------------------------------------------------------------------

df_roll = df.copy()

df_roll["Data Acquisition Time"] = pd.to_datetime(
    df_roll["Data Acquisition Time"]
)

df_roll = (
    df_roll
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"

# ----------------------------------------------------------------------
# TIME-INDEXED RECONSTRUCTION
# ----------------------------------------------------------------------

df_time = (
    df_roll[
        [time_col, water_col]
    ]
    .set_index(time_col)
)

recreated = (
    df_time[water_col]
    .rolling(
        "6h",
        closed="right"
    )
    .mean()
)

# ----------------------------------------------------------------------
# ALIGN BACK TO ORIGINAL SORTED DATA
# ----------------------------------------------------------------------

df_roll["Recreated_TimeBased_6h_Right"] = (
    recreated.to_numpy()
)

feature_col = "WaterLevel_RollingMean_6h"

# ----------------------------------------------------------------------
# DIFFERENCE
# ----------------------------------------------------------------------

df_roll["Difference"] = (
    df_roll[feature_col]
    -
    df_roll["Recreated_TimeBased_6h_Right"]
).abs()

# ----------------------------------------------------------------------
# VALIDATION
# ----------------------------------------------------------------------

tolerance = 1e-6

valid_mask = (
    df_roll[feature_col].notna()
    &
    df_roll["Recreated_TimeBased_6h_Right"].notna()
)

matching_mask = (
    valid_mask
    &
    (
        df_roll["Difference"] <= tolerance
    )
)

mismatching_mask = (
    valid_mask
    &
    (
        df_roll["Difference"] > tolerance
    )
)

checked = valid_mask.sum()
matching = matching_mask.sum()
mismatching = mismatching_mask.sum()

match_rate = (
    matching / checked * 100
    if checked > 0
    else 0
)

print("\n" + "-" * 70)
print("TIME-BASED 6H ROLLING VALIDATION")
print("-" * 70)

print("Configuration : window='6h', closed='right'")
print("Checked       :", checked)
print("Matching      :", matching)
print("Mismatching   :", mismatching)
print(f"Match rate    : {match_rate:.4f}%")

# ----------------------------------------------------------------------
# ERROR STATISTICS
# ----------------------------------------------------------------------

if mismatching > 0:

    mismatch_values = (
        df_roll.loc[
            mismatching_mask,
            "Difference"
        ]
    )

    print("\n" + "-" * 70)
    print("MISMATCH ERROR STATISTICS")
    print("-" * 70)

    print(
        "Mean absolute difference   :",
        mismatch_values.mean()
    )

    print(
        "Median absolute difference :",
        mismatch_values.median()
    )

    print(
        "Maximum absolute difference:",
        mismatch_values.max()
    )

# ----------------------------------------------------------------------
# FIRST MATCHING EXAMPLES
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST 10 MATCHING EXAMPLES")
print("-" * 70)

matching_examples = df_roll.loc[
    matching_mask,
    [
        time_col,
        feature_col,
        "Recreated_TimeBased_6h_Right",
        "Difference"
    ]
].head(10)

print(
    matching_examples.to_string(index=False)
)

# ----------------------------------------------------------------------
# FIRST MISMATCHING EXAMPLES
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST 20 MISMATCHING EXAMPLES")
print("-" * 70)

mismatch_examples = df_roll.loc[
    mismatching_mask,
    [
        time_col,
        feature_col,
        "Recreated_TimeBased_6h_Right",
        "Difference"
    ]
].head(20)

print(
    mismatch_examples.to_string(index=False)
)

# ----------------------------------------------------------------------
# FINAL SAFETY
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 4.7 COMPLETE")
print("=" * 70)

print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.7 — DIRECT TIME-BASED ROLLING RECONSTRUCTION
======================================================================

----------------------------------------------------------------------
TIME-BASED 6H ROLLING VALIDATION
----------------------------------------------------------------------
Configuration : window='6h', closed='right'
Checked       : 7309
Matching      : 6057
Mismatching   : 1252
Match rate    : 82.8704%

----------------------------------------------------------------------
MISMATCH ERROR STATISTICS
----------------------------------------------------------------------
Mean absolute difference   : 0.441187489457498
Median absolute difference : 0.01528333333333265
Maximum absolute difference: 36.086

----------------------------------------------------------------------
FIRST 10 MATCHING EXAMPLES
----------------------------------------------------------------------
Data Acquisition Time  WaterLevel_RollingMean_6h  Recreated_TimeBased_6h_Right   Difference
  2022-01-09 05:00:00                   0.531083                      0.531083 1.110223e-16
  2022-01-09 06:00:00                   0.530833                      0.530833 0.000000e+00
  2022-01-09 07:00:00                   0.528333                      0.528333 1.110223e-16
  2022-01-09 08:00:00                   0.524667                      0.524667 1.110223e-16
  2022-01-09 09:00:00                   0.521583                      0.521583 0.000000e+00
  2022-01-09 10:00:00                   0.519000                      0.519000 0.000000e+00
  2022-01-09 11:00:00                   0.517667                      0.517667 1.110223e-16
  2022-01-09 12:00:00                   0.518250                      0.518250 0.000000e+00
  2022-01-09 13:00:00                   0.520167                      0.520167 1.110223e-16
  2022-01-09 14:00:00                   0.522500                      0.522500 1.110223e-16

----------------------------------------------------------------------
FIRST 20 MISMATCHING EXAMPLES
----------------------------------------------------------------------
Data Acquisition Time  WaterLevel_RollingMean_6h  Recreated_TimeBased_6h_Right  Difference
  2022-01-04 04:00:00                   0.272400                      0.283000    0.010600
  2022-01-04 05:00:00                   0.288000                      0.294000    0.006000
  2022-01-04 07:00:00                   0.304182                      0.306576    0.002394
  2022-01-04 10:00:00                   0.337073                      0.336182    0.000891
  2022-01-04 13:00:00                   0.385182                      0.391864    0.006682
  2022-01-04 15:00:00                   0.405227                      0.407455    0.002227
  2022-01-04 16:00:00                   0.418591                      0.434182    0.015591
  2022-01-04 17:00:00                   0.441894                      0.456886    0.014992
  2022-01-09 00:00:00                   0.731667                      0.524000    0.207667
  2022-01-09 01:00:00                   0.689667                      0.527500    0.162167
  2022-01-09 02:00:00                   0.647500                      0.530667    0.116833
  2022-01-09 03:00:00                   0.607500                      0.531500    0.076000
  2022-01-09 04:00:00                   0.569083                      0.531500    0.037583
  2022-01-10 09:00:00                   0.480750                      0.482375    0.001625
  2022-01-10 10:00:00                   0.480083                      0.481375    0.001292
  2022-01-10 12:00:00                   0.477833                      0.476333    0.001500
  2022-01-10 21:00:00                   1.173733                      1.222000    0.048267
  2022-01-10 22:00:00                   1.223000                      1.221500    0.001500
  2022-01-11 00:00:00                   1.226500                      1.230000    0.003500
  2022-01-11 03:00:00                   1.238500                      1.238667    0.000167

======================================================================
STEP 4.7 COMPLETE
======================================================================
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [18]:
# ======================================================================
# STEP 4.8 — ROLLING SEMANTICS FORENSIC TEST
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.8 — ROLLING SEMANTICS FORENSIC TEST")
print("=" * 70)

# ----------------------------------------------------------------------
# SAFETY COPY
# ----------------------------------------------------------------------

df_test = df.copy()

df_test["Data Acquisition Time"] = pd.to_datetime(
    df_test["Data Acquisition Time"]
)

df_test = (
    df_test
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"
feature_col = "WaterLevel_RollingMean_6h"

# ----------------------------------------------------------------------
# SET TIME INDEX
# ----------------------------------------------------------------------

time_df = (
    df_test[
        [time_col, water_col]
    ]
    .set_index(time_col)
)

# ----------------------------------------------------------------------
# TEST ALL CLOSED OPTIONS
# ----------------------------------------------------------------------

closed_options = [
    "right",
    "left",
    "both",
    "neither"
]

results = []

for closed_option in closed_options:

    recreated = (
        time_df[water_col]
        .rolling(
            "6h",
            closed=closed_option
        )
        .mean()
    )

    temp = df_test.copy()

    temp["Recreated"] = recreated.to_numpy()

    valid = (
        temp[feature_col].notna()
        &
        temp["Recreated"].notna()
    )

    difference = (
        temp.loc[valid, feature_col]
        -
        temp.loc[valid, "Recreated"]
    ).abs()

    matching = (
        difference <= 1e-6
    ).sum()

    checked = len(difference)

    results.append({
        "Configuration": f"6h / closed={closed_option}",
        "Checked": checked,
        "Matching": matching,
        "Mismatching": checked - matching,
        "Match_Rate_%": (
            matching / checked * 100
            if checked else 0
        )
    })

print("\n" + "-" * 70)
print("TIME-BASED CLOSED-BOUNDARY COMPARISON")
print("-" * 70)

print(
    pd.DataFrame(results).to_string(index=False)
)

# ----------------------------------------------------------------------
# SPECIFIC FORENSIC TIMESTAMPS
# ----------------------------------------------------------------------

target_times = [
    "2022-01-04 04:00:00",
    "2022-01-04 05:00:00",
    "2022-01-04 07:00:00",
    "2022-01-04 10:00:00",
    "2022-01-04 13:00:00",
    "2022-01-04 15:00:00",
    "2022-01-04 16:00:00",
    "2022-01-04 17:00:00",
    "2022-01-09 00:00:00",
    "2022-01-09 01:00:00",
    "2022-01-10 21:00:00",
    "2022-01-10 22:00:00"
]

print("\n" + "-" * 70)
print("TARGET TIMESTAMP FORENSIC COMPARISON")
print("-" * 70)

for target in target_times:

    target = pd.Timestamp(target)

    row = df_test[
        df_test[time_col] == target
    ]

    if row.empty:
        continue

    stored = row.iloc[0][feature_col]

    print("\n" + "=" * 70)
    print("Timestamp:", target)
    print("Stored feature:", stored)

    for closed_option in closed_options:

        value = (
            time_df[water_col]
            .rolling(
                "6h",
                closed=closed_option
            )
            .mean()
            .get(target)
        )

        difference = (
            abs(stored - value)
            if pd.notna(value)
            else np.nan
        )

        print(
            f"closed={closed_option:8s} | "
            f"Recreated={value} | "
            f"Difference={difference}"
        )

# ----------------------------------------------------------------------
# EXPLICIT 6-HOUR BOUNDARY TEST
# ----------------------------------------------------------------------

print("\n" + "-" * 70)
print("EXACT 6-HOUR BOUNDARY TEST")
print("-" * 70)

target = pd.Timestamp("2022-01-04 16:00:00")

window_start = target - pd.Timedelta(hours=6)

print("Target time :", target)
print("Window start:", window_start)

boundary_rows = df_test[
    (
        df_test[time_col] >= window_start
    )
    &
    (
        df_test[time_col] <= target
    )
][
    [time_col, water_col]
]

print("\nRows between [target-6h, target]:")
print(
    boundary_rows.to_string(index=False)
)

print(
    "\nMean including exact 6h boundary:",
    boundary_rows[water_col].mean()
)

# ----------------------------------------------------------------------
# FINAL
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 4.8 COMPLETE")
print("=" * 70)

print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.8 — ROLLING SEMANTICS FORENSIC TEST
======================================================================

----------------------------------------------------------------------
TIME-BASED CLOSED-BOUNDARY COMPARISON
----------------------------------------------------------------------
      Configuration  Checked  Matching  Mismatching  Match_Rate_%
  6h / closed=right     7309      6057         1252     82.870434
   6h / closed=left     7186      2752         4434     38.296688
   6h / closed=both     7309      2873         4436     39.307703
6h / closed=neither     7153      2768         4385     38.697050

----------------------------------------------------------------------
TARGET TIMESTAMP FORENSIC COMPARISON
----------------------------------------------------------------------

======================================================================
Timestamp: 2022-01-04 04:00:00
Stored feature: 0.2724
closed=right    | Recreated=0.283 | Difference=0.010599999999999998
closed=left     | Recreated=nan | Difference=nan
closed=both     | Recreated=0.283 | Difference=0.010599999999999998
closed=neither  | Recreated=nan | Difference=nan

======================================================================
Timestamp: 2022-01-04 05:00:00
Stored feature: 0.288
closed=right    | Recreated=0.294 | Difference=0.006000000000000005
closed=left     | Recreated=0.283 | Difference=0.0050000000000000044
closed=both     | Recreated=0.294 | Difference=0.006000000000000005
closed=neither  | Recreated=0.283 | Difference=0.0050000000000000044

======================================================================
Timestamp: 2022-01-04 07:00:00
Stored feature: 0.3041818181818181
closed=right    | Recreated=0.30657575757575756 | Difference=0.002393939393939448
closed=left     | Recreated=0.294 | Difference=0.010181818181818125
closed=both     | Recreated=0.30657575757575756 | Difference=0.002393939393939448
closed=neither  | Recreated=0.294 | Difference=0.010181818181818125

======================================================================
Timestamp: 2022-01-04 10:00:00
Stored feature: 0.3370727272727272
closed=right    | Recreated=0.3361818181818182 | Difference=0.0008909090909089978
closed=left     | Recreated=0.30657575757575756 | Difference=0.030496969696969634
closed=both     | Recreated=0.32288636363636364 | Difference=0.014186363636363553
closed=neither  | Recreated=0.31836363636363635 | Difference=0.018709090909090842

======================================================================
Timestamp: 2022-01-04 13:00:00
Stored feature: 0.3851818181818182
closed=right    | Recreated=0.39186363636363636 | Difference=0.006681818181818178
closed=left     | Recreated=0.35177272727272724 | Difference=0.033409090909090944
closed=both     | Recreated=0.3718181818181818 | Difference=0.013363636363636355
closed=neither  | Recreated=0.3718181818181818 | Difference=0.013363636363636355

======================================================================
Timestamp: 2022-01-04 15:00:00
Stored feature: 0.4052272727272727
closed=right    | Recreated=0.40745454545454546 | Difference=0.0022272727272727444
closed=left     | Recreated=0.39186363636363636 | Difference=0.013363636363636355
closed=both     | Recreated=0.40745454545454546 | Difference=0.0022272727272727444
closed=neither  | Recreated=0.39186363636363636 | Difference=0.013363636363636355

======================================================================
Timestamp: 2022-01-04 16:00:00
Stored feature: 0.418590909090909
closed=right    | Recreated=0.43418181818181817 | Difference=0.015590909090909155
closed=left     | Recreated=0.40745454545454546 | Difference=0.011136363636363555
closed=both     | Recreated=0.4185909090909091 | Difference=1.1102230246251565e-16
closed=neither  | Recreated=0.42527272727272725 | Difference=0.006681818181818233

======================================================================
Timestamp: 2022-01-04 17:00:00
Stored feature: 0.4418939393939394
closed=right    | Recreated=0.45688636363636365 | Difference=0.014992424242424252
closed=left     | Recreated=0.43418181818181817 | Difference=0.007712121212121226
closed=both     | Recreated=0.45688636363636365 | Difference=0.014992424242424252
closed=neither  | Recreated=0.43418181818181817 | Difference=0.007712121212121226

======================================================================
Timestamp: 2022-01-09 00:00:00
Stored feature: 0.7316666666666668
closed=right    | Recreated=0.524 | Difference=0.20766666666666678
closed=left     | Recreated=nan | Difference=nan
closed=both     | Recreated=0.524 | Difference=0.20766666666666678
closed=neither  | Recreated=nan | Difference=nan

======================================================================
Timestamp: 2022-01-09 01:00:00
Stored feature: 0.6896666666666667
closed=right    | Recreated=0.5275000000000001 | Difference=0.16216666666666657
closed=left     | Recreated=0.524 | Difference=0.16566666666666663
closed=both     | Recreated=0.5275000000000001 | Difference=0.16216666666666657
closed=neither  | Recreated=0.524 | Difference=0.16566666666666663

======================================================================
Timestamp: 2022-01-10 21:00:00
Stored feature: 1.1737333333333333
closed=right    | Recreated=1.222 | Difference=0.04826666666666668
closed=left     | Recreated=nan | Difference=nan
closed=both     | Recreated=1.222 | Difference=0.04826666666666668
closed=neither  | Recreated=nan | Difference=nan

======================================================================
Timestamp: 2022-01-10 22:00:00
Stored feature: 1.223
closed=right    | Recreated=1.2215 | Difference=0.0015000000000000568
closed=left     | Recreated=1.222 | Difference=0.001000000000000112
closed=both     | Recreated=1.2215 | Difference=0.0015000000000000568
closed=neither  | Recreated=1.222 | Difference=0.001000000000000112

----------------------------------------------------------------------
EXACT 6-HOUR BOUNDARY TEST
----------------------------------------------------------------------
Target time : 2022-01-04 16:00:00
Window start: 2022-01-04 10:00:00

Rows between [target-6h, target]:
Data Acquisition Time  Current_Water_Level
  2022-01-04 10:00:00             0.371818
  2022-01-04 13:00:00             0.411909
  2022-01-04 15:00:00             0.438636
  2022-01-04 16:00:00             0.452000

Mean including exact 6h boundary: 0.41859090909090907

======================================================================
STEP 4.8 COMPLETE
======================================================================
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [19]:
# ======================================================================
# STEP 4.9 — EXACT HOURLY-INTERPOLATION ROLLING RECONSTRUCTION
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.9 — EXACT HOURLY-INTERPOLATION ROLLING RECONSTRUCTION")
print("=" * 70)

# ----------------------------------------------------------------------
# SAFETY COPY
# ----------------------------------------------------------------------

df_test = df.copy()

df_test["Data Acquisition Time"] = pd.to_datetime(
    df_test["Data Acquisition Time"]
)

df_test = (
    df_test
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)

time_col = "Data Acquisition Time"
water_col = "Current_Water_Level"
feature_col = "WaterLevel_RollingMean_6h"

# ----------------------------------------------------------------------
# CREATE HOURLY TIME GRID
# ----------------------------------------------------------------------

hourly = (
    df_test[
        [time_col, water_col]
    ]
    .drop_duplicates(subset=[time_col])
    .set_index(time_col)
    .sort_index()
)

hourly = hourly.resample("1h").asfreq()

print("\n" + "-" * 70)
print("HOURLY RESAMPLING")
print("-" * 70)

print("Original rows :", len(df_test))
print("Hourly rows   :", len(hourly))

print(
    "Missing hourly values before interpolation:",
    hourly[water_col].isna().sum()
)

# ----------------------------------------------------------------------
# TIME-BASED LINEAR INTERPOLATION
# ----------------------------------------------------------------------

hourly_interpolated = hourly.copy()

hourly_interpolated[water_col] = (
    hourly_interpolated[water_col]
    .interpolate(method="time")
)

print(
    "Missing hourly values after interpolation:",
    hourly_interpolated[water_col].isna().sum()
)

# ----------------------------------------------------------------------
# CALCULATE 6H ROLLING MEAN
# ----------------------------------------------------------------------

recreated_hourly = (
    hourly_interpolated[water_col]
    .rolling(
        "6h",
        closed="right"
    )
    .mean()
)

# ----------------------------------------------------------------------
# ALSO TEST 6 ROWS ON THE HOURLY GRID
# ----------------------------------------------------------------------

recreated_6rows_hourly = (
    hourly_interpolated[water_col]
    .rolling(
        window=6,
        min_periods=6
    )
    .mean()
)

# ----------------------------------------------------------------------
# MAP RESULTS BACK TO ORIGINAL TIMESTAMPS
# ----------------------------------------------------------------------

df_test["Recreated_Hourly_Time_6h"] = (
    recreated_hourly
    .reindex(df_test[time_col])
    .to_numpy()
)

df_test["Recreated_Hourly_6Rows"] = (
    recreated_6rows_hourly
    .reindex(df_test[time_col])
    .to_numpy()
)

# ----------------------------------------------------------------------
# COMPARE BOTH RECONSTRUCTIONS
# ----------------------------------------------------------------------

for col in [
    "Recreated_Hourly_Time_6h",
    "Recreated_Hourly_6Rows"
]:

    diff = (
        df_test[feature_col]
        -
        df_test[col]
    ).abs()

    valid = (
        df_test[feature_col].notna()
        &
        df_test[col].notna()
    )

    matching = (
        valid &
        (diff <= 1e-6)
    ).sum()

    checked = valid.sum()

    print("\n" + "-" * 70)
    print(col)
    print("-" * 70)

    print("Checked     :", checked)
    print("Matching    :", matching)
    print("Mismatching :", checked - matching)

    print(
        f"Match rate  : "
        f"{matching / checked * 100:.4f}%"
    )

    if checked > 0:

        print(
            "Mean abs difference   :",
            diff[valid].mean()
        )

        print(
            "Median abs difference :",
            diff[valid].median()
        )

        print(
            "Maximum difference    :",
            diff[valid].max()
        )

# ----------------------------------------------------------------------
# FORENSIC PROOF — KNOWN TIMESTAMPS
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("KNOWN-TIMESTAMP PROOF")
print("=" * 70)

target_times = [
    "2022-01-04 16:00:00",
    "2022-01-04 17:00:00",
    "2022-01-09 01:00:00",
    "2022-01-10 21:00:00"
]

for target in target_times:

    target = pd.Timestamp(target)

    original = df_test[
        df_test[time_col] == target
    ]

    if original.empty:
        continue

    print("\n" + "-" * 70)
    print("Timestamp:", target)

    print(
        "Stored feature:",
        original.iloc[0][feature_col]
    )

    print(
        "Hourly time rolling:",
        original.iloc[0]["Recreated_Hourly_Time_6h"]
    )

    print(
        "Hourly 6-row rolling:",
        original.iloc[0]["Recreated_Hourly_6Rows"]
    )

# ----------------------------------------------------------------------
# SHOW INTERPOLATED VALUES FOR FIRST PROOF CASE
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("INTERPOLATION PROOF — 2022-01-04 10:00 TO 17:00")
print("=" * 70)

proof_start = pd.Timestamp("2022-01-04 10:00:00")
proof_end = pd.Timestamp("2022-01-04 17:00:00")

proof = hourly_interpolated.loc[
    proof_start:proof_end,
    [water_col]
]

print(
    proof.to_string()
)

print("\n" + "=" * 70)
print("STEP 4.9 COMPLETE")
print("=" * 70)

print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.9 — EXACT HOURLY-INTERPOLATION ROLLING RECONSTRUCTION
======================================================================

----------------------------------------------------------------------
HOURLY RESAMPLING
----------------------------------------------------------------------
Original rows : 7309
Hourly rows   : 38678
Missing hourly values before interpolation: 31369
Missing hourly values after interpolation: 0

----------------------------------------------------------------------
Recreated_Hourly_Time_6h
----------------------------------------------------------------------
Checked     : 7309
Matching    : 6060
Mismatching : 1249
Match rate  : 82.9115%
Mean abs difference   : 0.07057096097343654
Median abs difference : 0.0
Maximum difference    : 16.191000000000003

----------------------------------------------------------------------
Recreated_Hourly_6Rows
----------------------------------------------------------------------
Checked     : 7306
Matching    : 6060
Mismatching : 1246
Match rate  : 82.9455%
Mean abs difference   : 0.07059693578507484
Median abs difference : 0.0
Maximum difference    : 16.191000000000003

======================================================================
KNOWN-TIMESTAMP PROOF
======================================================================

----------------------------------------------------------------------
Timestamp: 2022-01-04 16:00:00
Stored feature: 0.418590909090909
Hourly time rolling: 0.41859090909090907
Hourly 6-row rolling: 0.41859090909090907

----------------------------------------------------------------------
Timestamp: 2022-01-04 17:00:00
Stored feature: 0.4418939393939394
Hourly time rolling: 0.4418939393939394
Hourly 6-row rolling: 0.4418939393939394

----------------------------------------------------------------------
Timestamp: 2022-01-09 01:00:00
Stored feature: 0.6896666666666667
Hourly time rolling: 0.5251828478964401
Hourly 6-row rolling: 0.5251828478964401

----------------------------------------------------------------------
Timestamp: 2022-01-10 21:00:00
Stored feature: 1.1737333333333333
Hourly time rolling: 1.0142222222222221
Hourly 6-row rolling: 1.0142222222222221

======================================================================
INTERPOLATION PROOF — 2022-01-04 10:00 TO 17:00
======================================================================
                       Current_Water_Level
Data Acquisition Time
2022-01-04 10:00:00               0.371818
2022-01-04 11:00:00               0.385182
2022-01-04 12:00:00               0.398545
2022-01-04 13:00:00               0.411909
2022-01-04 14:00:00               0.425273
2022-01-04 15:00:00               0.438636
2022-01-04 16:00:00               0.452000
2022-01-04 17:00:00               0.525000

======================================================================
STEP 4.9 COMPLETE
======================================================================
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [20]:
# ================================================================
# STEP 4.10 — STORED 6H ROLLING SEMANTICS FORENSIC TEST
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.10 — STORED 6H ROLLING SEMANTICS FORENSIC TEST")
print("=" * 70)

# ---------------------------------------------------------------
# 0. SAFETY COPY
# ---------------------------------------------------------------

df_test = df.copy()

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"
FEATURE_COL = "WaterLevel_RollingMean_6h"

df_test[TIME_COL] = pd.to_datetime(df_test[TIME_COL])

print("\nOriginal rows:", len(df_test))
print("Original columns:", len(df_test.columns))


# ---------------------------------------------------------------
# 1. VERIFY REQUIRED COLUMNS
# ---------------------------------------------------------------

required = [TIME_COL, VALUE_COL, FEATURE_COL]

missing = [c for c in required if c not in df_test.columns]

if missing:
    raise ValueError(f"Missing required columns: {missing}")

print("\nRequired columns: PASS")


# ---------------------------------------------------------------
# 2. CHECK TIMESTAMP ORDER + DUPLICATES
# ---------------------------------------------------------------

print("\n" + "-" * 70)
print("TIMESTAMP STRUCTURE")
print("-" * 70)

is_sorted = df_test[TIME_COL].is_monotonic_increasing
duplicate_count = df_test[TIME_COL].duplicated().sum()

print("Already sorted:", is_sorted)
print("Duplicate timestamps:", duplicate_count)

if duplicate_count > 0:
    print("\nDuplicate timestamp examples:")
    print(
        df_test[df_test[TIME_COL].duplicated(keep=False)]
        [[TIME_COL, VALUE_COL]]
        .sort_values(TIME_COL)
        .head(20)
    )


# ---------------------------------------------------------------
# 3. CREATE CLEAN TIME INDEX — WITHOUT MODIFYING ORIGINAL DATA
# ---------------------------------------------------------------

base = (
    df_test[[TIME_COL, VALUE_COL, FEATURE_COL]]
    .copy()
    .sort_values(TIME_COL)
)

base_indexed = base.set_index(TIME_COL)


# ---------------------------------------------------------------
# 4. COMPARISON FUNCTION
# ---------------------------------------------------------------

def compare_candidate(name, candidate):

    comparison = pd.DataFrame({
        "stored": base_indexed[FEATURE_COL],
        "candidate": candidate
    })

    valid = comparison["stored"].notna() & comparison["candidate"].notna()

    if valid.sum() == 0:
        return {
            "Configuration": name,
            "Checked": 0,
            "Matching": 0,
            "Mismatching": 0,
            "Match_Rate_%": 0,
            "Mean_Abs_Difference": np.nan,
            "Median_Abs_Difference": np.nan,
            "Maximum_Difference": np.nan
        }

    diff = (
        comparison.loc[valid, "stored"]
        - comparison.loc[valid, "candidate"]
    ).abs()

    matching = np.isclose(
        comparison.loc[valid, "stored"],
        comparison.loc[valid, "candidate"],
        rtol=1e-10,
        atol=1e-10
    )

    return {
        "Configuration": name,
        "Checked": int(valid.sum()),
        "Matching": int(matching.sum()),
        "Mismatching": int((~matching).sum()),
        "Match_Rate_%": round(matching.mean() * 100, 6),
        "Mean_Abs_Difference": diff.mean(),
        "Median_Abs_Difference": diff.median(),
        "Maximum_Difference": diff.max()
    }


# ---------------------------------------------------------------
# 5. CANDIDATE TESTS
# ---------------------------------------------------------------

results = []


# ===============================================================
# TEST GROUP A — TIME BASED ROLLING
# ===============================================================

print("\n" + "=" * 70)
print("TEST GROUP A — TIME-BASED ROLLING")
print("=" * 70)

for closed in ["right", "left", "both", "neither"]:

    try:
        candidate = (
            base_indexed[VALUE_COL]
            .rolling("6h", closed=closed)
            .mean()
        )

        results.append(
            compare_candidate(
                f"6h / closed={closed}",
                candidate
            )
        )

    except Exception as e:
        print(f"6h / closed={closed} FAILED: {e}")


# ===============================================================
# TEST GROUP B — ROW BASED ROLLING
# ===============================================================

print("\n" + "=" * 70)
print("TEST GROUP B — ROW-BASED ROLLING")
print("=" * 70)

for window in [5, 6, 7]:

    for min_periods in [1, window]:

        candidate = (
            base_indexed[VALUE_COL]
            .rolling(
                window=window,
                min_periods=min_periods
            )
            .mean()
        )

        results.append(
            compare_candidate(
                f"{window} rows / min_periods={min_periods}",
                candidate
            )
        )


# ===============================================================
# TEST GROUP C — TIME BASED + min_periods
# ===============================================================

print("\n" + "=" * 70)
print("TEST GROUP C — TIME-BASED + min_periods")
print("=" * 70)

for closed in ["right", "left", "both", "neither"]:

    for min_periods in [1, 2, 3, 4, 5, 6]:

        try:

            candidate = (
                base_indexed[VALUE_COL]
                .rolling(
                    "6h",
                    closed=closed,
                    min_periods=min_periods
                )
                .mean()
            )

            results.append(
                compare_candidate(
                    f"6h / closed={closed} / min_periods={min_periods}",
                    candidate
                )
            )

        except Exception:
            pass


# ===============================================================
# TEST GROUP D — SHIFTED TIME WINDOWS
# ===============================================================

print("\n" + "=" * 70)
print("TEST GROUP D — SHIFTED / ALTERNATIVE WINDOW ALIGNMENT")
print("=" * 70)

# These test whether the stored feature may represent
# a previous/shifted 6-hour window.

for shift in [-2, -1, 0, 1, 2]:

    candidate = (
        base_indexed[VALUE_COL]
        .rolling("6h", closed="right")
        .mean()
        .shift(shift)
    )

    results.append(
        compare_candidate(
            f"6h / closed=right / shift={shift}",
            candidate
        )
    )


# ---------------------------------------------------------------
# 6. RESULTS TABLE
# ---------------------------------------------------------------

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Match_Rate_%",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 70)
print("ALL CANDIDATE RESULTS — RANKED")
print("=" * 70)

print(
    results_df.to_string(
        index=False
    )
)


# ---------------------------------------------------------------
# 7. BEST CANDIDATE
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("BEST CANDIDATE")
print("=" * 70)

best = results_df.iloc[0]

print("Configuration :", best["Configuration"])
print("Checked       :", best["Checked"])
print("Matching      :", best["Matching"])
print("Mismatching   :", best["Mismatching"])
print("Match rate    :", best["Match_Rate_%"], "%")
print("Mean abs diff :", best["Mean_Abs_Difference"])
print("Median diff   :", best["Median_Abs_Difference"])
print("Maximum diff  :", best["Maximum_Difference"])


# ---------------------------------------------------------------
# 8. SHOW WORST MISMATCHES FOR BEST CANDIDATE
# ---------------------------------------------------------------

best_name = best["Configuration"]

if "shift=" in best_name:

    shift_value = int(
        best_name.split("shift=")[1]
    )

    best_candidate = (
        base_indexed[VALUE_COL]
        .rolling("6h", closed="right")
        .mean()
        .shift(shift_value)
    )

elif "min_periods=" in best_name and "6h" in best_name:

    closed_value = best_name.split("closed=")[1].split(" ")[0]
    min_value = int(best_name.split("min_periods=")[1])

    best_candidate = (
        base_indexed[VALUE_COL]
        .rolling(
            "6h",
            closed=closed_value,
            min_periods=min_value
        )
        .mean()
    )

elif "6h / closed=" in best_name:

    closed_value = best_name.split("closed=")[1]

    best_candidate = (
        base_indexed[VALUE_COL]
        .rolling(
            "6h",
            closed=closed_value
        )
        .mean()
    )

else:

    # Row based fallback
    window_value = int(
        best_name.split(" rows")[0]
    )

    min_value = int(
        best_name.split("min_periods=")[1]
    )

    best_candidate = (
        base_indexed[VALUE_COL]
        .rolling(
            window=window_value,
            min_periods=min_value
        )
        .mean()
    )


comparison = pd.DataFrame({
    "Stored": base_indexed[FEATURE_COL],
    "Best_Candidate": best_candidate
})

comparison["Abs_Difference"] = (
    comparison["Stored"]
    - comparison["Best_Candidate"]
).abs()

comparison["Match"] = np.isclose(
    comparison["Stored"],
    comparison["Best_Candidate"],
    rtol=1e-10,
    atol=1e-10
)

worst = (
    comparison[
        comparison["Stored"].notna()
        & comparison["Best_Candidate"].notna()
    ]
    .sort_values(
        "Abs_Difference",
        ascending=False
    )
    .head(20)
)

print("\n" + "=" * 70)
print("TOP 20 WORST MISMATCHES — BEST CANDIDATE")
print("=" * 70)

print(worst.to_string())


# ---------------------------------------------------------------
# 9. KNOWN TIMESTAMP PROOF
# ---------------------------------------------------------------

known_timestamps = [
    "2022-01-04 16:00:00",
    "2022-01-04 17:00:00",
    "2022-01-09 01:00:00",
    "2022-01-10 21:00:00"
]

print("\n" + "=" * 70)
print("KNOWN-TIMESTAMP PROOF — BEST CANDIDATE")
print("=" * 70)

for ts in known_timestamps:

    ts = pd.Timestamp(ts)

    if ts in comparison.index:

        print("\nTimestamp:", ts)
        print(
            "Stored:",
            comparison.loc[ts, "Stored"]
        )
        print(
            "Best candidate:",
            comparison.loc[ts, "Best_Candidate"]
        )
        print(
            "Absolute difference:",
            comparison.loc[ts, "Abs_Difference"]
        )
        print(
            "Exact match:",
            comparison.loc[ts, "Match"]
        )


# ---------------------------------------------------------------
# 10. DATA SAFETY PROOF
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df rows after test :", len(df))
print("Original df columns         :", len(df.columns))

print("\nSTEP 4.10 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.10 — STORED 6H ROLLING SEMANTICS FORENSIC TEST
======================================================================

Original rows: 7309
Original columns: 21

Required columns: PASS

----------------------------------------------------------------------
TIMESTAMP STRUCTURE
----------------------------------------------------------------------
Already sorted: True
Duplicate timestamps: 0

======================================================================
TEST GROUP A — TIME-BASED ROLLING
======================================================================

======================================================================
TEST GROUP B — ROW-BASED ROLLING
======================================================================

======================================================================
TEST GROUP C — TIME-BASED + min_periods
======================================================================

======================================================================
TEST GROUP D — SHIFTED / ALTERNATIVE WINDOW ALIGNMENT
======================================================================

======================================================================
ALL CANDIDATE RESULTS — RANKED
======================================================================
                      Configuration  Checked  Matching  Mismatching  Match_Rate_%  Mean_Abs_Difference  Median_Abs_Difference  Maximum_Difference
  6h / closed=right / min_periods=6     5210      5210            0    100.000000         7.087741e-16               0.000000        2.131628e-14
  6h / closed=right / min_periods=5     5991      5520          471     92.138207         1.392097e-02               0.000000        6.391967e+00
  6h / closed=right / min_periods=4     6520      5744          776     88.098160         3.978971e-02               0.000000        1.199908e+01
  6h / closed=right / min_periods=3     6924      5916         1008     85.441941         5.416768e-02               0.000000        1.199908e+01
  6h / closed=right / min_periods=2     7153      6005         1148     83.950790         6.278913e-02               0.000000        1.601683e+01
  6h / closed=right / min_periods=1     7309      6057         1252     82.870434         7.557350e-02               0.000000        3.608600e+01
                  6h / closed=right     7309      6057         1252     82.870434         7.557350e-02               0.000000        3.608600e+01
        6h / closed=right / shift=0     7309      6057         1252     82.870434         7.557350e-02               0.000000        3.608600e+01
             6 rows / min_periods=6     7304      5996         1308     82.092004         4.300539e-01               0.000000        3.977183e+01
             6 rows / min_periods=1     7309      5996         1313     82.035846         4.297704e-01               0.000000        3.977183e+01
   6h / closed=both / min_periods=3     7003      2764         4239     39.468799         1.153569e-01               0.000631        1.439913e+01
   6h / closed=both / min_periods=2     7186      2836         4350     39.465628         1.238483e-01               0.000643        1.601683e+01
   6h / closed=both / min_periods=5     6324      2490         3834     39.373814         9.110817e-02               0.000595        1.439913e+01
   6h / closed=both / min_periods=4     6754      2659         4095     39.369263         1.080087e-01               0.000619        1.439913e+01
                   6h / closed=both     7309      2873         4436     39.307703         1.290862e-01               0.000667        1.601683e+01
   6h / closed=both / min_periods=1     7309      2873         4436     39.307703         1.290862e-01               0.000667        1.601683e+01
   6h / closed=both / min_periods=6     5829      2285         3544     39.200549         7.051288e-02               0.000571        7.990167e+00
6h / closed=neither / min_periods=1     7153      2768         4385     38.697050         1.428100e-01               0.000733        2.880300e+01
                6h / closed=neither     7153      2768         4385     38.697050         1.428100e-01               0.000733        2.880300e+01
6h / closed=neither / min_periods=2     6924      2678         4246     38.677065         1.295157e-01               0.000700        2.399933e+01
6h / closed=neither / min_periods=3     6520      2506         4014     38.435583         1.059436e-01               0.000700        2.399933e+01
                   6h / closed=left     7186      2752         4434     38.296688         2.195289e-01               0.001500        2.880300e+01
   6h / closed=left / min_periods=1     7186      2752         4434     38.296688         2.195289e-01               0.001500        2.880300e+01
   6h / closed=left / min_periods=2     7003      2680         4323     38.269313         2.070705e-01               0.001400        2.880300e+01
   6h / closed=left / min_periods=3     6754      2575         4179     38.125555         1.968645e-01               0.001333        2.399933e+01
   6h / closed=left / min_periods=4     6324      2405         3919     38.029728         1.659672e-01               0.001333        2.399933e+01
6h / closed=neither / min_periods=4     5991      2276         3715     37.990319         7.643108e-02               0.000667        1.598117e+01
        6h / closed=right / shift=1     7308      2768         4540     37.876300         3.443476e-01               0.001500        4.768267e+01
   6h / closed=left / min_periods=5     5829      2202         3627     37.776634         1.384726e-01               0.001333        1.596117e+01
       6h / closed=right / shift=-1     7308      2755         4553     37.698413         3.824209e-01               0.001833        4.783417e+01
6h / closed=neither / min_periods=5     5210      1959         3251     37.600768         6.208161e-02               0.000667        8.051667e+00
   6h / closed=left / min_periods=6     5064      1903         3161     37.578989         1.241444e-01               0.001333        8.213833e+00
             5 rows / min_periods=5     7305      2731         4574     37.385352         3.797108e-01               0.000833        3.816967e+01
             5 rows / min_periods=1     7309      2731         4578     37.364893         3.795075e-01               0.000833        3.816967e+01
        6h / closed=right / shift=2     7307      2665         4642     36.471876         6.644255e-01               0.003667        4.800650e+01
       6h / closed=right / shift=-2     7307      2648         4659     36.239223         7.174003e-01               0.004000        4.795900e+01
             7 rows / min_periods=7     7303      2603         4700     35.642886         5.945011e-01               0.001095        4.091624e+01
             7 rows / min_periods=1     7309      2603         4706     35.613627         5.940303e-01               0.001095        4.091624e+01
6h / closed=neither / min_periods=6        0         0            0      0.000000                  NaN                    NaN                 NaN

======================================================================
BEST CANDIDATE
======================================================================
Configuration : 6h / closed=right / min_periods=6
Checked       : 5210
Matching      : 5210
Mismatching   : 0
Match rate    : 100.0 %
Mean abs diff : 7.08774050327396e-16
Median diff   : 0.0
Maximum diff  : 2.1316282072803006e-14

======================================================================
TOP 20 WORST MISMATCHES — BEST CANDIDATE
======================================================================
                          Stored  Best_Candidate  Abs_Difference  Match
Data Acquisition Time
2025-03-05 16:00:00    60.323333       60.323333    2.131628e-14   True
2025-04-06 17:00:00    60.725667       60.725667    2.131628e-14   True
2025-05-07 11:00:00    60.758167       60.758167    2.131628e-14   True
2026-05-27 20:00:00    61.026167       61.026167    2.131628e-14   True
2026-05-27 16:00:00    61.014167       61.014167    2.131628e-14   True
2025-05-08 13:00:00    60.586167       60.586167    2.131628e-14   True
2026-05-31 07:00:00    60.979000       60.979000    1.421085e-14   True
2025-01-08 10:00:00    60.569667       60.569667    1.421085e-14   True
2025-01-06 18:00:00    61.860000       61.860000    1.421085e-14   True
2026-05-30 16:00:00    61.027833       61.027833    1.421085e-14   True
2025-03-08 00:00:00    60.949000       60.949000    1.421085e-14   True
2025-02-07 14:00:00    61.046167       61.046167    1.421085e-14   True
2025-03-08 08:00:00    60.727667       60.727667    1.421085e-14   True
2025-03-08 06:00:00    60.763333       60.763333    1.421085e-14   True
2025-04-07 09:00:00    60.923333       60.923333    1.421085e-14   True
2025-04-08 04:00:00    61.200833       61.200833    1.421085e-14   True
2025-04-08 10:00:00    61.180167       61.180167    1.421085e-14   True
2025-04-06 23:00:00    60.850667       60.850667    1.421085e-14   True
2026-05-28 16:00:00    61.070500       61.070500    1.421085e-14   True
2026-05-29 13:00:00    61.098167       61.098167    1.421085e-14   True

======================================================================
KNOWN-TIMESTAMP PROOF — BEST CANDIDATE
======================================================================

Timestamp: 2022-01-04 16:00:00
Stored: 0.418590909090909
Best candidate: nan
Absolute difference: nan
Exact match: False

Timestamp: 2022-01-04 17:00:00
Stored: 0.4418939393939394
Best candidate: nan
Absolute difference: nan
Exact match: False

Timestamp: 2022-01-09 01:00:00
Stored: 0.6896666666666667
Best candidate: nan
Absolute difference: nan
Exact match: False

Timestamp: 2022-01-10 21:00:00
Stored: 1.1737333333333333
Best candidate: nan
Absolute difference: nan
Exact match: False

======================================================================
DATA SAFETY CHECK
======================================================================
Original df rows after test : 7309
Original df columns         : 21

STEP 4.10 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [2]:
# ================================================================
# STEP 4.11 — DATAFRAME RECOVERY CHECK
# ================================================================

print("Checking available variables...")

print("df exists:", "df" in globals())

if "df" not in globals():
    print("\nERROR: df is not loaded in the current notebook session.")
    print("Please run the earlier cell that loads your final dataset.")
else:
    print("\nDF FOUND")
    print("Rows    :", len(df))
    print("Columns :", len(df.columns))
    print("\nColumns:")
    print(df.columns.tolist())

Checking available variables...
df exists: False

ERROR: df is not loaded in the current notebook session.
Please run the earlier cell that loads your final dataset.

In [4]:
# ============================================================
# STEP 42 — RECOVER RAINFALL DATASET FROM VERIFIED RAW FILES
# ============================================================

import pandas as pd
import numpy as np

print("STEP 42 — RECOVERING RAINFALL WORKING DATASET")
print("=" * 70)

# ------------------------------------------------------------
# 1. LOAD VERIFIED RAW RAINFALL FILES
# ------------------------------------------------------------

rainfall_2021_2025 = pd.read_csv(
    "data/raw/assam_rainfall_2021_2025.csv"
)

rainfall_2026_2030 = pd.read_csv(
    "data/raw/assam_rainfall_2026_2030.csv"
)

print("Raw rainfall files loaded:")
print("2021-2025:", rainfall_2021_2025.shape)
print("2026-2030:", rainfall_2026_2030.shape)


# ------------------------------------------------------------
# 2. COMBINE
# ------------------------------------------------------------

rainfall_all = pd.concat(
    [
        rainfall_2021_2025,
        rainfall_2026_2030
    ],
    ignore_index=True
)


# ------------------------------------------------------------
# 3. PARSE TIMESTAMP
# ------------------------------------------------------------

rainfall_all["Data Acquisition Time"] = pd.to_datetime(
    rainfall_all["Data Acquisition Time"],
    errors="coerce",
    dayfirst=True
)

rainfall_col = "Telemetry Hourly Rainfall (mm)"


# ------------------------------------------------------------
# 4. SELECT TARGET STATION
# ------------------------------------------------------------

rainfall_fakirpara = rainfall_all[
    rainfall_all["Station"].astype(str).str.strip()
    == "NH15 Crossing Fakirpara Tangni"
].copy()

rainfall_fakirpara = (
    rainfall_fakirpara
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 5. FIND DUPLICATE TIMESTAMPS
# ------------------------------------------------------------

duplicate_mask = rainfall_fakirpara[
    "Data Acquisition Time"
].duplicated(
    keep=False
)

duplicate_rows = rainfall_fakirpara[
    duplicate_mask
].copy()


# ------------------------------------------------------------
# 6. IDENTIFY EXACT DUPLICATE PAIRS
# ------------------------------------------------------------

duplicate_groups = (
    rainfall_fakirpara[
        rainfall_fakirpara[
            "Data Acquisition Time"
        ].duplicated(keep=False)
    ]
    .groupby("Data Acquisition Time")
)

exact_duplicate_times = []

for timestamp, group in duplicate_groups:

    values = (
        group[rainfall_col]
        .dropna()
        .tolist()
    )

    if len(values) == 2 and values[0] == values[1]:
        exact_duplicate_times.append(timestamp)


# ------------------------------------------------------------
# 7. KEEP ONE COPY OF EXACT DUPLICATES
# ------------------------------------------------------------

exact_duplicate_clean = (
    rainfall_fakirpara[
        rainfall_fakirpara[
            "Data Acquisition Time"
        ].isin(exact_duplicate_times)
    ]
    .drop_duplicates(
        subset=["Data Acquisition Time"],
        keep="first"
    )
)


# ------------------------------------------------------------
# 8. REMOVE ALL DUPLICATE TIMESTAMPS
# ------------------------------------------------------------

rainfall_unique = (
    rainfall_fakirpara[
        ~rainfall_fakirpara[
            "Data Acquisition Time"
        ].duplicated(keep=False)
    ]
    .copy()
)


# ------------------------------------------------------------
# 9. ADD EXACT DUPLICATES BACK
# ------------------------------------------------------------

rainfall_clean = pd.concat(
    [
        rainfall_unique,
        exact_duplicate_clean
    ],
    ignore_index=True
)

rainfall_clean = (
    rainfall_clean
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. ADD TIME FEATURES
# ------------------------------------------------------------

rainfall_clean["time_gap"] = (
    rainfall_clean[
        "Data Acquisition Time"
    ].diff()
)

rainfall_clean["year"] = (
    rainfall_clean[
        "Data Acquisition Time"
    ].dt.year
)

rainfall_clean["month"] = (
    rainfall_clean[
        "Data Acquisition Time"
    ].dt.month
)


# ------------------------------------------------------------
# 11. FINAL RECOVERY CHECK
# ------------------------------------------------------------

print()
print("RECOVERED RAINFALL DATASET")
print("-" * 70)

print(
    "Shape:",
    rainfall_clean.shape
)

print(
    "Duplicate timestamps:",
    rainfall_clean[
        "Data Acquisition Time"
    ].duplicated().sum()
)

print(
    "Missing rainfall:",
    rainfall_clean[
        rainfall_col
    ].isna().sum()
)

print(
    "Valid rainfall:",
    rainfall_clean[
        rainfall_col
    ].notna().sum()
)

print(
    "Date range:",
    rainfall_clean[
        "Data Acquisition Time"
    ].min(),
    "to",
    rainfall_clean[
        "Data Acquisition Time"
    ].max()
)


# ------------------------------------------------------------
# 12. CONFIRM VARIABLE EXISTS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RECOVERY STATUS")
print("=" * 70)

print(
    "rainfall_clean exists:",
    "rainfall_clean" in globals()
)

print(
    "rainfall_clean rows:",
    len(rainfall_clean)
)

print(
    "rainfall_clean columns:",
    len(rainfall_clean.columns)
)

print("\nSTEP 42 RECOVERY COMPLETE.")

STEP 42 — RECOVERING RAINFALL WORKING DATASET
======================================================================
Raw rainfall files loaded:
2021-2025: (74560, 20)
2026-2030: (1336, 20)

RECOVERED RAINFALL DATASET
----------------------------------------------------------------------
Shape: (1322, 23)
Duplicate timestamps: 0
Missing rainfall: 0
Valid rainfall: 1322
Date range: 2022-03-25 06:00:00 to 2026-05-27 06:00:00

======================================================================
RECOVERY STATUS
======================================================================
rainfall_clean exists: True
rainfall_clean rows: 1322
rainfall_clean columns: 23

STEP 42 RECOVERY COMPLETE.

In [6]:
# ============================================================
# STEP 43 — FIND VERIFIED WATER-LEVEL RAW FILE
# ============================================================

import os
import glob

print("=" * 70)
print("STEP 43 — FINDING WATER-LEVEL RAW DATA")
print("=" * 70)

files = glob.glob("data/raw/*.csv")

print("\nCSV files found:")
for f in files:
    print(" -", f)

print("\nWater-level candidate files:")

for f in files:
    name = os.path.basename(f).lower()

    if any(x in name for x in [
        "water",
        "level",
        "nwdp",
        "darrang",
        "fakirpara",
        "api"
    ]):
        print(" ->", f)

======================================================================
STEP 43 — FINDING WATER-LEVEL RAW DATA
======================================================================

CSV files found:
 - data/raw\assam_rainfall_2021_2025.csv
 - data/raw\assam_rainfall_2026_2030.csv
 - data/raw\assam_water_level_2021_2025.csv
 - data/raw\darrang_api1_raw.csv
 - data/raw\darrang_api2_raw.csv

Water-level candidate files:
 -> data/raw\assam_water_level_2021_2025.csv
 -> data/raw\darrang_api1_raw.csv
 -> data/raw\darrang_api2_raw.csv

In [7]:
# ============================================================
# STEP 44 — WATER-LEVEL RAW FILE STRUCTURE CHECK
# ============================================================

import pandas as pd

print("=" * 70)
print("STEP 44 — WATER-LEVEL RAW FILE STRUCTURE CHECK")
print("=" * 70)

files = [
    "data/raw/assam_water_level_2021_2025.csv",
    "data/raw/darrang_api1_raw.csv",
    "data/raw/darrang_api2_raw.csv"
]

for file in files:

    print("\n" + "-" * 70)
    print("FILE:", file)
    print("-" * 70)

    temp = pd.read_csv(file)

    print("Shape:", temp.shape)

    print("\nColumns:")
    for col in temp.columns:
        print(" -", col)

    print("\nFirst 2 rows:")
    display(temp.head(2))

======================================================================
STEP 44 — WATER-LEVEL RAW FILE STRUCTURE CHECK
======================================================================

----------------------------------------------------------------------
FILE: data/raw/assam_water_level_2021_2025.csv
----------------------------------------------------------------------
Shape: (78212, 24)

Columns:
 - _id
 - SlNo
 - Station
 - Agency
 - State LGD Code
 - State
 - District LGD Code
 - District
 - Tehsil
 - Block
 - Village
 - River
 - Basin
 - Tributary
 - Subtributary
 - SubSubtributary
 - Local River
 - Latitude
 - Longitude
 - Is_DischargeDataAvailable
 - RL_of_zeroGauge
 - MeanSeaLevel
 - Data Acquisition Time
 - River Water Level Telemetry Hourly (meter)

First 2 rows:

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,Data Acquisition Time,River Water Level Telemetry Hourly (meter)
0,1,1,NH15 Crossing Dhansirighat,Assam,18,Assam,617,Udalguri,-,-,...,-,-,-,26.695833,92.257778,No,0,0,26-02-2022 17:00,0.296
1,2,2,NH15 Crossing Dhansirighat,Assam,18,Assam,617,Udalguri,-,-,...,-,-,-,26.695833,92.257778,No,0,0,26-02-2022 18:00,0.291

----------------------------------------------------------------------
FILE: data/raw/darrang_api1_raw.csv
----------------------------------------------------------------------
Shape: (36460, 24)

Columns:
 - _id
 - SlNo
 - Station
 - Agency
 - State LGD Code
 - State
 - District LGD Code
 - District
 - Tehsil
 - Block
 - Village
 - River
 - Basin
 - Tributary
 - Subtributary
 - SubSubtributary
 - Local River
 - Latitude
 - Longitude
 - Is_DischargeDataAvailable
 - RL_of_zeroGauge
 - MeanSeaLevel
 - Data Acquisition Time
 - River Water Level Telemetry Hourly (meter)

First 2 rows:

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,Data Acquisition Time,River Water Level Telemetry Hourly (meter)
0,16499,16499,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,-,...,-,-,-,26.508333,92.116389,No,0,0,01-01-2022 20:00,1.275
1,16500,16500,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,-,...,-,-,-,26.508333,92.116389,No,0,0,27-02-2022 00:00,0.502

----------------------------------------------------------------------
FILE: data/raw/darrang_api2_raw.csv
----------------------------------------------------------------------
Shape: (626, 24)

Columns:
 - _id
 - SlNo
 - Station
 - Agency
 - State LGD Code
 - State
 - District LGD Code
 - District
 - Tehsil
 - Block
 - Village
 - River
 - Basin
 - Tributary
 - Subtributary
 - SubSubtributary
 - Local River
 - Latitude
 - Longitude
 - Is_DischargeDataAvailable
 - RL_of_zeroGauge
 - MeanSeaLevel
 - Data Acquisition Time
 - River Water Level Telemetry Hourly (meter)

First 2 rows:

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Is_DischargeDataAvailable,RL_of_zeroGauge,MeanSeaLevel,Data Acquisition Time,River Water Level Telemetry Hourly (meter)
0,1,1,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,-,...,-,-,-,26.508333,92.116389,No,0,0,07-05-2026 20:00,60.937
1,2,2,NH15 Crossing Fakirpara Tangni,Assam,18,Assam,283,DARRANG,-,-,...,-,-,-,26.508333,92.116389,No,0,0,07-05-2026 21:00,60.941

In [3]:
# ============================================================
# STEP 4.10.3 — LOAD EXISTING VERIFIED FINAL ML DATASET
# ============================================================

import pandas as pd

FINAL_PATH = "data/cleaned/final_ml_dataset.csv"

df = pd.read_csv(FINAL_PATH)

print("=" * 70)
print("STEP 4.10.3 — FINAL ML DATASET LOADED")
print("=" * 70)

print("File   :", FINAL_PATH)
print("Shape  :", df.shape)

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i:>2}. {col}")

print("\n" + "=" * 70)
print("DATASET RECOVERY CHECK")
print("=" * 70)

print("Rows    :", len(df))
print("Columns :", len(df.columns))

print("\nMissing values:")
print(df.isna().sum())

print("\nSTEP 4.10.3 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.10.3 — FINAL ML DATASET LOADED
======================================================================
File   : data/cleaned/final_ml_dataset.csv
Shape  : (7309, 21)

Columns:
 1. Data Acquisition Time
 2. Current_Water_Level
 3. Month
 4. Hour
 5. DayOfYear
 6. WaterLevel_Lag_1h
 7. WaterLevel_Lag_3h
 8. WaterLevel_Lag_6h
 9. WaterLevel_Lag_12h
10. WaterLevel_Lag_24h
11. WaterLevel_RollingMean_6h
12. WaterLevel_RollingMean_12h
13. WaterLevel_RollingMean_24h
14. WaterLevel_RollingMax_24h
15. WaterLevel_RollingMin_24h
16. WaterLevel_Change_1h
17. WaterLevel_Change_3h
18. WaterLevel_Change_6h
19. WaterLevel_Change_12h
20. WaterLevel_Change_24h
21. High_Water_6h

======================================================================
DATASET RECOVERY CHECK
======================================================================
Rows    : 7309
Columns : 21

Missing values:
Data Acquisition Time         0
Current_Water_Level           0
Month                         0
Hour                          0
DayOfYear                     0
WaterLevel_Lag_1h             0
WaterLevel_Lag_3h             0
WaterLevel_Lag_6h             0
WaterLevel_Lag_12h            0
WaterLevel_Lag_24h            0
WaterLevel_RollingMean_6h     0
WaterLevel_RollingMean_12h    0
WaterLevel_RollingMean_24h    0
WaterLevel_RollingMax_24h     0
WaterLevel_RollingMin_24h     0
WaterLevel_Change_1h          0
WaterLevel_Change_3h          0
WaterLevel_Change_6h          0
WaterLevel_Change_12h         0
WaterLevel_Change_24h         0
High_Water_6h                 0
dtype: int64

STEP 4.10.3 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [4]:
# ================================================================
# STEP 4.11 — REMAINING ROLLING FEATURES FORENSIC TEST
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.11 — REMAINING ROLLING FEATURES FORENSIC TEST")
print("=" * 70)

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"

# ---------------------------------------------------------------
# SAFETY COPY
# ---------------------------------------------------------------

work = df.copy()

work[TIME_COL] = pd.to_datetime(work[TIME_COL])

work = (
    work
    .sort_values(TIME_COL)
    .set_index(TIME_COL)
)

rolling_features = [
    "WaterLevel_RollingMean_12h",
    "WaterLevel_RollingMean_24h",
    "WaterLevel_RollingMax_24h",
    "WaterLevel_RollingMin_24h"
]

print("\nFeatures to validate:")
for feature in rolling_features:
    print(" -", feature)


# ---------------------------------------------------------------
# CANDIDATE TEST FUNCTION
# ---------------------------------------------------------------

def test_candidate(
    feature,
    window,
    aggregation,
    closed,
    min_periods
):

    rolling_obj = work[VALUE_COL].rolling(
        window=window,
        closed=closed,
        min_periods=min_periods
    )

    if aggregation == "mean":
        candidate = rolling_obj.mean()

    elif aggregation == "max":
        candidate = rolling_obj.max()

    elif aggregation == "min":
        candidate = rolling_obj.min()

    stored = work[feature]

    valid = stored.notna() & candidate.notna()

    if valid.sum() == 0:
        return None

    stored_v = stored.loc[valid]
    candidate_v = candidate.loc[valid]

    diff = (
        stored_v - candidate_v
    ).abs()

    match = np.isclose(
        stored_v,
        candidate_v,
        rtol=1e-10,
        atol=1e-10
    )

    return {
        "Feature": feature,
        "Window": window,
        "Aggregation": aggregation,
        "Closed": closed,
        "Min_Periods": min_periods,
        "Checked": int(valid.sum()),
        "Matching": int(match.sum()),
        "Mismatching": int((~match).sum()),
        "Match_Rate_%": match.mean() * 100,
        "Mean_Abs_Difference": diff.mean(),
        "Median_Abs_Difference": diff.median(),
        "Maximum_Difference": diff.max()
    }


# ---------------------------------------------------------------
# TEST CANDIDATES
# ---------------------------------------------------------------

results = []

configs = {
    "12h": ["mean"],
    "24h": ["mean", "max", "min"]
}

for feature in rolling_features:

    print("\n" + "-" * 70)
    print(feature)
    print("-" * 70)

    if "12h" in feature:
        window = "12h"
    else:
        window = "24h"

    aggregation = (
        "mean" if "Mean" in feature
        else "max" if "Max" in feature
        else "min"
    )

    # Test the same semantic family that STEP 4.10 proved:
    # time-based rolling + closed=right.
    #
    # We test min_periods from 1 through full window
    # to identify the exact stored semantics.

    hours = int(window.replace("h", ""))

    for min_periods in range(1, hours + 1):

        result = test_candidate(
            feature=feature,
            window=window,
            aggregation=aggregation,
            closed="right",
            min_periods=min_periods
        )

        if result is not None:
            results.append(result)


# ---------------------------------------------------------------
# RESULTS
# ---------------------------------------------------------------

results_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("ALL CANDIDATES — RANKED")
print("=" * 70)

results_df = results_df.sort_values(
    [
        "Feature",
        "Match_Rate_%",
        "Mean_Abs_Difference"
    ],
    ascending=[
        True,
        False,
        True
    ]
)

print(
    results_df.to_string(index=False)
)


# ---------------------------------------------------------------
# BEST CANDIDATE PER FEATURE
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("BEST CANDIDATE PER FEATURE")
print("=" * 70)

best = (
    results_df
    .sort_values(
        [
            "Feature",
            "Match_Rate_%",
            "Mean_Abs_Difference"
        ],
        ascending=[
            True,
            False,
            True
        ]
    )
    .groupby("Feature")
    .head(1)
)

print(
    best.to_string(index=False)
)


# ---------------------------------------------------------------
# SAFETY CHECK
# ---------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Working shape     :", work.shape)

print("\nSTEP 4.11 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.11 — REMAINING ROLLING FEATURES FORENSIC TEST
======================================================================

Features to validate:
 - WaterLevel_RollingMean_12h
 - WaterLevel_RollingMean_24h
 - WaterLevel_RollingMax_24h
 - WaterLevel_RollingMin_24h

----------------------------------------------------------------------
WaterLevel_RollingMean_12h
----------------------------------------------------------------------

----------------------------------------------------------------------
WaterLevel_RollingMean_24h
----------------------------------------------------------------------

----------------------------------------------------------------------
WaterLevel_RollingMax_24h
----------------------------------------------------------------------

----------------------------------------------------------------------
WaterLevel_RollingMin_24h
----------------------------------------------------------------------

======================================================================
ALL CANDIDATES — RANKED
======================================================================
                   Feature Window Aggregation Closed  Min_Periods  Checked  Matching  Mismatching  Match_Rate_%  Mean_Abs_Difference  Median_Abs_Difference  Maximum_Difference
 WaterLevel_RollingMax_24h    24h         max  right           24     3586      3586            0    100.000000         0.000000e+00                    0.0        0.000000e+00
 WaterLevel_RollingMax_24h    24h         max  right           23     3991      3961           30     99.248309         1.374843e-03                    0.0        4.614000e+00
 WaterLevel_RollingMax_24h    24h         max  right           22     4300      4243           57     98.674419         2.480000e-03                    0.0        4.614000e+00
 WaterLevel_RollingMax_24h    24h         max  right           21     4538      4469           69     98.479506         6.511018e-03                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           20     4748      4668           80     98.315080         1.113837e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           19     5026      4921          105     97.910864         1.063888e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           18     5271      5142          129     97.552647         1.027509e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           17     5467      5321          146     97.329431         1.006640e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           16     5614      5456          158     97.185607         9.928215e-03                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           15     5810      5636          174     97.005164         1.054750e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           14     5962      5760          202     96.611875         1.045438e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           13     6126      5899          227     96.294483         1.108341e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           12     6267      6024          243     96.122547         1.097399e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           11     6387      6126          261     95.913574         1.091217e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right           10     6505      6225          280     95.695619         1.088437e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            9     6608      6310          298     95.490315         1.089718e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            8     6720      6399          321     95.223214         1.389237e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            7     6815      6469          346     94.922964         1.686763e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            6     6910      6536          374     94.587554         2.308707e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            5     6999      6598          401     94.270610         2.652612e-02                    0.0        1.840000e+01
 WaterLevel_RollingMax_24h    24h         max  right            4     7086      6657          429     93.945809         3.204885e-02                    0.0        1.900000e+01
 WaterLevel_RollingMax_24h    24h         max  right            3     7167      6713          454     93.665411         3.761271e-02                    0.0        2.010000e+01
 WaterLevel_RollingMax_24h    24h         max  right            2     7241      6765          476     93.426322         4.433772e-02                    0.0        2.010000e+01
 WaterLevel_RollingMax_24h    24h         max  right            1     7309      6809          500     93.159119         5.027718e-02                    0.0        2.010000e+01
WaterLevel_RollingMean_12h    12h        mean  right           12     4429      4429            0    100.000000         6.726513e-16                    0.0        2.131628e-14
WaterLevel_RollingMean_12h    12h        mean  right           11     5123      4645          478     90.669530         1.323736e-02                    0.0        3.240583e+00
WaterLevel_RollingMean_12h    12h        mean  right           10     5509      4798          711     87.093846         2.836959e-02                    0.0        7.146233e+00
WaterLevel_RollingMean_12h    12h        mean  right            9     5794      4884          910     84.294097         4.452029e-02                    0.0        7.146233e+00
WaterLevel_RollingMean_12h    12h        mean  right            8     6165      5026         1139     81.524736         6.098160e-02                    0.0        7.146233e+00
WaterLevel_RollingMean_12h    12h        mean  right            7     6450      5111         1339     79.240310         6.987116e-02                    0.0        7.146233e+00
WaterLevel_RollingMean_12h    12h        mean  right            6     6636      5174         1462     77.968656         7.608924e-02                    0.0        8.005750e+00
WaterLevel_RollingMean_12h    12h        mean  right            5     6852      5272         1580     76.941039         8.880720e-02                    0.0        1.443720e+01
WaterLevel_RollingMean_12h    12h        mean  right            4     6996      5314         1682     75.957690         9.881908e-02                    0.0        1.443720e+01
WaterLevel_RollingMean_12h    12h        mean  right            3     7115      5344         1771     75.108925         1.062672e-01                    0.0        1.443720e+01
WaterLevel_RollingMean_12h    12h        mean  right            2     7222      5368         1854     74.328441         1.132863e-01                    0.0        1.443720e+01
WaterLevel_RollingMean_12h    12h        mean  right            1     7309      5386         1923     73.689971         1.222890e-01                    0.0        1.600000e+01
WaterLevel_RollingMean_24h    24h        mean  right           24     3586      3586            0    100.000000         7.720168e-16                    0.0        2.131628e-14
WaterLevel_RollingMean_24h    24h        mean  right           23     3991      3705          286     92.833876         3.819212e-03                    0.0        1.322750e+00
WaterLevel_RollingMean_24h    24h        mean  right           22     4300      3808          492     88.558140         1.198537e-02                    0.0        2.646208e+00
WaterLevel_RollingMean_24h    24h        mean  right           21     4538      3866          672     85.191714         2.676706e-02                    0.0        3.784440e+00
WaterLevel_RollingMean_24h    24h        mean  right           20     4748      3920          828     82.561078         3.445987e-02                    0.0        3.784440e+00
WaterLevel_RollingMean_24h    24h        mean  right           19     5026      3982         1044     79.228014         4.602393e-02                    0.0        3.784440e+00
WaterLevel_RollingMean_24h    24h        mean  right           18     5271      4043         1228     76.702713         5.994279e-02                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           17     5467      4101         1366     75.013719         7.311842e-02                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           16     5614      4137         1477     73.690773         8.367221e-02                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           15     5810      4203         1607     72.340792         1.006922e-01                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           14     5962      4242         1720     71.150621         1.097446e-01                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           13     6126      4289         1837     70.013059         1.189945e-01                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           12     6267      4331         1936     69.108026         1.259102e-01                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           11     6387      4371         2016     68.435885         1.300383e-01                    0.0        5.739251e+00
WaterLevel_RollingMean_24h    24h        mean  right           10     6505      4401         2104     67.655650         1.361351e-01                    0.0        5.839481e+00
WaterLevel_RollingMean_24h    24h        mean  right            9     6608      4432         2176     67.070218         1.399592e-01                    0.0        5.839481e+00
WaterLevel_RollingMean_24h    24h        mean  right            8     6720      4464         2256     66.428571         1.460543e-01                    0.0        5.839481e+00
WaterLevel_RollingMean_24h    24h        mean  right            7     6815      4485         2330     65.810712         1.515715e-01                    0.0        5.839481e+00
WaterLevel_RollingMean_24h    24h        mean  right            6     6910      4505         2405     65.195369         1.616709e-01                    0.0        7.307143e+00
WaterLevel_RollingMean_24h    24h        mean  right            5     6999      4526         2473     64.666381         1.699836e-01                    0.0        8.373333e+00
WaterLevel_RollingMean_24h    24h        mean  right            4     7086      4543         2543     64.112334         1.790402e-01                    0.0        1.132024e+01
WaterLevel_RollingMean_24h    24h        mean  right            3     7167      4558         2609     63.597042         1.885558e-01                    0.0        1.431429e+01
WaterLevel_RollingMean_24h    24h        mean  right            2     7241      4573         2668     63.154260         1.986588e-01                    0.0        1.640909e+01
WaterLevel_RollingMean_24h    24h        mean  right            1     7309      4587         2722     62.758243         2.097600e-01                    0.0        1.823636e+01
 WaterLevel_RollingMin_24h    24h         min  right           24     3586      3586            0    100.000000         0.000000e+00                    0.0        0.000000e+00
 WaterLevel_RollingMin_24h    24h         min  right           23     3991      3972           19     99.523929         1.263885e-02                    0.0        3.174600e+01
 WaterLevel_RollingMin_24h    24h         min  right           22     4300      4253           47     98.906977         2.592775e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           21     4538      4450           88     98.060820         3.042375e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           20     4748      4626          122     97.430497         3.444401e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           19     5026      4856          170     96.617589         3.804533e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           18     5271      5053          218     95.864162         4.415970e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           17     5467      5199          268     95.097860         4.916668e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           16     5614      5301          313     94.424653         5.447062e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           15     5810      5444          366     93.700516         6.422158e-02                    0.0        3.176300e+01
 WaterLevel_RollingMin_24h    24h         min  right           14     5962      5538          424     92.888293         7.776856e-02                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right           13     6126      5652          474     92.262488         8.966329e-02                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right           12     6267      5747          520     91.702569         9.429274e-02                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right           11     6387      5825          562     91.200877         9.895748e-02                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right           10     6505      5888          617     90.514988         1.053352e-01                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right            9     6608      5944          664     89.951574         1.115499e-01                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right            8     6720      6000          720     89.285714         1.175842e-01                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right            7     6815      6034          781     88.539985         1.243422e-01                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right            6     6910      6071          839     87.858177         1.312307e-01                    0.0        4.758200e+01
 WaterLevel_RollingMin_24h    24h         min  right            5     6999      6104          895     87.212459         1.528446e-01                    0.0        4.804200e+01
 WaterLevel_RollingMin_24h    24h         min  right            4     7086      6136          950     86.593283         1.670125e-01                    0.0        4.804200e+01
 WaterLevel_RollingMin_24h    24h         min  right            3     7167      6162         1005     85.977396         1.808872e-01                    0.0        4.804200e+01
 WaterLevel_RollingMin_24h    24h         min  right            2     7241      6190         1051     85.485430         1.946333e-01                    0.0        4.804200e+01
 WaterLevel_RollingMin_24h    24h         min  right            1     7309      6215         1094     85.032152         2.083162e-01                    0.0        4.804200e+01

======================================================================
BEST CANDIDATE PER FEATURE
======================================================================
                   Feature Window Aggregation Closed  Min_Periods  Checked  Matching  Mismatching  Match_Rate_%  Mean_Abs_Difference  Median_Abs_Difference  Maximum_Difference
 WaterLevel_RollingMax_24h    24h         max  right           24     3586      3586            0         100.0         0.000000e+00                    0.0        0.000000e+00
WaterLevel_RollingMean_12h    12h        mean  right           12     4429      4429            0         100.0         6.726513e-16                    0.0        2.131628e-14
WaterLevel_RollingMean_24h    24h        mean  right           24     3586      3586            0         100.0         7.720168e-16                    0.0        2.131628e-14
 WaterLevel_RollingMin_24h    24h         min  right           24     3586      3586            0         100.0         0.000000e+00                    0.0        0.000000e+00

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Working shape     : (7309, 20)

STEP 4.11 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [5]:
# ============================================================
# STEP 4.12 — HIGH WATER 6H TARGET FORENSIC VALIDATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.12 — HIGH WATER 6H TARGET FORENSIC VALIDATION")
print("=" * 70)

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"
TARGET_COL = "High_Water_6h"

test = df.copy()

test[TIME_COL] = pd.to_datetime(test[TIME_COL])

test = (
    test
    .sort_values(TIME_COL)
    .reset_index(drop=True)
)

print("\nDataset:")
print("Rows    :", len(test))
print("Columns :", len(test.columns))

print("\nTarget distribution:")
print(test[TARGET_COL].value_counts(dropna=False).sort_index())

print("\nTarget dtype:")
print(test[TARGET_COL].dtype)


# ------------------------------------------------------------
# Candidate target semantics
# ------------------------------------------------------------

# Candidate 1:
# Future 6-hour maximum INCLUDING current timestamp
future_max_including_current = (
    test[VALUE_COL]
    .rolling(
        window=7,
        min_periods=7
    )
    .max()
    .shift(-6)
)

# Candidate 2:
# Future 6-hour maximum AFTER current timestamp
future_values = pd.concat(
    [
        test[VALUE_COL].shift(-i)
        for i in range(1, 7)
    ],
    axis=1
)

future_max_excluding_current = future_values.max(axis=1)

# Candidate 3:
# Future 6-hour minimum AFTER current timestamp
future_min_excluding_current = future_values.min(axis=1)


# ------------------------------------------------------------
# Compare candidates
# ------------------------------------------------------------

candidates = {
    "future_max_including_current": future_max_including_current,
    "future_max_excluding_current": future_max_excluding_current,
    "future_min_excluding_current": future_min_excluding_current
}

results = []

for name, candidate in candidates.items():

    valid = (
        test[TARGET_COL].notna()
        & candidate.notna()
    )

    stored = test.loc[valid, TARGET_COL]
    cand = candidate.loc[valid]

    # Exact equality
    match = np.isclose(
        stored,
        cand,
        rtol=1e-10,
        atol=1e-10
    )

    diff = (
        stored - cand
    ).abs()

    results.append({
        "Candidate": name,
        "Checked": int(valid.sum()),
        "Matching": int(match.sum()),
        "Mismatching": int((~match).sum()),
        "Match_Rate_%": match.mean() * 100,
        "Mean_Abs_Difference": diff.mean(),
        "Maximum_Difference": diff.max()
    })


results_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("TARGET CANDIDATES")
print("=" * 70)

print(
    results_df.to_string(index=False)
)


# ------------------------------------------------------------
# Target transition / future availability
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET EDGE CHECK")
print("=" * 70)

print(
    "Last 10 timestamps and target:"
)

print(
    test[
        [TIME_COL, VALUE_COL, TARGET_COL]
    ].tail(10).to_string(index=False)
)


# ------------------------------------------------------------
# Safety
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Test shape        :", test.shape)

print("\nSTEP 4.12 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.12 — HIGH WATER 6H TARGET FORENSIC VALIDATION
======================================================================

Dataset:
Rows    : 7309
Columns : 21

Target distribution:
High_Water_6h
0.0    5845
1.0    1464
Name: count, dtype: int64

Target dtype:
float64

======================================================================
TARGET CANDIDATES
======================================================================
                   Candidate  Checked  Matching  Mismatching  Match_Rate_%  Mean_Abs_Difference  Maximum_Difference
future_max_including_current     7303         0         7303           0.0            21.979056              61.636
future_max_excluding_current     7308         0         7308           0.0            21.844702              61.636
future_min_excluding_current     7308         0         7308           0.0            20.129576              61.497

======================================================================
TARGET EDGE CHECK
======================================================================
Last 10 timestamps and target:
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2026-06-03 08:00:00               60.948            1.0
  2026-06-03 09:00:00               60.957            1.0
  2026-06-03 10:00:00               60.957            1.0
  2026-06-03 11:00:00               60.962            1.0
  2026-06-03 12:00:00               60.956            1.0
  2026-06-03 13:00:00               60.959            1.0
  2026-06-03 14:00:00               60.955            1.0
  2026-06-03 15:00:00               60.952            1.0
  2026-06-03 16:00:00               60.957            1.0
  2026-06-03 17:00:00               60.965            1.0

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Test shape        : (7309, 21)

STEP 4.12 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [6]:
# ============================================================
# STEP 4.13 — HIGH WATER TARGET RULE FORENSIC ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.13 — HIGH WATER 6H TARGET RULE FORENSIC ANALYSIS")
print("=" * 70)

test = df.copy()

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"
TARGET_COL = "High_Water_6h"

test[TIME_COL] = pd.to_datetime(test[TIME_COL])
test = test.sort_values(TIME_COL).reset_index(drop=True)

# ------------------------------------------------------------
# BASIC TARGET / WATER-LEVEL ANALYSIS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — TARGET GROUP WATER-LEVEL DISTRIBUTION")
print("=" * 70)

for target in [0, 1]:

    subset = test.loc[
        test[TARGET_COL] == target,
        VALUE_COL
    ]

    print(f"\nTarget = {target}")
    print("Count :", len(subset))
    print("Min   :", subset.min())
    print("Q1    :", subset.quantile(0.25))
    print("Median:", subset.median())
    print("Q3    :", subset.quantile(0.75))
    print("Max   :", subset.max())


# ------------------------------------------------------------
# CANDIDATE THRESHOLD TEST
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — CURRENT WATER LEVEL THRESHOLD TEST")
print("=" * 70)

thresholds = np.arange(
    np.floor(test[VALUE_COL].min()),
    np.ceil(test[VALUE_COL].max()) + 0.1,
    0.5
)

threshold_results = []

for threshold in thresholds:

    candidate = (
        test[VALUE_COL] >= threshold
    ).astype(int)

    valid = candidate.notna() & test[TARGET_COL].notna()

    match = (
        candidate[valid].values
        == test.loc[valid, TARGET_COL].values
    )

    threshold_results.append({
        "Threshold": threshold,
        "Matching": int(match.sum()),
        "Mismatching": int((~match).sum()),
        "Match_Rate_%": match.mean() * 100
    })

threshold_df = pd.DataFrame(threshold_results)

print(
    threshold_df
    .sort_values(
        "Match_Rate_%",
        ascending=False
    )
    .head(15)
    .to_string(index=False)
)


# ------------------------------------------------------------
# PART C — TARGET BY WATER-LEVEL BINS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — TARGET RATE BY WATER-LEVEL RANGE")
print("=" * 70)

test["WaterLevel_Bin"] = pd.cut(
    test[VALUE_COL],
    bins=20
)

bin_summary = (
    test
    .groupby("WaterLevel_Bin", observed=False)[TARGET_COL]
    .agg(
        Rows="count",
        Positive_Count="sum",
        Positive_Rate="mean"
    )
)

bin_summary["Positive_Rate_%"] = (
    bin_summary["Positive_Rate"] * 100
)

print(
    bin_summary[
        ["Rows", "Positive_Count", "Positive_Rate_%"]
    ].to_string()
)


# ------------------------------------------------------------
# PART D — HIGH TARGET EXAMPLES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — SAMPLE TARGET = 1 ROWS")
print("=" * 70)

print(
    test.loc[
        test[TARGET_COL] == 1,
        [
            TIME_COL,
            VALUE_COL,
            TARGET_COL
        ]
    ].head(20).to_string(index=False)
)


# ------------------------------------------------------------
# PART E — LOW TARGET EXAMPLES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART E — SAMPLE TARGET = 0 ROWS")
print("=" * 70)

print(
    test.loc[
        test[TARGET_COL] == 0,
        [
            TIME_COL,
            VALUE_COL,
            TARGET_COL
        ]
    ].head(20).to_string(index=False)
)


# ------------------------------------------------------------
# SAFETY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Test shape        :", test.shape)

print("\nSTEP 4.13 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.13 — HIGH WATER 6H TARGET RULE FORENSIC ANALYSIS
======================================================================

======================================================================
PART A — TARGET GROUP WATER-LEVEL DISTRIBUTION
======================================================================

Target = 0
Count : 5845
Min   : 0.223
Q1    : 1.243
Median: 5.763
Q3    : 32.7
Max   : 32.701

Target = 1
Count : 1464
Min   : 11.4
Q1    : 60.57175
Median: 60.905
Q3    : 61.049
Max   : 62.636

======================================================================
PART B — CURRENT WATER LEVEL THRESHOLD TEST
======================================================================
 Threshold  Matching  Mismatching  Match_Rate_%
      48.0      7270           39     99.466411
      48.5      7270           39     99.466411
      47.0      7270           39     99.466411
      45.0      7270           39     99.466411
      46.5      7270           39     99.466411
      46.0      7270           39     99.466411
      45.5      7270           39     99.466411
      43.0      7270           39     99.466411
      59.0      7270           39     99.466411
      58.0      7270           39     99.466411
      57.5      7270           39     99.466411
      57.0      7270           39     99.466411
      58.5      7270           39     99.466411
      60.0      7270           39     99.466411
      59.5      7270           39     99.466411

======================================================================
PART C — TARGET RATE BY WATER-LEVEL RANGE
======================================================================
                  Rows  Positive_Count  Positive_Rate_%
WaterLevel_Bin
(0.161, 3.344]    2484             0.0         0.000000
(3.344, 6.464]    1510             0.0         0.000000
(6.464, 9.585]       0             0.0              NaN
(9.585, 12.706]    129            28.0        21.705426
(12.706, 15.826]   146            11.0         7.534247
(15.826, 18.947]     0             0.0              NaN
(18.947, 22.068]     0             0.0              NaN
(22.068, 25.188]     0             0.0              NaN
(25.188, 28.309]     0             0.0              NaN
(28.309, 31.43]      0             0.0              NaN
(31.43, 34.55]    1615             0.0         0.000000
(34.55, 37.671]      0             0.0              NaN
(37.671, 40.791]     0             0.0              NaN
(40.791, 43.912]     0             0.0              NaN
(43.912, 47.033]     0             0.0              NaN
(47.033, 50.153]     0             0.0              NaN
(50.153, 53.274]     0             0.0              NaN
(53.274, 56.395]     0             0.0              NaN
(56.395, 59.515]     0             0.0              NaN
(59.515, 62.636]  1425          1425.0       100.000000

======================================================================
PART D — SAMPLE TARGET = 1 ROWS
======================================================================
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-01-04 18:00:00               12.900            1.0
  2025-01-04 19:00:00               12.800            1.0
  2025-01-04 20:00:00               12.800            1.0
  2025-01-04 23:00:00               12.700            1.0
  2025-01-05 01:00:00               60.698            1.0
  2025-01-05 02:00:00               60.701            1.0
  2025-01-05 04:00:00               60.714            1.0
  2025-01-05 05:00:00               60.714            1.0
  2025-01-05 06:00:00               60.708            1.0
  2025-01-05 07:00:00               60.672            1.0
  2025-01-05 08:00:00               60.654            1.0
  2025-01-05 10:00:00               60.619            1.0
  2025-01-05 11:00:00               60.636            1.0
  2025-01-05 12:00:00               60.579            1.0
  2025-01-05 14:00:00               60.631            1.0
  2025-01-05 15:00:00               60.657            1.0
  2025-01-05 16:00:00               60.652            1.0
  2025-01-05 17:00:00               60.643            1.0
  2025-01-05 18:00:00               60.669            1.0
  2025-01-05 23:00:00               60.742            1.0

======================================================================
PART E — SAMPLE TARGET = 0 ROWS
======================================================================
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2022-01-04 04:00:00             0.283000            0.0
  2022-01-04 05:00:00             0.305000            0.0
  2022-01-04 07:00:00             0.331727            0.0
  2022-01-04 10:00:00             0.371818            0.0
  2022-01-04 13:00:00             0.411909            0.0
  2022-01-04 15:00:00             0.438636            0.0
  2022-01-04 16:00:00             0.452000            0.0
  2022-01-04 17:00:00             0.525000            0.0
  2022-01-09 00:00:00             0.524000            0.0
  2022-01-09 01:00:00             0.531000            0.0
  2022-01-09 02:00:00             0.537000            0.0
  2022-01-09 03:00:00             0.534000            0.0
  2022-01-09 04:00:00             0.531500            0.0
  2022-01-09 05:00:00             0.529000            0.0
  2022-01-09 06:00:00             0.522500            0.0
  2022-01-09 07:00:00             0.516000            0.0
  2022-01-09 08:00:00             0.515000            0.0
  2022-01-09 09:00:00             0.515500            0.0
  2022-01-09 10:00:00             0.516000            0.0
  2022-01-09 11:00:00             0.521000            0.0

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Test shape        : (7309, 22)

STEP 4.13 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [8]:
# ============================================================
# STEP 4.14 — EXACT HIGH_WATER_6H TARGET SEMANTICS
# CORRECTED VERSION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.14 — EXACT HIGH_WATER_6H TARGET SEMANTICS")
print("=" * 70)

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"
TARGET_COL = "High_Water_6h"
THRESHOLD = 60.0

test = df.copy()

test[TIME_COL] = pd.to_datetime(test[TIME_COL])

test = (
    test
    .sort_values(TIME_COL)
    .reset_index(drop=True)
)

target = test[TARGET_COL].to_numpy(dtype=int)


# ------------------------------------------------------------
# CANDIDATE 1 — CURRENT LEVEL >= 60
# ------------------------------------------------------------

current_high = (
    test[VALUE_COL] >= THRESHOLD
).astype(int).to_numpy()


# ------------------------------------------------------------
# CANDIDATE 2 — NEXT 6 ROWS >= 60
# ------------------------------------------------------------

future_6rows = pd.concat(
    [
        test[VALUE_COL].shift(-i)
        for i in range(1, 7)
    ],
    axis=1
)

future_6rows_high = (
    future_6rows >= THRESHOLD
).any(axis=1).astype(int).to_numpy()


# ------------------------------------------------------------
# CANDIDATE 3 — CURRENT + NEXT 6 ROWS >= 60
# ------------------------------------------------------------

current_plus_6rows_high = (
    pd.concat(
        [
            test[VALUE_COL].shift(-i)
            for i in range(0, 7)
        ],
        axis=1
    )
    .ge(THRESHOLD)
    .any(axis=1)
    .astype(int)
    .to_numpy()
)


# ------------------------------------------------------------
# CANDIDATE 4 — FUTURE 6 HOURS >= 60
# ------------------------------------------------------------

timestamps = test[TIME_COL].to_numpy()
values = test[VALUE_COL].to_numpy()

future_6h_high = np.zeros(len(test), dtype=int)

for i in range(len(test)):

    current_time = timestamps[i]

    mask = (
        (test[TIME_COL] > current_time)
        &
        (
            test[TIME_COL]
            <= current_time + pd.Timedelta(hours=6)
        )
    )

    if mask.any():
        future_6h_high[i] = int(
            (test.loc[mask, VALUE_COL] >= THRESHOLD).any()
        )


# ------------------------------------------------------------
# CANDIDATE 5 — CURRENT + FUTURE 6 HOURS >= 60
# ------------------------------------------------------------

current_plus_future_6h = (
    (
        test[VALUE_COL].to_numpy() >= THRESHOLD
    )
    |
    (future_6h_high == 1)
).astype(int)


# ------------------------------------------------------------
# COMPARE
# ------------------------------------------------------------

candidates = {
    "Current >= 60": current_high,
    "Next 6 rows >= 60": future_6rows_high,
    "Current + next 6 rows >= 60": current_plus_6rows_high,
    "Future 6h >= 60": future_6h_high,
    "Current + future 6h >= 60": current_plus_future_6h
}

results = []

for name, candidate in candidates.items():

    match = candidate == target

    results.append({
        "Candidate": name,
        "Checked": len(test),
        "Matching": int(match.sum()),
        "Mismatching": int((~match).sum()),
        "Match_Rate_%": round(
            match.mean() * 100,
            6
        )
    })

results_df = pd.DataFrame(results)

print("\n" + "=" * 70)
print("TARGET SEMANTICS RESULTS")
print("=" * 70)

print(
    results_df
    .sort_values("Match_Rate_%", ascending=False)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 39 CURRENT-THRESHOLD MISMATCHES
# ------------------------------------------------------------

threshold_mismatch = (
    current_high != target
)

mismatch_view = test.loc[
    threshold_mismatch,
    [
        TIME_COL,
        VALUE_COL,
        TARGET_COL
    ]
].copy()

mismatch_view["Future_6h_High"] = future_6h_high[
    threshold_mismatch
]

print("\n" + "=" * 70)
print("CURRENT >= 60 MISMATCHES")
print("=" * 70)

print(
    mismatch_view.to_string(index=False)
)


# ------------------------------------------------------------
# BEST CANDIDATE
# ------------------------------------------------------------

best_row = results_df.loc[
    results_df["Match_Rate_%"].idxmax()
]

print("\n" + "=" * 70)
print("BEST CANDIDATE")
print("=" * 70)

print(best_row.to_string())


# ------------------------------------------------------------
# SAFETY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Test shape        :", test.shape)

print("\nSTEP 4.14 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.14 — EXACT HIGH_WATER_6H TARGET SEMANTICS
======================================================================

======================================================================
TARGET SEMANTICS RESULTS
======================================================================
                  Candidate  Checked  Matching  Mismatching  Match_Rate_%
  Current + future 6h >= 60     7309      7304            5     99.931591
            Future 6h >= 60     7309      7282           27     99.630592
Current + next 6 rows >= 60     7309      7276           33     99.548502
              Current >= 60     7309      7270           39     99.466411
          Next 6 rows >= 60     7309      7264           45     99.384321

======================================================================
CURRENT >= 60 MISMATCHES
======================================================================
Data Acquisition Time  Current_Water_Level  High_Water_6h  Future_6h_High
  2025-01-04 18:00:00                 12.9            1.0               0
  2025-01-04 19:00:00                 12.8            1.0               1
  2025-01-04 20:00:00                 12.8            1.0               1
  2025-01-04 23:00:00                 12.7            1.0               1
  2025-02-04 18:00:00                 13.0            1.0               1
  2025-03-04 20:00:00                 12.7            1.0               1
  2025-03-04 23:00:00                 12.7            1.0               1
  2025-04-04 18:00:00                 12.9            1.0               0
  2025-04-04 19:00:00                 12.7            1.0               1
  2025-04-04 20:00:00                 12.0            1.0               1
  2025-04-04 23:00:00                 11.5            1.0               1
  2025-05-04 18:00:00                 13.0            1.0               1
  2025-05-04 19:00:00                 12.8            1.0               1
  2025-05-04 21:00:00                 12.4            1.0               1
  2025-05-04 22:00:00                 12.7            1.0               1
  2025-06-04 18:00:00                 12.8            1.0               0
  2025-06-04 19:00:00                 12.7            1.0               0
  2025-06-04 20:00:00                 12.7            1.0               1
  2025-06-04 21:00:00                 12.7            1.0               1
  2025-06-04 22:00:00                 12.7            1.0               1
  2025-06-04 23:00:00                 12.7            1.0               1
  2025-07-04 18:00:00                 11.9            1.0               1
  2025-07-04 19:00:00                 12.7            1.0               1
  2025-07-04 20:00:00                 12.3            1.0               1
  2025-07-04 21:00:00                 12.7            1.0               1
  2025-07-04 22:00:00                 12.7            1.0               1
  2025-07-04 23:00:00                 11.4            1.0               1
  2025-08-04 20:00:00                 12.7            1.0               1
  2025-10-04 20:00:00                 12.6            1.0               1
  2025-10-04 23:00:00                 12.4            1.0               1
  2025-11-04 20:00:00                 12.4            1.0               1
  2025-11-04 22:00:00                 12.7            1.0               1
  2025-11-04 23:00:00                 13.0            1.0               1
  2025-12-04 18:00:00                 13.0            1.0               0
  2025-12-04 19:00:00                 12.8            1.0               1
  2025-12-04 20:00:00                 12.7            1.0               1
  2025-12-04 21:00:00                 12.7            1.0               1
  2025-12-04 22:00:00                 12.7            1.0               1
  2025-12-04 23:00:00                 12.7            1.0               1

======================================================================
BEST CANDIDATE
======================================================================
Candidate       Current + future 6h >= 60
Checked                              7309
Matching                             7304
Mismatching                             5
Match_Rate_%                    99.931591

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Test shape        : (7309, 21)

STEP 4.14 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [9]:
# ============================================================
# STEP 4.15 — INVESTIGATE 5 TARGET MISMATCHES
# ============================================================

print("=" * 70)
print("STEP 4.15 — INVESTIGATING TARGET MISMATCHES")
print("=" * 70)

# Rebuild best candidate
current_plus_future_6h = (
    (
        test[VALUE_COL].to_numpy() >= 60.0
    )
    |
    (future_6h_high == 1)
).astype(int)

mismatch_mask = (
    current_plus_future_6h
    != test[TARGET_COL].to_numpy()
)

mismatches = test.loc[
    mismatch_mask,
    [
        TIME_COL,
        VALUE_COL,
        TARGET_COL
    ]
].copy()

mismatches["Reconstructed_Target"] = (
    current_plus_future_6h[mismatch_mask]
)

print("\n5 MISMATCH ROWS:")
print(
    mismatches.to_string(index=False)
)

# ------------------------------------------------------------
# Show surrounding timestamps
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SURROUNDING WATER-LEVEL DATA")
print("=" * 70)

for timestamp in mismatches[TIME_COL]:

    print("\n" + "-" * 70)
    print("Mismatch timestamp:", timestamp)

    window = test[
        (
            test[TIME_COL] >= timestamp - pd.Timedelta(hours=6)
        )
        &
        (
            test[TIME_COL] <= timestamp + pd.Timedelta(hours=6)
        )
    ][
        [
            TIME_COL,
            VALUE_COL,
            TARGET_COL
        ]
    ]

    print(window.to_string(index=False))


# ------------------------------------------------------------
# Safety
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Test shape        :", test.shape)

print("\nSTEP 4.15 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.15 — INVESTIGATING TARGET MISMATCHES
======================================================================

5 MISMATCH ROWS:
Data Acquisition Time  Current_Water_Level  High_Water_6h  Reconstructed_Target
  2025-01-04 18:00:00                 12.9            1.0                     0
  2025-04-04 18:00:00                 12.9            1.0                     0
  2025-06-04 18:00:00                 12.8            1.0                     0
  2025-06-04 19:00:00                 12.7            1.0                     0
  2025-12-04 18:00:00                 13.0            1.0                     0

======================================================================
SURROUNDING WATER-LEVEL DATA
======================================================================

----------------------------------------------------------------------
Mismatch timestamp: 2025-01-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-01-04 12:00:00                 14.1            0.0
  2025-01-04 13:00:00                 14.2            0.0
  2025-01-04 14:00:00                 13.9            0.0
  2025-01-04 16:00:00                 12.9            0.0
  2025-01-04 17:00:00                 12.6            0.0
  2025-01-04 18:00:00                 12.9            1.0
  2025-01-04 19:00:00                 12.8            1.0
  2025-01-04 20:00:00                 12.8            1.0
  2025-01-04 23:00:00                 12.7            1.0

----------------------------------------------------------------------
Mismatch timestamp: 2025-04-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-04-04 17:00:00                 12.9            0.0
  2025-04-04 18:00:00                 12.9            1.0
  2025-04-04 19:00:00                 12.7            1.0
  2025-04-04 20:00:00                 12.0            1.0
  2025-04-04 23:00:00                 11.5            1.0

----------------------------------------------------------------------
Mismatch timestamp: 2025-06-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-06-04 14:00:00                 14.1            0.0
  2025-06-04 15:00:00                 14.3            0.0
  2025-06-04 16:00:00                 13.7            0.0
  2025-06-04 17:00:00                 13.2            0.0
  2025-06-04 18:00:00                 12.8            1.0
  2025-06-04 19:00:00                 12.7            1.0
  2025-06-04 20:00:00                 12.7            1.0
  2025-06-04 21:00:00                 12.7            1.0
  2025-06-04 22:00:00                 12.7            1.0
  2025-06-04 23:00:00                 12.7            1.0

----------------------------------------------------------------------
Mismatch timestamp: 2025-06-04 19:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-06-04 14:00:00                 14.1            0.0
  2025-06-04 15:00:00                 14.3            0.0
  2025-06-04 16:00:00                 13.7            0.0
  2025-06-04 17:00:00                 13.2            0.0
  2025-06-04 18:00:00                 12.8            1.0
  2025-06-04 19:00:00                 12.7            1.0
  2025-06-04 20:00:00                 12.7            1.0
  2025-06-04 21:00:00                 12.7            1.0
  2025-06-04 22:00:00                 12.7            1.0
  2025-06-04 23:00:00                 12.7            1.0

----------------------------------------------------------------------
Mismatch timestamp: 2025-12-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-12-04 13:00:00                 14.1            0.0
  2025-12-04 15:00:00                 13.9            0.0
  2025-12-04 16:00:00                 13.9            0.0
  2025-12-04 17:00:00                 13.6            0.0
  2025-12-04 18:00:00                 13.0            1.0
  2025-12-04 19:00:00                 12.8            1.0
  2025-12-04 20:00:00                 12.7            1.0
  2025-12-04 21:00:00                 12.7            1.0
  2025-12-04 22:00:00                 12.7            1.0
  2025-12-04 23:00:00                 12.7            1.0

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Test shape        : (7309, 21)

STEP 4.15 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [10]:
# ============================================================
# STEP 4.16 — HIGH_WATER_6H TARGET ORIGIN / ANOMALY FORENSIC
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.16 — HIGH_WATER_6H TARGET ORIGIN / ANOMALY FORENSIC")
print("=" * 70)

# ------------------------------------------------------------
# SAFETY COPY
# ------------------------------------------------------------

forensic = df.copy()

forensic["Data Acquisition Time"] = pd.to_datetime(
    forensic["Data Acquisition Time"]
)

forensic = (
    forensic
    .sort_values("Data Acquisition Time")
    .reset_index(drop=True)
)

TIME_COL = "Data Acquisition Time"
VALUE_COL = "Current_Water_Level"
TARGET_COL = "High_Water_6h"

# ------------------------------------------------------------
# PART A — TARGET TRANSITIONS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — TARGET TRANSITIONS")
print("=" * 70)

target_change = (
    forensic[TARGET_COL]
    .ne(forensic[TARGET_COL].shift())
)

transitions = forensic.loc[
    target_change,
    [
        TIME_COL,
        VALUE_COL,
        TARGET_COL
    ]
].copy()

print("Number of target transitions:", len(transitions))

print("\nFirst 50 transitions:")
print(
    transitions
    .head(50)
    .to_string(index=False)
)

# ------------------------------------------------------------
# PART B — TARGET = 1 WITH LOW CURRENT WATER LEVEL
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — TARGET=1 BUT CURRENT LEVEL < 20")
print("=" * 70)

low_target_rows = forensic[
    (forensic[TARGET_COL] == 1)
    &
    (forensic[VALUE_COL] < 20)
][
    [
        TIME_COL,
        VALUE_COL,
        TARGET_COL
    ]
].copy()

print("Rows:", len(low_target_rows))

print(
    low_target_rows
    .head(100)
    .to_string(index=False)
)

# ------------------------------------------------------------
# PART C — TARGET=1 LOW-LEVEL DATE PATTERN
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — LOW-LEVEL TARGET=1 DATE PATTERN")
print("=" * 70)

if len(low_target_rows) > 0:

    low_target_rows["Year"] = (
        low_target_rows[TIME_COL].dt.year
    )

    low_target_rows["Month"] = (
        low_target_rows[TIME_COL].dt.month
    )

    low_target_rows["Day"] = (
        low_target_rows[TIME_COL].dt.day
    )

    print(
        low_target_rows[
            ["Year", "Month", "Day"]
        ]
        .value_counts()
        .head(50)
        .to_string()
    )

# ------------------------------------------------------------
# PART D — TARGET RATE BY MONTH/DAY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — TARGET RATE BY MONTH")
print("=" * 70)

monthly_target = (
    forensic
    .groupby(
        forensic[TIME_COL].dt.month
    )[TARGET_COL]
    .agg(
        Rows="count",
        Positive_Count="sum",
        Positive_Rate="mean"
    )
)

monthly_target["Positive_Rate"] *= 100

print(
    monthly_target
    .to_string()
)

# ------------------------------------------------------------
# PART E — TARGET RATE BY DAY OF MONTH
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART E — TARGET RATE BY DAY OF MONTH")
print("=" * 70)

daily_target = (
    forensic
    .groupby(
        forensic[TIME_COL].dt.day
    )[TARGET_COL]
    .agg(
        Rows="count",
        Positive_Count="sum",
        Positive_Rate="mean"
    )
)

daily_target["Positive_Rate"] *= 100

print(
    daily_target
    .sort_values(
        "Positive_Rate",
        ascending=False
    )
    .head(20)
    .to_string()
)

# ------------------------------------------------------------
# PART F — ALL TARGET=1 LOW-LEVEL ROWS AROUND THE 5 ANOMALIES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PART F — ANOMALOUS TARGET WINDOWS")
print("=" * 70)

anomaly_times = pd.to_datetime([
    "2025-01-04 18:00:00",
    "2025-04-04 18:00:00",
    "2025-06-04 18:00:00",
    "2025-06-04 19:00:00",
    "2025-12-04 18:00:00"
])

for ts in anomaly_times:

    print("\n" + "-" * 70)
    print("ANOMALY:", ts)

    window = forensic[
        (
            forensic[TIME_COL]
            >= ts - pd.Timedelta(hours=12)
        )
        &
        (
            forensic[TIME_COL]
            <= ts + pd.Timedelta(hours=12)
        )
    ][
        [
            TIME_COL,
            VALUE_COL,
            TARGET_COL
        ]
    ]

    print(
        window.to_string(index=False)
    )

# ------------------------------------------------------------
# PART G — SAFETY CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original df shape :", df.shape)
print("Forensic df shape :", forensic.shape)

print("\nSTEP 4.16 COMPLETE")
print("NO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

======================================================================
STEP 4.16 — HIGH_WATER_6H TARGET ORIGIN / ANOMALY FORENSIC
======================================================================

======================================================================
PART A — TARGET TRANSITIONS
======================================================================
Number of target transitions: 24

First 50 transitions:
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2022-01-04 04:00:00                0.283            0.0
  2025-01-04 18:00:00               12.900            1.0
  2025-02-02 00:00:00               32.700            0.0
  2025-02-04 18:00:00               13.000            1.0
  2025-03-02 05:00:00               32.700            0.0
  2025-03-04 20:00:00               12.700            1.0
  2025-04-02 00:00:00               32.700            0.0
  2025-04-04 18:00:00               12.900            1.0
  2025-05-02 00:00:00               32.700            0.0
  2025-05-04 18:00:00               13.000            1.0
  2025-06-02 00:00:00               32.700            0.0
  2025-06-04 18:00:00               12.800            1.0
  2025-07-02 02:00:00               32.700            0.0
  2025-07-04 18:00:00               11.900            1.0
  2025-08-02 00:00:00               32.700            0.0
  2025-08-04 20:00:00               12.700            1.0
  2025-09-02 02:00:00               32.700            0.0
  2025-09-05 12:00:00               60.265            1.0
  2025-10-02 00:00:00               32.700            0.0
  2025-10-04 20:00:00               12.600            1.0
  2025-11-02 00:00:00               32.700            0.0
  2025-11-04 20:00:00               12.400            1.0
  2025-12-03 01:00:00               12.600            0.0
  2025-12-04 18:00:00               13.000            1.0

======================================================================
PART B — TARGET=1 BUT CURRENT LEVEL < 20
======================================================================
Rows: 39
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-01-04 18:00:00                 12.9            1.0
  2025-01-04 19:00:00                 12.8            1.0
  2025-01-04 20:00:00                 12.8            1.0
  2025-01-04 23:00:00                 12.7            1.0
  2025-02-04 18:00:00                 13.0            1.0
  2025-03-04 20:00:00                 12.7            1.0
  2025-03-04 23:00:00                 12.7            1.0
  2025-04-04 18:00:00                 12.9            1.0
  2025-04-04 19:00:00                 12.7            1.0
  2025-04-04 20:00:00                 12.0            1.0
  2025-04-04 23:00:00                 11.5            1.0
  2025-05-04 18:00:00                 13.0            1.0
  2025-05-04 19:00:00                 12.8            1.0
  2025-05-04 21:00:00                 12.4            1.0
  2025-05-04 22:00:00                 12.7            1.0
  2025-06-04 18:00:00                 12.8            1.0
  2025-06-04 19:00:00                 12.7            1.0
  2025-06-04 20:00:00                 12.7            1.0
  2025-06-04 21:00:00                 12.7            1.0
  2025-06-04 22:00:00                 12.7            1.0
  2025-06-04 23:00:00                 12.7            1.0
  2025-07-04 18:00:00                 11.9            1.0
  2025-07-04 19:00:00                 12.7            1.0
  2025-07-04 20:00:00                 12.3            1.0
  2025-07-04 21:00:00                 12.7            1.0
  2025-07-04 22:00:00                 12.7            1.0
  2025-07-04 23:00:00                 11.4            1.0
  2025-08-04 20:00:00                 12.7            1.0
  2025-10-04 20:00:00                 12.6            1.0
  2025-10-04 23:00:00                 12.4            1.0
  2025-11-04 20:00:00                 12.4            1.0
  2025-11-04 22:00:00                 12.7            1.0
  2025-11-04 23:00:00                 13.0            1.0
  2025-12-04 18:00:00                 13.0            1.0
  2025-12-04 19:00:00                 12.8            1.0
  2025-12-04 20:00:00                 12.7            1.0
  2025-12-04 21:00:00                 12.7            1.0
  2025-12-04 22:00:00                 12.7            1.0
  2025-12-04 23:00:00                 12.7            1.0

======================================================================
PART C — LOW-LEVEL TARGET=1 DATE PATTERN
======================================================================
Year  Month  Day
2025  6      4      6
      7      4      6
      12     4      6
      1      4      4
      4      4      4
      5      4      4
      11     4      3
      3      4      2
      10     4      2
      2      4      1
      8      4      1

======================================================================
PART D — TARGET RATE BY MONTH
======================================================================
                       Rows  Positive_Count  Positive_Rate
Data Acquisition Time
1                       548            83.0      15.145985
2                       555            79.0      14.234234
3                       528            83.0      15.719697
4                       505            76.0      15.049505
5                       958           526.0      54.906054
6                       664           129.0      19.427711
7                       622            91.0      14.630225
8                       593            66.0      11.129848
9                       602            72.0      11.960133
10                      556            82.0      14.748201
11                      583            89.0      15.265866
12                      595            88.0      14.789916

======================================================================
PART E — TARGET RATE BY DAY OF MONTH
======================================================================
                       Rows  Positive_Count  Positive_Rate
Data Acquisition Time
1                        24            24.0          100.0
15                        6             6.0          100.0
14                        2             2.0          100.0
13                        3             3.0          100.0
26                       18            18.0          100.0
25                       24            24.0          100.0
24                       24            24.0          100.0
23                       24            24.0          100.0
22                       24            24.0          100.0
21                       24            24.0          100.0
20                       24            24.0          100.0
19                       22            22.0          100.0
18                       11            11.0          100.0
17                        7             7.0          100.0
16                       13            13.0          100.0
28                       24            24.0          100.0
29                       24            24.0          100.0
30                       24            24.0          100.0
27                       23            23.0          100.0
31                       24            24.0          100.0

======================================================================
PART F — ANOMALOUS TARGET WINDOWS
======================================================================

----------------------------------------------------------------------
ANOMALY: 2025-01-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-01-04 07:00:00               13.400            0.0
  2025-01-04 08:00:00               13.400            0.0
  2025-01-04 09:00:00               14.100            0.0
  2025-01-04 10:00:00               14.100            0.0
  2025-01-04 11:00:00               14.100            0.0
  2025-01-04 12:00:00               14.100            0.0
  2025-01-04 13:00:00               14.200            0.0
  2025-01-04 14:00:00               13.900            0.0
  2025-01-04 16:00:00               12.900            0.0
  2025-01-04 17:00:00               12.600            0.0
  2025-01-04 18:00:00               12.900            1.0
  2025-01-04 19:00:00               12.800            1.0
  2025-01-04 20:00:00               12.800            1.0
  2025-01-04 23:00:00               12.700            1.0
  2025-01-05 01:00:00               60.698            1.0
  2025-01-05 02:00:00               60.701            1.0
  2025-01-05 04:00:00               60.714            1.0
  2025-01-05 05:00:00               60.714            1.0
  2025-01-05 06:00:00               60.708            1.0

----------------------------------------------------------------------
ANOMALY: 2025-04-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-04-04 07:00:00               13.600            0.0
  2025-04-04 08:00:00               14.200            0.0
  2025-04-04 09:00:00               14.100            0.0
  2025-04-04 10:00:00               14.100            0.0
  2025-04-04 11:00:00               14.100            0.0
  2025-04-04 17:00:00               12.900            0.0
  2025-04-04 18:00:00               12.900            1.0
  2025-04-04 19:00:00               12.700            1.0
  2025-04-04 20:00:00               12.000            1.0
  2025-04-04 23:00:00               11.500            1.0
  2025-04-05 01:00:00               60.655            1.0
  2025-04-05 02:00:00               60.658            1.0
  2025-04-05 04:00:00               60.664            1.0
  2025-04-05 06:00:00               60.667            1.0

----------------------------------------------------------------------
ANOMALY: 2025-06-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-06-04 06:00:00               12.600            0.0
  2025-06-04 08:00:00               13.700            0.0
  2025-06-04 09:00:00               13.900            0.0
  2025-06-04 10:00:00               14.200            0.0
  2025-06-04 14:00:00               14.100            0.0
  2025-06-04 15:00:00               14.300            0.0
  2025-06-04 16:00:00               13.700            0.0
  2025-06-04 17:00:00               13.200            0.0
  2025-06-04 18:00:00               12.800            1.0
  2025-06-04 19:00:00               12.700            1.0
  2025-06-04 20:00:00               12.700            1.0
  2025-06-04 21:00:00               12.700            1.0
  2025-06-04 22:00:00               12.700            1.0
  2025-06-04 23:00:00               12.700            1.0
  2025-06-05 02:00:00               60.701            1.0
  2025-06-05 03:00:00               60.706            1.0
  2025-06-05 04:00:00               60.707            1.0
  2025-06-05 05:00:00               60.706            1.0

----------------------------------------------------------------------
ANOMALY: 2025-06-04 19:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-06-04 08:00:00               13.700            0.0
  2025-06-04 09:00:00               13.900            0.0
  2025-06-04 10:00:00               14.200            0.0
  2025-06-04 14:00:00               14.100            0.0
  2025-06-04 15:00:00               14.300            0.0
  2025-06-04 16:00:00               13.700            0.0
  2025-06-04 17:00:00               13.200            0.0
  2025-06-04 18:00:00               12.800            1.0
  2025-06-04 19:00:00               12.700            1.0
  2025-06-04 20:00:00               12.700            1.0
  2025-06-04 21:00:00               12.700            1.0
  2025-06-04 22:00:00               12.700            1.0
  2025-06-04 23:00:00               12.700            1.0
  2025-06-05 02:00:00               60.701            1.0
  2025-06-05 03:00:00               60.706            1.0
  2025-06-05 04:00:00               60.707            1.0
  2025-06-05 05:00:00               60.706            1.0

----------------------------------------------------------------------
ANOMALY: 2025-12-04 18:00:00
Data Acquisition Time  Current_Water_Level  High_Water_6h
  2025-12-04 07:00:00               13.400            0.0
  2025-12-04 08:00:00               14.100            0.0
  2025-12-04 09:00:00               14.100            0.0
  2025-12-04 10:00:00               14.300            0.0
  2025-12-04 11:00:00               14.300            0.0
  2025-12-04 13:00:00               14.100            0.0
  2025-12-04 15:00:00               13.900            0.0
  2025-12-04 16:00:00               13.900            0.0
  2025-12-04 17:00:00               13.600            0.0
  2025-12-04 18:00:00               13.000            1.0
  2025-12-04 19:00:00               12.800            1.0
  2025-12-04 20:00:00               12.700            1.0
  2025-12-04 21:00:00               12.700            1.0
  2025-12-04 22:00:00               12.700            1.0
  2025-12-04 23:00:00               12.700            1.0
  2025-12-05 01:00:00               60.646            1.0
  2025-12-05 02:00:00               60.648            1.0
  2025-12-05 03:00:00               60.651            1.0
  2025-12-05 04:00:00               60.649            1.0
  2025-12-05 05:00:00               60.651            1.0
  2025-12-05 06:00:00               60.636            1.0

======================================================================
DATA SAFETY CHECK
======================================================================
Original df shape : (7309, 21)
Forensic df shape : (7309, 21)

STEP 4.16 COMPLETE
NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

In [11]:
# ============================================================
# STEP 4.16 — FINAL TARGET DECISION & ML READINESS CHECK
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.16 — FINAL TARGET DECISION & ML READINESS CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. LOAD VERIFIED FINAL ML DATASET
# ------------------------------------------------------------

FILE = "data/cleaned/final_ml_dataset.csv"

ml_df = pd.read_csv(FILE)

ml_df["Data Acquisition Time"] = pd.to_datetime(
    ml_df["Data Acquisition Time"],
    errors="coerce"
)

ml_df = ml_df.sort_values(
    "Data Acquisition Time"
).reset_index(drop=True)

TARGET = "High_Water_6h"

print("\n" + "=" * 70)
print("DATASET CHECK")
print("=" * 70)

print("File:", FILE)
print("Rows:", len(ml_df))
print("Columns:", len(ml_df.columns))
print("Target:", TARGET)

# ------------------------------------------------------------
# 2. REQUIRED STRUCTURE
# ------------------------------------------------------------

required_columns = [
    "Data Acquisition Time",
    "Current_Water_Level",
    "Month",
    "Hour",
    "DayOfYear",
    "WaterLevel_Lag_1h",
    "WaterLevel_Lag_3h",
    "WaterLevel_Lag_6h",
    "WaterLevel_Lag_12h",
    "WaterLevel_Lag_24h",
    "WaterLevel_RollingMean_6h",
    "WaterLevel_RollingMean_12h",
    "WaterLevel_RollingMean_24h",
    "WaterLevel_RollingMax_24h",
    "WaterLevel_RollingMin_24h",
    "WaterLevel_Change_1h",
    "WaterLevel_Change_3h",
    "WaterLevel_Change_6h",
    "WaterLevel_Change_12h",
    "WaterLevel_Change_24h",
    TARGET
]

missing_columns = [
    col for col in required_columns
    if col not in ml_df.columns
]

print("\nRequired columns:",
      "PASS" if not missing_columns else "FAIL")

if missing_columns:
    print("Missing:", missing_columns)

# ------------------------------------------------------------
# 3. TIMESTAMP CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TIMESTAMP CHECK")
print("=" * 70)

print("Missing timestamps:",
      ml_df["Data Acquisition Time"].isna().sum())

print("Duplicate timestamps:",
      ml_df["Data Acquisition Time"].duplicated().sum())

print(
    "Sorted:",
    ml_df["Data Acquisition Time"].is_monotonic_increasing
)

print(
    "Date range:",
    ml_df["Data Acquisition Time"].min(),
    "to",
    ml_df["Data Acquisition Time"].max()
)

# ------------------------------------------------------------
# 4. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUE CHECK")
print("=" * 70)

missing = ml_df[required_columns].isna().sum()

print(missing)

print(
    "\nTotal missing values:",
    missing.sum()
)

# ------------------------------------------------------------
# 5. TARGET CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET CHECK")
print("=" * 70)

print("Target dtype:", ml_df[TARGET].dtype)

print("\nTarget values:")
print(ml_df[TARGET].value_counts(dropna=False).sort_index())

print("\nTarget proportions:")
print(
    ml_df[TARGET]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
)

# ------------------------------------------------------------
# 6. TARGET VALIDITY
# ------------------------------------------------------------

valid_target = ml_df[TARGET].dropna()

invalid_target_values = sorted(
    set(valid_target.unique()) - {0, 1, 0.0, 1.0}
)

print("\nInvalid target values:", invalid_target_values)

# ------------------------------------------------------------
# 7. FEATURE-TARGET LEAKAGE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FEATURE-TARGET LEAKAGE CHECK")
print("=" * 70)

feature_columns = [
    col for col in required_columns
    if col not in [
        "Data Acquisition Time",
        TARGET
    ]
]

print("Number of candidate features:", len(feature_columns))

# Features whose names directly indicate future information
future_named_features = [
    col for col in feature_columns
    if any(
        word in col.lower()
        for word in [
            "future",
            "target",
            "lead",
            "next"
        ]
    )
]

print(
    "Future/lead/next named features:",
    future_named_features
    if future_named_features
    else "NONE"
)

# ------------------------------------------------------------
# 8. CURRENT TARGET CORRELATION CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET RELATIONSHIP CHECK")
print("=" * 70)

numeric_features = ml_df[
    feature_columns
].select_dtypes(include=np.number).columns.tolist()

correlations = (
    ml_df[numeric_features + [TARGET]]
    .corr(numeric_only=True)[TARGET]
    .drop(TARGET)
    .abs()
    .sort_values(ascending=False)
)

print(
    correlations.to_string()
)

# ------------------------------------------------------------
# 9. FINAL FORENSIC DECISION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL FORENSIC DECISION")
print("=" * 70)

checks = {
    "Dataset rows = 7309": len(ml_df) == 7309,
    "Dataset columns = 21": len(ml_df.columns) == 21,
    "Required columns present": len(missing_columns) == 0,
    "No missing required values": missing.sum() == 0,
    "No duplicate timestamps":
        ml_df["Data Acquisition Time"].duplicated().sum() == 0,
    "Timestamp sorted":
        ml_df["Data Acquisition Time"].is_monotonic_increasing,
    "Binary target":
        len(invalid_target_values) == 0,
    "No future-named features":
        len(future_named_features) == 0
}

for check, result in checks.items():
    print(
        f"{check:<35} : "
        f"{'PASS' if result else 'FAIL'}"
    )

# ------------------------------------------------------------
# 10. TARGET SEMANTICS CONCLUSION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET SEMANTICS CONCLUSION")
print("=" * 70)

print(
    "Validated reconstruction from Step 4.14:"
)

print(
    "Current + future 6h water level >= 60"
)

print(
    "Match rate from forensic test: 99.931591%"
)

print(
    "Known mismatch count: 5 rows"
)

print(
    "\nIMPORTANT:"
)

print(
    "The existing High_Water_6h column is NOT modified."
)

print(
    "The existing target is retained exactly as stored."
)

# ------------------------------------------------------------
# 11. ML READINESS
# ------------------------------------------------------------

all_pass = all(checks.values())

print("\n" + "=" * 70)
print("ML READINESS STATUS")
print("=" * 70)

if all_pass:
    print("STATUS: READY FOR ML PIPELINE")
    print()
    print("Next step:")
    print("STEP 5 — TIME-BASED TRAIN / VALIDATION / TEST SPLIT")
else:
    print("STATUS: NOT READY")
    print()
    print("Resolve the FAILED checks before model training.")

# ------------------------------------------------------------
# 12. DATA SAFETY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA SAFETY CHECK")
print("=" * 70)

print("Original source file:", FILE)
print("Rows loaded:", len(ml_df))
print("Columns loaded:", len(ml_df.columns))

print("\nNO DATA WAS MODIFIED.")
print("NO FEATURES WERE REGENERATED.")
print("NO ROWS WERE DELETED.")

print("\n" + "=" * 70)
print("STEP 4.16 COMPLETE")
print("=" * 70)

======================================================================
STEP 4.16 — FINAL TARGET DECISION & ML READINESS CHECK
======================================================================

======================================================================
DATASET CHECK
======================================================================
File: data/cleaned/final_ml_dataset.csv
Rows: 7309
Columns: 21
Target: High_Water_6h

Required columns: PASS

======================================================================
TIMESTAMP CHECK
======================================================================
Missing timestamps: 0
Duplicate timestamps: 0
Sorted: True
Date range: 2022-01-04 04:00:00 to 2026-06-03 17:00:00

======================================================================
MISSING VALUE CHECK
======================================================================
Data Acquisition Time         0
Current_Water_Level           0
Month                         0
Hour                          0
DayOfYear                     0
WaterLevel_Lag_1h             0
WaterLevel_Lag_3h             0
WaterLevel_Lag_6h             0
WaterLevel_Lag_12h            0
WaterLevel_Lag_24h            0
WaterLevel_RollingMean_6h     0
WaterLevel_RollingMean_12h    0
WaterLevel_RollingMean_24h    0
WaterLevel_RollingMax_24h     0
WaterLevel_RollingMin_24h     0
WaterLevel_Change_1h          0
WaterLevel_Change_3h          0
WaterLevel_Change_6h          0
WaterLevel_Change_12h         0
WaterLevel_Change_24h         0
High_Water_6h                 0
dtype: int64

Total missing values: 0

======================================================================
TARGET CHECK
======================================================================
Target dtype: float64

Target values:
High_Water_6h
0.0    5845
1.0    1464
Name: count, dtype: int64

Target proportions:
High_Water_6h
0.0    79.9699
1.0    20.0301
Name: proportion, dtype: float64

Invalid target values: []

======================================================================
FEATURE-TARGET LEAKAGE CHECK
======================================================================
Number of candidate features: 19
Future/lead/next named features: NONE

======================================================================
TARGET RELATIONSHIP CHECK
======================================================================
Current_Water_Level           0.839474
WaterLevel_Lag_1h             0.838458
WaterLevel_RollingMax_24h     0.837683
WaterLevel_RollingMean_6h     0.837483
WaterLevel_RollingMean_12h    0.833435
WaterLevel_Lag_3h             0.832535
WaterLevel_Lag_6h             0.824561
WaterLevel_RollingMean_24h    0.823496
WaterLevel_Lag_12h            0.808661
WaterLevel_RollingMin_24h     0.782173
WaterLevel_Lag_24h            0.773571
WaterLevel_Change_24h         0.205383
WaterLevel_Change_12h         0.129973
WaterLevel_Change_6h          0.087668
Month                         0.069698
DayOfYear                     0.059937
WaterLevel_Change_3h          0.057281
WaterLevel_Change_1h          0.014712
Hour                          0.011713

======================================================================
FINAL FORENSIC DECISION
======================================================================
Dataset rows = 7309                 : PASS
Dataset columns = 21                : PASS
Required columns present            : PASS
No missing required values          : PASS
No duplicate timestamps             : PASS
Timestamp sorted                    : PASS
Binary target                       : PASS
No future-named features            : PASS

======================================================================
TARGET SEMANTICS CONCLUSION
======================================================================
Validated reconstruction from Step 4.14:
Current + future 6h water level >= 60
Match rate from forensic test: 99.931591%
Known mismatch count: 5 rows

IMPORTANT:
The existing High_Water_6h column is NOT modified.
The existing target is retained exactly as stored.

======================================================================
ML READINESS STATUS
======================================================================
STATUS: READY FOR ML PIPELINE

Next step:
STEP 5 — TIME-BASED TRAIN / VALIDATION / TEST SPLIT

======================================================================
DATA SAFETY CHECK
======================================================================
Original source file: data/cleaned/final_ml_dataset.csv
Rows loaded: 7309
Columns loaded: 21

NO DATA WAS MODIFIED.
NO FEATURES WERE REGENERATED.
NO ROWS WERE DELETED.

======================================================================
STEP 4.16 COMPLETE
======================================================================

In [1]:
import pandas as pd
import numpy as np

FILE_PATH = r"D:\document\Brahmaputra-FloodCast\data\cleaned\water_rainfall_integrated_clean.csv"

df = pd.read_csv(FILE_PATH)

df["Data Acquisition Time"] = pd.to_datetime(
    df["Data Acquisition Time"],
    errors="coerce"
)

df = df.sort_values("Data Acquisition Time").reset_index(drop=True)

print("=" * 70)
print("INTEGRATED DATASET LOADED")
print("=" * 70)

print("Shape:", df.shape)

print("\nDate range:")
print(df["Data Acquisition Time"].min(), "->", df["Data Acquisition Time"].max())

print("\nColumns:")
print(df.columns.tolist())

======================================================================
INTEGRATED DATASET LOADED
======================================================================
Shape: (11124, 34)

Date range:
2022-01-01 20:00:00 -> 2026-12-05 22:00:00

Columns:
['Data Acquisition Time', '_id', 'SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Is_DischargeDataAvailable', 'RL_of_zeroGauge', 'MeanSeaLevel', 'River Water Level Telemetry Hourly (meter)', 'rainfall_1h_sum', 'rainfall_3h_sum', 'rainfall_6h_sum', 'rainfall_12h_sum', 'rainfall_24h_sum', 'rainfall_1h_count', 'rainfall_3h_count', 'rainfall_6h_count', 'rainfall_12h_count', 'rainfall_24h_count']

In [2]:
# ============================================================
# STEP 2 — CREATE FINAL WATER + RAINFALL ML FEATURES
# ============================================================

WATER_LEVEL_FEATURES = [
    "Current_Water_Level",
    "Month",
    "Hour",
    "DayOfYear",

    "WaterLevel_Lag_1h",
    "WaterLevel_Lag_3h",
    "WaterLevel_Lag_6h",
    "WaterLevel_Lag_12h",
    "WaterLevel_Lag_24h",

    "WaterLevel_RollingMean_6h",
    "WaterLevel_RollingMean_12h",
    "WaterLevel_RollingMean_24h",
    "WaterLevel_RollingMax_24h",
    "WaterLevel_RollingMin_24h",

    "WaterLevel_Change_1h",
    "WaterLevel_Change_3h",
    "WaterLevel_Change_6h",
    "WaterLevel_Change_12h",
    "WaterLevel_Change_24h"
]

RAINFALL_FEATURES = [
    "rainfall_1h_sum",
    "rainfall_3h_sum",
    "rainfall_6h_sum",
    "rainfall_12h_sum",
    "rainfall_24h_sum"
]

FEATURES = WATER_LEVEL_FEATURES + RAINFALL_FEATURES

print("=" * 70)
print("FINAL FEATURE PLAN")
print("=" * 70)

print("Water-level features :", len(WATER_LEVEL_FEATURES))
print("Rainfall features    :", len(RAINFALL_FEATURES))
print("Total ML features    :", len(FEATURES))

print("\nFinal features:")

for i, feature in enumerate(FEATURES, 1):
    print(f"{i}. {feature}")

======================================================================
FINAL FEATURE PLAN
======================================================================
Water-level features : 19
Rainfall features    : 5
Total ML features    : 24

Final features:
1. Current_Water_Level
2. Month
3. Hour
4. DayOfYear
5. WaterLevel_Lag_1h
6. WaterLevel_Lag_3h
7. WaterLevel_Lag_6h
8. WaterLevel_Lag_12h
9. WaterLevel_Lag_24h
10. WaterLevel_RollingMean_6h
11. WaterLevel_RollingMean_12h
12. WaterLevel_RollingMean_24h
13. WaterLevel_RollingMax_24h
14. WaterLevel_RollingMin_24h
15. WaterLevel_Change_1h
16. WaterLevel_Change_3h
17. WaterLevel_Change_6h
18. WaterLevel_Change_12h
19. WaterLevel_Change_24h
20. rainfall_1h_sum
21. rainfall_3h_sum
22. rainfall_6h_sum
23. rainfall_12h_sum
24. rainfall_24h_sum

In [3]:
# ============================================================
# STEP 3 — CREATE WATER-LEVEL TIME FEATURES
# ============================================================

WATER_COL = "River Water Level Telemetry Hourly (meter)"
TIME_COL = "Data Acquisition Time"

# Make sure data is sorted
df = df.sort_values(TIME_COL).reset_index(drop=True)

# Current water level
df["Current_Water_Level"] = df[WATER_COL]

# Calendar features
df["Month"] = df[TIME_COL].dt.month
df["Hour"] = df[TIME_COL].dt.hour
df["DayOfYear"] = df[TIME_COL].dt.dayofyear

print("=" * 70)
print("STEP 3 — BASIC WATER-LEVEL FEATURES")
print("=" * 70)

print("Created:")
print("✓ Current_Water_Level")
print("✓ Month")
print("✓ Hour")
print("✓ DayOfYear")

print("\nCurrent shape:", df.shape)

print("\nLatest rows:")
print(
    df[
        [
            TIME_COL,
            WATER_COL,
            "Current_Water_Level",
            "Month",
            "Hour",
            "DayOfYear"
        ]
    ].tail(5).to_string(index=False)
)

======================================================================
STEP 3 — BASIC WATER-LEVEL FEATURES
======================================================================
Created:
✓ Current_Water_Level
✓ Month
✓ Hour
✓ DayOfYear

Current shape: (11124, 38)

Latest rows:
Data Acquisition Time  River Water Level Telemetry Hourly (meter)  Current_Water_Level  Month  Hour  DayOfYear
  2026-12-05 17:00:00                                      60.894               60.894     12    17        339
  2026-12-05 18:00:00                                      60.894               60.894     12    18        339
  2026-12-05 19:00:00                                      60.891               60.891     12    19        339
  2026-12-05 20:00:00                                      60.891               60.891     12    20        339
  2026-12-05 22:00:00                                      60.893               60.893     12    22        339

In [5]:
# =========================================
# STEP 4 — EXACT-TIME LAG FEATURES
# =========================================

print("=" * 70)
print("STEP 4 — EXACT-TIME LAG FEATURES")
print("=" * 70)

# Make sure time is datetime
df[TIME_COL] = pd.to_datetime(df[TIME_COL], errors="coerce")

# Sort chronologically
df = df.sort_values(TIME_COL).reset_index(drop=True)

# Create exact timestamp -> water level lookup
water_series = (
    df.set_index(TIME_COL)["Current_Water_Level"]
    .sort_index()
)

# Required lag periods
lag_hours = [1, 3, 6, 12, 24]

for hours in lag_hours:

    target_times = df[TIME_COL] - pd.Timedelta(hours=hours)

    df[f"WaterLevel_Lag_{hours}h"] = (
        water_series.reindex(target_times).to_numpy()
    )

print("\nCreated lag features:")

for hours in lag_hours:
    col = f"WaterLevel_Lag_{hours}h"
    print(f"✓ {col}")

print("\nLatest rows with lag features:")

print(
    df[
        [
            TIME_COL,
            "Current_Water_Level",
            "WaterLevel_Lag_1h",
            "WaterLevel_Lag_3h",
            "WaterLevel_Lag_6h",
            "WaterLevel_Lag_12h",
            "WaterLevel_Lag_24h"
        ]
    ].tail(10).to_string(index=False)
)

print("\nCurrent shape:", df.shape)

======================================================================
STEP 4 — EXACT-TIME LAG FEATURES
======================================================================

Created lag features:
✓ WaterLevel_Lag_1h
✓ WaterLevel_Lag_3h
✓ WaterLevel_Lag_6h
✓ WaterLevel_Lag_12h
✓ WaterLevel_Lag_24h

Latest rows with lag features:
Data Acquisition Time  Current_Water_Level  WaterLevel_Lag_1h  WaterLevel_Lag_3h  WaterLevel_Lag_6h  WaterLevel_Lag_12h  WaterLevel_Lag_24h
  2026-12-05 12:00:00               60.895             60.895             60.889             60.882              60.883                 NaN
  2026-12-05 13:00:00               60.897             60.895             60.893             60.886              60.882                 NaN
  2026-12-05 14:00:00               60.900             60.897             60.895             60.888              60.882                 NaN
  2026-12-05 15:00:00               60.899             60.900             60.895             60.889              60.882                 NaN
  2026-12-05 16:00:00               60.896             60.899             60.897             60.893              60.882                 NaN
  2026-12-05 17:00:00               60.894             60.896             60.900             60.895              60.882                 NaN
  2026-12-05 18:00:00               60.894             60.894             60.899             60.895              60.882                 NaN
  2026-12-05 19:00:00               60.891             60.894             60.896             60.897              60.886                 NaN
  2026-12-05 20:00:00               60.891             60.891             60.894             60.900              60.888                 NaN
  2026-12-05 22:00:00               60.893                NaN             60.891             60.896              60.893                 NaN

Current shape: (11124, 43)

In [6]:
# =========================================
# STEP 5 — ROLLING WATER-LEVEL FEATURES
# =========================================

print("=" * 70)
print("STEP 5 — ROLLING WATER-LEVEL FEATURES")
print("=" * 70)

# Make sure data is sorted by exact time
df = df.sort_values(TIME_COL).reset_index(drop=True)

# Rolling windows
df["WaterLevel_RollingMean_6h"] = (
    df["Current_Water_Level"]
    .rolling(window=6, min_periods=6)
    .mean()
)

df["WaterLevel_RollingMean_12h"] = (
    df["Current_Water_Level"]
    .rolling(window=12, min_periods=12)
    .mean()
)

df["WaterLevel_RollingMean_24h"] = (
    df["Current_Water_Level"]
    .rolling(window=24, min_periods=24)
    .mean()
)

df["WaterLevel_RollingMax_24h"] = (
    df["Current_Water_Level"]
    .rolling(window=24, min_periods=24)
    .max()
)

df["WaterLevel_RollingMin_24h"] = (
    df["Current_Water_Level"]
    .rolling(window=24, min_periods=24)
    .min()
)

print("\nCreated rolling features:")

rolling_features = [
    "WaterLevel_RollingMean_6h",
    "WaterLevel_RollingMean_12h",
    "WaterLevel_RollingMean_24h",
    "WaterLevel_RollingMax_24h",
    "WaterLevel_RollingMin_24h"
]

for feature in rolling_features:
    print(f"✓ {feature}")

print("\nLatest rows:")

print(
    df[
        [
            TIME_COL,
            "Current_Water_Level",
            "WaterLevel_RollingMean_6h",
            "WaterLevel_RollingMean_12h",
            "WaterLevel_RollingMean_24h",
            "WaterLevel_RollingMax_24h",
            "WaterLevel_RollingMin_24h"
        ]
    ].tail(10).to_string(index=False)
)

print("\nCurrent shape:", df.shape)

print("\nMissing values in rolling features:")

print(
    df[rolling_features]
    .isna()
    .sum()
)

======================================================================
STEP 5 — ROLLING WATER-LEVEL FEATURES
======================================================================

Created rolling features:
✓ WaterLevel_RollingMean_6h
✓ WaterLevel_RollingMean_12h
✓ WaterLevel_RollingMean_24h
✓ WaterLevel_RollingMax_24h
✓ WaterLevel_RollingMin_24h

Latest rows:
Data Acquisition Time  Current_Water_Level  WaterLevel_RollingMean_6h  WaterLevel_RollingMean_12h  WaterLevel_RollingMean_24h  WaterLevel_RollingMax_24h  WaterLevel_RollingMin_24h
  2026-12-05 12:00:00               60.895                  60.891000                   60.886500                   60.895250                     60.937                     60.882
  2026-12-05 13:00:00               60.897                  60.892833                   60.887750                   60.893583                     60.930                     60.882
  2026-12-05 14:00:00               60.900                  60.894833                   60.889250                   60.892333                     60.924                     60.882
  2026-12-05 15:00:00               60.899                  60.896500                   60.890667                   60.891292                     60.916                     60.882
  2026-12-05 16:00:00               60.896                  60.897000                   60.891833                   60.890458                     60.909                     60.882
  2026-12-05 17:00:00               60.894                  60.896833                   60.892833                   60.889833                     60.902                     60.882
  2026-12-05 18:00:00               60.894                  60.896667                   60.893833                   60.889500                     60.900                     60.882
  2026-12-05 19:00:00               60.891                  60.895667                   60.894250                   60.889375                     60.900                     60.882
  2026-12-05 20:00:00               60.891                  60.894167                   60.894500                   60.889417                     60.900                     60.882
  2026-12-05 22:00:00               60.893                  60.893167                   60.894833                   60.889542                     60.900                     60.882

Current shape: (11124, 48)

Missing values in rolling features:
WaterLevel_RollingMean_6h     104
WaterLevel_RollingMean_12h    170
WaterLevel_RollingMean_24h    302
WaterLevel_RollingMax_24h     302
WaterLevel_RollingMin_24h     302
dtype: int64

In [8]:
# =========================================
# STEP 6 — WATER-LEVEL CHANGE / TREND FEATURES
# =========================================

print("=" * 70)
print("STEP 6 — WATER-LEVEL CHANGE / TREND FEATURES")
print("=" * 70)

# Exact-time lookup series
water_series = (
    df.set_index(TIME_COL)["Current_Water_Level"]
    .sort_index()
)

change_hours = [1, 3, 6, 12, 24]

for hours in change_hours:

    target_times = df[TIME_COL] - pd.Timedelta(hours=hours)

    past_values = (
        water_series
        .reindex(target_times)
        .to_numpy()
    )

    df[f"WaterLevel_Change_{hours}h"] = (
        df["Current_Water_Level"].to_numpy()
        - past_values
    )

print("\nCreated change/trend features:")

change_features = [
    "WaterLevel_Change_1h",
    "WaterLevel_Change_3h",
    "WaterLevel_Change_6h",
    "WaterLevel_Change_12h",
    "WaterLevel_Change_24h"
]

for feature in change_features:
    print(f"✓ {feature}")

print("\nLatest rows:")

print(
    df[
        [
            TIME_COL,
            "Current_Water_Level",
            "WaterLevel_Change_1h",
            "WaterLevel_Change_3h",
            "WaterLevel_Change_6h",
            "WaterLevel_Change_12h",
            "WaterLevel_Change_24h"
        ]
    ].tail(10).to_string(index=False)
)

print("\nCurrent shape:", df.shape)

print("\nMissing values in change features:")

print(
    df[change_features]
    .isna()
    .sum()
)

======================================================================
STEP 6 — WATER-LEVEL CHANGE / TREND FEATURES
======================================================================

Created change/trend features:
✓ WaterLevel_Change_1h
✓ WaterLevel_Change_3h
✓ WaterLevel_Change_6h
✓ WaterLevel_Change_12h
✓ WaterLevel_Change_24h

Latest rows:
Data Acquisition Time  Current_Water_Level  WaterLevel_Change_1h  WaterLevel_Change_3h  WaterLevel_Change_6h  WaterLevel_Change_12h  WaterLevel_Change_24h
  2026-12-05 12:00:00               60.895                 0.000                 0.006                 0.013                  0.012                    NaN
  2026-12-05 13:00:00               60.897                 0.002                 0.004                 0.011                  0.015                    NaN
  2026-12-05 14:00:00               60.900                 0.003                 0.005                 0.012                  0.018                    NaN
  2026-12-05 15:00:00               60.899                -0.001                 0.004                 0.010                  0.017                    NaN
  2026-12-05 16:00:00               60.896                -0.003                -0.001                 0.003                  0.014                    NaN
  2026-12-05 17:00:00               60.894                -0.002                -0.006                -0.001                  0.012                    NaN
  2026-12-05 18:00:00               60.894                 0.000                -0.005                -0.001                  0.012                    NaN
  2026-12-05 19:00:00               60.891                -0.003                -0.005                -0.006                  0.005                    NaN
  2026-12-05 20:00:00               60.891                 0.000                -0.003                -0.009                  0.003                    NaN
  2026-12-05 22:00:00               60.893                   NaN                 0.002                -0.003                  0.000                    NaN

Current shape: (11124, 53)

Missing values in change features:
WaterLevel_Change_1h      557
WaterLevel_Change_3h      765
WaterLevel_Change_6h     1064
WaterLevel_Change_12h    1548
WaterLevel_Change_24h    2422
dtype: int64

In [10]:
# =========================================
# STEP 7.1 — RAINFALL TIMESTAMP COVERAGE CHECK
# =========================================

print("=" * 70)
print("STEP 7.1 — RAINFALL TIMESTAMP COVERAGE CHECK")
print("=" * 70)

# Time conversion
df[TIME_COL] = pd.to_datetime(
    df[TIME_COL],
    errors="coerce"
)

print("\nOVERALL DATA RANGE:")
print(df[TIME_COL].min(), "->", df[TIME_COL].max())

print("\nRAINFALL AVAILABILITY BY FEATURE:")

for col in RAINFALL_FEATURES:

    valid = df[df[col].notna()]

    if len(valid) > 0:
        print(
            f"\n{col}"
        )
        print(
            "Rows       :", len(valid)
        )
        print(
            "Date range :", 
            valid[TIME_COL].min(),
            "->",
            valid[TIME_COL].max()
        )
    else:
        print(f"\n{col}: NO DATA")

print("\n" + "=" * 70)
print("RAINFALL TIMESTAMP SAMPLE")
print("=" * 70)

rainfall_available = df[
    df[RAINFALL_FEATURES].notna().any(axis=1)
][
    [TIME_COL] + RAINFALL_FEATURES
]

print(
    rainfall_available
    .sort_values(TIME_COL)
    .head(20)
    .to_string(index=False)
)

print("\n" + "=" * 70)
print("LATEST ROW WITH ANY RAINFALL DATA")
print("=" * 70)

print(
    rainfall_available
    .sort_values(TIME_COL)
    .tail(10)
    .to_string(index=False)
)

======================================================================
STEP 7.1 — RAINFALL TIMESTAMP COVERAGE CHECK
======================================================================

OVERALL DATA RANGE:
2022-01-01 20:00:00 -> 2026-12-05 22:00:00

RAINFALL AVAILABILITY BY FEATURE:

rainfall_1h_sum
Rows       : 393
Date range : 2022-04-03 06:00:00 -> 2026-05-27 06:00:00

rainfall_3h_sum
Rows       : 548
Date range : 2022-04-03 06:00:00 -> 2026-05-27 08:00:00

rainfall_6h_sum
Rows       : 714
Date range : 2022-04-03 06:00:00 -> 2026-05-27 11:00:00

rainfall_12h_sum
Rows       : 978
Date range : 2022-04-03 06:00:00 -> 2026-05-27 17:00:00

rainfall_24h_sum
Rows       : 1316
Date range : 2022-04-03 06:00:00 -> 2026-05-28 05:00:00

======================================================================
RAINFALL TIMESTAMP SAMPLE
======================================================================
Data Acquisition Time  rainfall_1h_sum  rainfall_3h_sum  rainfall_6h_sum  rainfall_12h_sum  rainfall_24h_sum
  2022-04-03 06:00:00              1.0              1.0              1.0               1.0               1.0
  2022-04-03 07:00:00              NaN              1.0              1.0               1.0               1.0
  2022-04-03 08:00:00              NaN              1.0              1.0               1.0               1.0
  2022-04-03 09:00:00              NaN              NaN              1.0               1.0               1.0
  2022-04-03 10:00:00              NaN              NaN              1.0               1.0               1.0
  2022-04-03 11:00:00              NaN              NaN              1.0               1.0               1.0
  2022-04-03 12:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 13:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 14:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 15:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 16:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 17:00:00              NaN              NaN              NaN               1.0               1.0
  2022-04-03 18:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-03 19:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-03 20:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-03 21:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-03 22:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-03 23:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-04 00:00:00              NaN              NaN              NaN               NaN               1.0
  2022-04-04 01:00:00              NaN              NaN              NaN               NaN               1.0

======================================================================
LATEST ROW WITH ANY RAINFALL DATA
======================================================================
Data Acquisition Time  rainfall_1h_sum  rainfall_3h_sum  rainfall_6h_sum  rainfall_12h_sum  rainfall_24h_sum
  2026-05-27 20:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-27 21:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-27 22:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-27 23:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 00:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 01:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 02:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 03:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 04:00:00              NaN              NaN              NaN               NaN               0.2
  2026-05-28 05:00:00              NaN              NaN              NaN               NaN               0.2